/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.Count;
import com.axonivy.connector.successfactors.connector.rest.SFODataPaymentInformationDetailV3JPN;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * CollectionOfPaymentInformationDetailV3JPN
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class CollectionOfPaymentInformationDetailV3JPN {
  @JsonProperty("@odata.count")
  private Count _atOdataCount = null;

  @JsonProperty("value")
  private List<SFODataPaymentInformationDetailV3JPN> value = null;

  public CollectionOfPaymentInformationDetailV3JPN _atOdataCount(Count _atOdataCount) {
    this._atOdataCount = _atOdataCount;
    return this;
  }

   /**
   * Get _atOdataCount
   * @return _atOdataCount
  **/
  public Count getAtOdataCount() {
    return _atOdataCount;
  }

  public void setAtOdataCount(Count _atOdataCount) {
    this._atOdataCount = _atOdataCount;
  }

  public CollectionOfPaymentInformationDetailV3JPN value(List<SFODataPaymentInformationDetailV3JPN> value) {
    this.value = value;
    return this;
  }

  public CollectionOfPaymentInformationDetailV3JPN addValueItem(SFODataPaymentInformationDetailV3JPN valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public List<SFODataPaymentInformationDetailV3JPN> getValue() {
    return value;
  }

  public void setValue(List<SFODataPaymentInformationDetailV3JPN> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectionOfPaymentInformationDetailV3JPN collectionOfPaymentInformationDetailV3JPN = (CollectionOfPaymentInformationDetailV3JPN) o;
    return Objects.equals(this._atOdataCount, collectionOfPaymentInformationDetailV3JPN._atOdataCount) &&
        Objects.equals(this.value, collectionOfPaymentInformationDetailV3JPN.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atOdataCount, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionOfPaymentInformationDetailV3JPN {\n");
    
    sb.append("    _atOdataCount: ").append(toIndentedString(_atOdataCount)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
