/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RefreshInterviewAssessmentsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class RefreshInterviewAssessmentsBody {
  @JsonProperty("jobReqIdParam")
  private AnyOfrefreshInterviewAssessmentsBodyJobReqIdParam jobReqIdParam = null;

  public RefreshInterviewAssessmentsBody jobReqIdParam(AnyOfrefreshInterviewAssessmentsBodyJobReqIdParam jobReqIdParam) {
    this.jobReqIdParam = jobReqIdParam;
    return this;
  }

   /**
   * Get jobReqIdParam
   * @return jobReqIdParam
  **/
  public AnyOfrefreshInterviewAssessmentsBodyJobReqIdParam getJobReqIdParam() {
    return jobReqIdParam;
  }

  public void setJobReqIdParam(AnyOfrefreshInterviewAssessmentsBodyJobReqIdParam jobReqIdParam) {
    this.jobReqIdParam = jobReqIdParam;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefreshInterviewAssessmentsBody refreshInterviewAssessmentsBody = (RefreshInterviewAssessmentsBody) o;
    return Objects.equals(this.jobReqIdParam, refreshInterviewAssessmentsBody.jobReqIdParam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobReqIdParam);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefreshInterviewAssessmentsBody {\n");
    
    sb.append("    jobReqIdParam: ").append(toIndentedString(jobReqIdParam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
