/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataEmpEmployment;
import com.axonivy.connector.successfactors.connector.rest.SFODataPicklistOption;
import com.axonivy.connector.successfactors.connector.rest.SFODataUser;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataEmpGlobalAssignment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataEmpGlobalAssignment {
  @JsonProperty("assignmentClass")
  private String assignmentClass = null;

  @JsonProperty("assignmentType")
  private String assignmentType = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("payrollEndDate")
  private OffsetDateTime payrollEndDate = null;

  @JsonProperty("personIdExternal")
  private String personIdExternal = null;

  @JsonProperty("plannedEndDate")
  private OffsetDateTime plannedEndDate = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("assignmentTypeNav")
  private SFODataPicklistOption assignmentTypeNav = null;

  @JsonProperty("employmentNav")
  private SFODataEmpEmployment employmentNav = null;

  @JsonProperty("userNav")
  private SFODataUser userNav = null;

  public SFODataEmpGlobalAssignment assignmentClass(String assignmentClass) {
    this.assignmentClass = assignmentClass;
    return this;
  }

   /**
   * Get assignmentClass
   * @return assignmentClass
  **/
  public String getAssignmentClass() {
    return assignmentClass;
  }

  public void setAssignmentClass(String assignmentClass) {
    this.assignmentClass = assignmentClass;
  }

  public SFODataEmpGlobalAssignment assignmentType(String assignmentType) {
    this.assignmentType = assignmentType;
    return this;
  }

   /**
   * Get assignmentType
   * @return assignmentType
  **/
  public String getAssignmentType() {
    return assignmentType;
  }

  public void setAssignmentType(String assignmentType) {
    this.assignmentType = assignmentType;
  }

  public SFODataEmpGlobalAssignment createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataEmpGlobalAssignment createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataEmpGlobalAssignment createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataEmpGlobalAssignment endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataEmpGlobalAssignment lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataEmpGlobalAssignment lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataEmpGlobalAssignment lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataEmpGlobalAssignment payrollEndDate(OffsetDateTime payrollEndDate) {
    this.payrollEndDate = payrollEndDate;
    return this;
  }

   /**
   * Get payrollEndDate
   * @return payrollEndDate
  **/
  public OffsetDateTime getPayrollEndDate() {
    return payrollEndDate;
  }

  public void setPayrollEndDate(OffsetDateTime payrollEndDate) {
    this.payrollEndDate = payrollEndDate;
  }

  public SFODataEmpGlobalAssignment personIdExternal(String personIdExternal) {
    this.personIdExternal = personIdExternal;
    return this;
  }

   /**
   * Get personIdExternal
   * @return personIdExternal
  **/
  public String getPersonIdExternal() {
    return personIdExternal;
  }

  public void setPersonIdExternal(String personIdExternal) {
    this.personIdExternal = personIdExternal;
  }

  public SFODataEmpGlobalAssignment plannedEndDate(OffsetDateTime plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
    return this;
  }

   /**
   * Get plannedEndDate
   * @return plannedEndDate
  **/
  public OffsetDateTime getPlannedEndDate() {
    return plannedEndDate;
  }

  public void setPlannedEndDate(OffsetDateTime plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
  }

  public SFODataEmpGlobalAssignment startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SFODataEmpGlobalAssignment userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataEmpGlobalAssignment assignmentTypeNav(SFODataPicklistOption assignmentTypeNav) {
    this.assignmentTypeNav = assignmentTypeNav;
    return this;
  }

   /**
   * Get assignmentTypeNav
   * @return assignmentTypeNav
  **/
  public SFODataPicklistOption getAssignmentTypeNav() {
    return assignmentTypeNav;
  }

  public void setAssignmentTypeNav(SFODataPicklistOption assignmentTypeNav) {
    this.assignmentTypeNav = assignmentTypeNav;
  }

  public SFODataEmpGlobalAssignment employmentNav(SFODataEmpEmployment employmentNav) {
    this.employmentNav = employmentNav;
    return this;
  }

   /**
   * Get employmentNav
   * @return employmentNav
  **/
  public SFODataEmpEmployment getEmploymentNav() {
    return employmentNav;
  }

  public void setEmploymentNav(SFODataEmpEmployment employmentNav) {
    this.employmentNav = employmentNav;
  }

  public SFODataEmpGlobalAssignment userNav(SFODataUser userNav) {
    this.userNav = userNav;
    return this;
  }

   /**
   * Get userNav
   * @return userNav
  **/
  public SFODataUser getUserNav() {
    return userNav;
  }

  public void setUserNav(SFODataUser userNav) {
    this.userNav = userNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataEmpGlobalAssignment sfODataEmpGlobalAssignment = (SFODataEmpGlobalAssignment) o;
    return Objects.equals(this.assignmentClass, sfODataEmpGlobalAssignment.assignmentClass) &&
        Objects.equals(this.assignmentType, sfODataEmpGlobalAssignment.assignmentType) &&
        Objects.equals(this.createdBy, sfODataEmpGlobalAssignment.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataEmpGlobalAssignment.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataEmpGlobalAssignment.createdOn) &&
        Objects.equals(this.endDate, sfODataEmpGlobalAssignment.endDate) &&
        Objects.equals(this.lastModifiedBy, sfODataEmpGlobalAssignment.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataEmpGlobalAssignment.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataEmpGlobalAssignment.lastModifiedOn) &&
        Objects.equals(this.payrollEndDate, sfODataEmpGlobalAssignment.payrollEndDate) &&
        Objects.equals(this.personIdExternal, sfODataEmpGlobalAssignment.personIdExternal) &&
        Objects.equals(this.plannedEndDate, sfODataEmpGlobalAssignment.plannedEndDate) &&
        Objects.equals(this.startDate, sfODataEmpGlobalAssignment.startDate) &&
        Objects.equals(this.userId, sfODataEmpGlobalAssignment.userId) &&
        Objects.equals(this.assignmentTypeNav, sfODataEmpGlobalAssignment.assignmentTypeNav) &&
        Objects.equals(this.employmentNav, sfODataEmpGlobalAssignment.employmentNav) &&
        Objects.equals(this.userNav, sfODataEmpGlobalAssignment.userNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignmentClass, assignmentType, createdBy, createdDateTime, createdOn, endDate, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, payrollEndDate, personIdExternal, plannedEndDate, startDate, userId, assignmentTypeNav, employmentNav, userNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataEmpGlobalAssignment {\n");
    
    sb.append("    assignmentClass: ").append(toIndentedString(assignmentClass)).append("\n");
    sb.append("    assignmentType: ").append(toIndentedString(assignmentType)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    payrollEndDate: ").append(toIndentedString(payrollEndDate)).append("\n");
    sb.append("    personIdExternal: ").append(toIndentedString(personIdExternal)).append("\n");
    sb.append("    plannedEndDate: ").append(toIndentedString(plannedEndDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    assignmentTypeNav: ").append(toIndentedString(assignmentTypeNav)).append("\n");
    sb.append("    employmentNav: ").append(toIndentedString(employmentNav)).append("\n");
    sb.append("    userNav: ").append(toIndentedString(userNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
