/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataMDFEnumValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataJobClassificationFRA
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataJobClassificationFRA {
  @JsonProperty("JobClassificationCountry_country")
  private String jobClassificationCountryCountry = null;

  @JsonProperty("JobClassification_effectiveStartDate")
  private OffsetDateTime jobClassificationEffectiveStartDate = null;

  @JsonProperty("JobClassification_externalCode")
  private String jobClassificationExternalCode = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("employeeCategory")
  private AnyOfSFODataJobClassificationFRAEmployeeCategory employeeCategory = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataJobClassificationFRAExternalCode externalCode = null;

  @JsonProperty("inseeCode")
  private String inseeCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("createdByNav")
  private AllOfSFODataJobClassificationFRACreatedByNav createdByNav = null;

  @JsonProperty("lastModifiedByNav")
  private AllOfSFODataJobClassificationFRALastModifiedByNav lastModifiedByNav = null;

  @JsonProperty("mdfSystemRecordStatusNav")
  private SFODataMDFEnumValue mdfSystemRecordStatusNav = null;

  public SFODataJobClassificationFRA jobClassificationCountryCountry(String jobClassificationCountryCountry) {
    this.jobClassificationCountryCountry = jobClassificationCountryCountry;
    return this;
  }

   /**
   * Get jobClassificationCountryCountry
   * @return jobClassificationCountryCountry
  **/
  public String getJobClassificationCountryCountry() {
    return jobClassificationCountryCountry;
  }

  public void setJobClassificationCountryCountry(String jobClassificationCountryCountry) {
    this.jobClassificationCountryCountry = jobClassificationCountryCountry;
  }

  public SFODataJobClassificationFRA jobClassificationEffectiveStartDate(OffsetDateTime jobClassificationEffectiveStartDate) {
    this.jobClassificationEffectiveStartDate = jobClassificationEffectiveStartDate;
    return this;
  }

   /**
   * Get jobClassificationEffectiveStartDate
   * @return jobClassificationEffectiveStartDate
  **/
  public OffsetDateTime getJobClassificationEffectiveStartDate() {
    return jobClassificationEffectiveStartDate;
  }

  public void setJobClassificationEffectiveStartDate(OffsetDateTime jobClassificationEffectiveStartDate) {
    this.jobClassificationEffectiveStartDate = jobClassificationEffectiveStartDate;
  }

  public SFODataJobClassificationFRA jobClassificationExternalCode(String jobClassificationExternalCode) {
    this.jobClassificationExternalCode = jobClassificationExternalCode;
    return this;
  }

   /**
   * Get jobClassificationExternalCode
   * @return jobClassificationExternalCode
  **/
  public String getJobClassificationExternalCode() {
    return jobClassificationExternalCode;
  }

  public void setJobClassificationExternalCode(String jobClassificationExternalCode) {
    this.jobClassificationExternalCode = jobClassificationExternalCode;
  }

  public SFODataJobClassificationFRA createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataJobClassificationFRA createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataJobClassificationFRA employeeCategory(AnyOfSFODataJobClassificationFRAEmployeeCategory employeeCategory) {
    this.employeeCategory = employeeCategory;
    return this;
  }

   /**
   * Get employeeCategory
   * @return employeeCategory
  **/
  public AnyOfSFODataJobClassificationFRAEmployeeCategory getEmployeeCategory() {
    return employeeCategory;
  }

  public void setEmployeeCategory(AnyOfSFODataJobClassificationFRAEmployeeCategory employeeCategory) {
    this.employeeCategory = employeeCategory;
  }

  public SFODataJobClassificationFRA externalCode(AnyOfSFODataJobClassificationFRAExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataJobClassificationFRAExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataJobClassificationFRAExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataJobClassificationFRA inseeCode(String inseeCode) {
    this.inseeCode = inseeCode;
    return this;
  }

   /**
   * Get inseeCode
   * @return inseeCode
  **/
  public String getInseeCode() {
    return inseeCode;
  }

  public void setInseeCode(String inseeCode) {
    this.inseeCode = inseeCode;
  }

  public SFODataJobClassificationFRA lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataJobClassificationFRA lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataJobClassificationFRA mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataJobClassificationFRA createdByNav(AllOfSFODataJobClassificationFRACreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
    return this;
  }

   /**
   * Get createdByNav
   * @return createdByNav
  **/
  public AllOfSFODataJobClassificationFRACreatedByNav getCreatedByNav() {
    return createdByNav;
  }

  public void setCreatedByNav(AllOfSFODataJobClassificationFRACreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
  }

  public SFODataJobClassificationFRA lastModifiedByNav(AllOfSFODataJobClassificationFRALastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
    return this;
  }

   /**
   * Get lastModifiedByNav
   * @return lastModifiedByNav
  **/
  public AllOfSFODataJobClassificationFRALastModifiedByNav getLastModifiedByNav() {
    return lastModifiedByNav;
  }

  public void setLastModifiedByNav(AllOfSFODataJobClassificationFRALastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
  }

  public SFODataJobClassificationFRA mdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNav
   * @return mdfSystemRecordStatusNav
  **/
  public SFODataMDFEnumValue getMdfSystemRecordStatusNav() {
    return mdfSystemRecordStatusNav;
  }

  public void setMdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataJobClassificationFRA sfODataJobClassificationFRA = (SFODataJobClassificationFRA) o;
    return Objects.equals(this.jobClassificationCountryCountry, sfODataJobClassificationFRA.jobClassificationCountryCountry) &&
        Objects.equals(this.jobClassificationEffectiveStartDate, sfODataJobClassificationFRA.jobClassificationEffectiveStartDate) &&
        Objects.equals(this.jobClassificationExternalCode, sfODataJobClassificationFRA.jobClassificationExternalCode) &&
        Objects.equals(this.createdBy, sfODataJobClassificationFRA.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataJobClassificationFRA.createdDateTime) &&
        Objects.equals(this.employeeCategory, sfODataJobClassificationFRA.employeeCategory) &&
        Objects.equals(this.externalCode, sfODataJobClassificationFRA.externalCode) &&
        Objects.equals(this.inseeCode, sfODataJobClassificationFRA.inseeCode) &&
        Objects.equals(this.lastModifiedBy, sfODataJobClassificationFRA.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataJobClassificationFRA.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataJobClassificationFRA.mdfSystemRecordStatus) &&
        Objects.equals(this.createdByNav, sfODataJobClassificationFRA.createdByNav) &&
        Objects.equals(this.lastModifiedByNav, sfODataJobClassificationFRA.lastModifiedByNav) &&
        Objects.equals(this.mdfSystemRecordStatusNav, sfODataJobClassificationFRA.mdfSystemRecordStatusNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobClassificationCountryCountry, jobClassificationEffectiveStartDate, jobClassificationExternalCode, createdBy, createdDateTime, employeeCategory, externalCode, inseeCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, createdByNav, lastModifiedByNav, mdfSystemRecordStatusNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataJobClassificationFRA {\n");
    
    sb.append("    jobClassificationCountryCountry: ").append(toIndentedString(jobClassificationCountryCountry)).append("\n");
    sb.append("    jobClassificationEffectiveStartDate: ").append(toIndentedString(jobClassificationEffectiveStartDate)).append("\n");
    sb.append("    jobClassificationExternalCode: ").append(toIndentedString(jobClassificationExternalCode)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    employeeCategory: ").append(toIndentedString(employeeCategory)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    inseeCode: ").append(toIndentedString(inseeCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    createdByNav: ").append(toIndentedString(createdByNav)).append("\n");
    sb.append("    lastModifiedByNav: ").append(toIndentedString(lastModifiedByNav)).append("\n");
    sb.append("    mdfSystemRecordStatusNav: ").append(toIndentedString(mdfSystemRecordStatusNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
