/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Complex type that contains password validation result, password salt and password hash.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataThemeContentConfig {
  @JsonProperty("bgColor")
  private AllOfSFODataThemeContentConfigBgColor bgColor = null;

  @JsonProperty("bgColorVariant")
  private AllOfSFODataThemeContentConfigBgColorVariant bgColorVariant = null;

  @JsonProperty("iconScheme")
  private String iconScheme = null;

  @JsonProperty("linkTextColor")
  private AllOfSFODataThemeContentConfigLinkTextColor linkTextColor = null;

  @JsonProperty("textColor")
  private AllOfSFODataThemeContentConfigTextColor textColor = null;

  @JsonProperty("textColorVariant")
  private AllOfSFODataThemeContentConfigTextColorVariant textColorVariant = null;

  public SFODataThemeContentConfig bgColor(AllOfSFODataThemeContentConfigBgColor bgColor) {
    this.bgColor = bgColor;
    return this;
  }

   /**
   * Get bgColor
   * @return bgColor
  **/
  public AllOfSFODataThemeContentConfigBgColor getBgColor() {
    return bgColor;
  }

  public void setBgColor(AllOfSFODataThemeContentConfigBgColor bgColor) {
    this.bgColor = bgColor;
  }

  public SFODataThemeContentConfig bgColorVariant(AllOfSFODataThemeContentConfigBgColorVariant bgColorVariant) {
    this.bgColorVariant = bgColorVariant;
    return this;
  }

   /**
   * Get bgColorVariant
   * @return bgColorVariant
  **/
  public AllOfSFODataThemeContentConfigBgColorVariant getBgColorVariant() {
    return bgColorVariant;
  }

  public void setBgColorVariant(AllOfSFODataThemeContentConfigBgColorVariant bgColorVariant) {
    this.bgColorVariant = bgColorVariant;
  }

  public SFODataThemeContentConfig iconScheme(String iconScheme) {
    this.iconScheme = iconScheme;
    return this;
  }

   /**
   * Get iconScheme
   * @return iconScheme
  **/
  public String getIconScheme() {
    return iconScheme;
  }

  public void setIconScheme(String iconScheme) {
    this.iconScheme = iconScheme;
  }

  public SFODataThemeContentConfig linkTextColor(AllOfSFODataThemeContentConfigLinkTextColor linkTextColor) {
    this.linkTextColor = linkTextColor;
    return this;
  }

   /**
   * Get linkTextColor
   * @return linkTextColor
  **/
  public AllOfSFODataThemeContentConfigLinkTextColor getLinkTextColor() {
    return linkTextColor;
  }

  public void setLinkTextColor(AllOfSFODataThemeContentConfigLinkTextColor linkTextColor) {
    this.linkTextColor = linkTextColor;
  }

  public SFODataThemeContentConfig textColor(AllOfSFODataThemeContentConfigTextColor textColor) {
    this.textColor = textColor;
    return this;
  }

   /**
   * Get textColor
   * @return textColor
  **/
  public AllOfSFODataThemeContentConfigTextColor getTextColor() {
    return textColor;
  }

  public void setTextColor(AllOfSFODataThemeContentConfigTextColor textColor) {
    this.textColor = textColor;
  }

  public SFODataThemeContentConfig textColorVariant(AllOfSFODataThemeContentConfigTextColorVariant textColorVariant) {
    this.textColorVariant = textColorVariant;
    return this;
  }

   /**
   * Get textColorVariant
   * @return textColorVariant
  **/
  public AllOfSFODataThemeContentConfigTextColorVariant getTextColorVariant() {
    return textColorVariant;
  }

  public void setTextColorVariant(AllOfSFODataThemeContentConfigTextColorVariant textColorVariant) {
    this.textColorVariant = textColorVariant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataThemeContentConfig sfODataThemeContentConfig = (SFODataThemeContentConfig) o;
    return Objects.equals(this.bgColor, sfODataThemeContentConfig.bgColor) &&
        Objects.equals(this.bgColorVariant, sfODataThemeContentConfig.bgColorVariant) &&
        Objects.equals(this.iconScheme, sfODataThemeContentConfig.iconScheme) &&
        Objects.equals(this.linkTextColor, sfODataThemeContentConfig.linkTextColor) &&
        Objects.equals(this.textColor, sfODataThemeContentConfig.textColor) &&
        Objects.equals(this.textColorVariant, sfODataThemeContentConfig.textColorVariant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bgColor, bgColorVariant, iconScheme, linkTextColor, textColor, textColorVariant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataThemeContentConfig {\n");
    
    sb.append("    bgColor: ").append(toIndentedString(bgColor)).append("\n");
    sb.append("    bgColorVariant: ").append(toIndentedString(bgColorVariant)).append("\n");
    sb.append("    iconScheme: ").append(toIndentedString(iconScheme)).append("\n");
    sb.append("    linkTextColor: ").append(toIndentedString(linkTextColor)).append("\n");
    sb.append("    textColor: ").append(toIndentedString(textColor)).append("\n");
    sb.append("    textColorVariant: ").append(toIndentedString(textColorVariant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
