/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataPhotoUpsert
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataPhotoUpsert {
  @JsonProperty("metadataUri")
  private String metadataUri = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("mimeType")
  private String mimeType = null;

  @JsonProperty("personUUID")
  private String personUUID = null;

  @JsonProperty("photo")
  private String photo = null;

  @JsonProperty("photoHash")
  private String photoHash = null;

  @JsonProperty("photoId")
  private String photoId = null;

  @JsonProperty("photoName")
  private String photoName = null;

  @JsonProperty("photoType")
  private Integer photoType = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("width")
  private Integer width = null;

  public SFODataPhotoUpsert metadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
    return this;
  }

   /**
   * Get metadataUri
   * @return metadataUri
  **/
  public String getMetadataUri() {
    return metadataUri;
  }

  public void setMetadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
  }

  public SFODataPhotoUpsert height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public SFODataPhotoUpsert mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Get mimeType
   * @return mimeType
  **/
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public SFODataPhotoUpsert personUUID(String personUUID) {
    this.personUUID = personUUID;
    return this;
  }

   /**
   * Get personUUID
   * @return personUUID
  **/
  public String getPersonUUID() {
    return personUUID;
  }

  public void setPersonUUID(String personUUID) {
    this.personUUID = personUUID;
  }

  public SFODataPhotoUpsert photo(String photo) {
    this.photo = photo;
    return this;
  }

   /**
   * Get photo
   * @return photo
  **/
  public String getPhoto() {
    return photo;
  }

  public void setPhoto(String photo) {
    this.photo = photo;
  }

  public SFODataPhotoUpsert photoHash(String photoHash) {
    this.photoHash = photoHash;
    return this;
  }

   /**
   * Get photoHash
   * @return photoHash
  **/
  public String getPhotoHash() {
    return photoHash;
  }

  public void setPhotoHash(String photoHash) {
    this.photoHash = photoHash;
  }

  public SFODataPhotoUpsert photoId(String photoId) {
    this.photoId = photoId;
    return this;
  }

   /**
   * Get photoId
   * @return photoId
  **/
  public String getPhotoId() {
    return photoId;
  }

  public void setPhotoId(String photoId) {
    this.photoId = photoId;
  }

  public SFODataPhotoUpsert photoName(String photoName) {
    this.photoName = photoName;
    return this;
  }

   /**
   * Get photoName
   * @return photoName
  **/
  public String getPhotoName() {
    return photoName;
  }

  public void setPhotoName(String photoName) {
    this.photoName = photoName;
  }

  public SFODataPhotoUpsert photoType(Integer photoType) {
    this.photoType = photoType;
    return this;
  }

   /**
   * Get photoType
   * @return photoType
  **/
  public Integer getPhotoType() {
    return photoType;
  }

  public void setPhotoType(Integer photoType) {
    this.photoType = photoType;
  }

  public SFODataPhotoUpsert userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataPhotoUpsert width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataPhotoUpsert sfODataPhotoUpsert = (SFODataPhotoUpsert) o;
    return Objects.equals(this.metadataUri, sfODataPhotoUpsert.metadataUri) &&
        Objects.equals(this.height, sfODataPhotoUpsert.height) &&
        Objects.equals(this.mimeType, sfODataPhotoUpsert.mimeType) &&
        Objects.equals(this.personUUID, sfODataPhotoUpsert.personUUID) &&
        Objects.equals(this.photo, sfODataPhotoUpsert.photo) &&
        Objects.equals(this.photoHash, sfODataPhotoUpsert.photoHash) &&
        Objects.equals(this.photoId, sfODataPhotoUpsert.photoId) &&
        Objects.equals(this.photoName, sfODataPhotoUpsert.photoName) &&
        Objects.equals(this.photoType, sfODataPhotoUpsert.photoType) &&
        Objects.equals(this.userId, sfODataPhotoUpsert.userId) &&
        Objects.equals(this.width, sfODataPhotoUpsert.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadataUri, height, mimeType, personUUID, photo, photoHash, photoId, photoName, photoType, userId, width);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataPhotoUpsert {\n");
    
    sb.append("    metadataUri: ").append(toIndentedString(metadataUri)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    personUUID: ").append(toIndentedString(personUUID)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    photoHash: ").append(toIndentedString(photoHash)).append("\n");
    sb.append("    photoId: ").append(toIndentedString(photoId)).append("\n");
    sb.append("    photoName: ").append(toIndentedString(photoName)).append("\n");
    sb.append("    photoType: ").append(toIndentedString(photoType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
