/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataHolidayCalendarCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataHolidayCalendarCreate {
  @JsonProperty("country")
  private String country = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("entityUUID")
  private String entityUUID = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("name_da_DK")
  private String nameDaDK = null;

  @JsonProperty("name_de_CH")
  private String nameDeCH = null;

  @JsonProperty("name_de_DE")
  private String nameDeDE = null;

  @JsonProperty("name_defaultValue")
  private String nameDefaultValue = null;

  @JsonProperty("name_en_DEBUG")
  private String nameEnDEBUG = null;

  @JsonProperty("name_en_GB")
  private String nameEnGB = null;

  @JsonProperty("name_es_ES")
  private String nameEsES = null;

  @JsonProperty("name_fi_FI")
  private String nameFiFI = null;

  @JsonProperty("name_fr_FR")
  private String nameFrFR = null;

  @JsonProperty("name_hu_HU")
  private String nameHuHU = null;

  @JsonProperty("name_it_IT")
  private String nameItIT = null;

  @JsonProperty("name_localized")
  private String nameLocalized = null;

  @JsonProperty("name_nb_NO")
  private String nameNbNO = null;

  @JsonProperty("name_nl_NL")
  private String nameNlNL = null;

  @JsonProperty("name_pl_PL")
  private String namePlPL = null;

  @JsonProperty("name_pt_PT")
  private String namePtPT = null;

  @JsonProperty("name_sv_SE")
  private String nameSvSE = null;

  @JsonProperty("oldName")
  private String oldName = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  public SFODataHolidayCalendarCreate country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public SFODataHolidayCalendarCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataHolidayCalendarCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataHolidayCalendarCreate entityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
    return this;
  }

   /**
   * Get entityUUID
   * @return entityUUID
  **/
  public String getEntityUUID() {
    return entityUUID;
  }

  public void setEntityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
  }

  public SFODataHolidayCalendarCreate externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataHolidayCalendarCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataHolidayCalendarCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataHolidayCalendarCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataHolidayCalendarCreate nameDaDK(String nameDaDK) {
    this.nameDaDK = nameDaDK;
    return this;
  }

   /**
   * Get nameDaDK
   * @return nameDaDK
  **/
  public String getNameDaDK() {
    return nameDaDK;
  }

  public void setNameDaDK(String nameDaDK) {
    this.nameDaDK = nameDaDK;
  }

  public SFODataHolidayCalendarCreate nameDeCH(String nameDeCH) {
    this.nameDeCH = nameDeCH;
    return this;
  }

   /**
   * Get nameDeCH
   * @return nameDeCH
  **/
  public String getNameDeCH() {
    return nameDeCH;
  }

  public void setNameDeCH(String nameDeCH) {
    this.nameDeCH = nameDeCH;
  }

  public SFODataHolidayCalendarCreate nameDeDE(String nameDeDE) {
    this.nameDeDE = nameDeDE;
    return this;
  }

   /**
   * Get nameDeDE
   * @return nameDeDE
  **/
  public String getNameDeDE() {
    return nameDeDE;
  }

  public void setNameDeDE(String nameDeDE) {
    this.nameDeDE = nameDeDE;
  }

  public SFODataHolidayCalendarCreate nameDefaultValue(String nameDefaultValue) {
    this.nameDefaultValue = nameDefaultValue;
    return this;
  }

   /**
   * Get nameDefaultValue
   * @return nameDefaultValue
  **/
  public String getNameDefaultValue() {
    return nameDefaultValue;
  }

  public void setNameDefaultValue(String nameDefaultValue) {
    this.nameDefaultValue = nameDefaultValue;
  }

  public SFODataHolidayCalendarCreate nameEnDEBUG(String nameEnDEBUG) {
    this.nameEnDEBUG = nameEnDEBUG;
    return this;
  }

   /**
   * Get nameEnDEBUG
   * @return nameEnDEBUG
  **/
  public String getNameEnDEBUG() {
    return nameEnDEBUG;
  }

  public void setNameEnDEBUG(String nameEnDEBUG) {
    this.nameEnDEBUG = nameEnDEBUG;
  }

  public SFODataHolidayCalendarCreate nameEnGB(String nameEnGB) {
    this.nameEnGB = nameEnGB;
    return this;
  }

   /**
   * Get nameEnGB
   * @return nameEnGB
  **/
  public String getNameEnGB() {
    return nameEnGB;
  }

  public void setNameEnGB(String nameEnGB) {
    this.nameEnGB = nameEnGB;
  }

  public SFODataHolidayCalendarCreate nameEsES(String nameEsES) {
    this.nameEsES = nameEsES;
    return this;
  }

   /**
   * Get nameEsES
   * @return nameEsES
  **/
  public String getNameEsES() {
    return nameEsES;
  }

  public void setNameEsES(String nameEsES) {
    this.nameEsES = nameEsES;
  }

  public SFODataHolidayCalendarCreate nameFiFI(String nameFiFI) {
    this.nameFiFI = nameFiFI;
    return this;
  }

   /**
   * Get nameFiFI
   * @return nameFiFI
  **/
  public String getNameFiFI() {
    return nameFiFI;
  }

  public void setNameFiFI(String nameFiFI) {
    this.nameFiFI = nameFiFI;
  }

  public SFODataHolidayCalendarCreate nameFrFR(String nameFrFR) {
    this.nameFrFR = nameFrFR;
    return this;
  }

   /**
   * Get nameFrFR
   * @return nameFrFR
  **/
  public String getNameFrFR() {
    return nameFrFR;
  }

  public void setNameFrFR(String nameFrFR) {
    this.nameFrFR = nameFrFR;
  }

  public SFODataHolidayCalendarCreate nameHuHU(String nameHuHU) {
    this.nameHuHU = nameHuHU;
    return this;
  }

   /**
   * Get nameHuHU
   * @return nameHuHU
  **/
  public String getNameHuHU() {
    return nameHuHU;
  }

  public void setNameHuHU(String nameHuHU) {
    this.nameHuHU = nameHuHU;
  }

  public SFODataHolidayCalendarCreate nameItIT(String nameItIT) {
    this.nameItIT = nameItIT;
    return this;
  }

   /**
   * Get nameItIT
   * @return nameItIT
  **/
  public String getNameItIT() {
    return nameItIT;
  }

  public void setNameItIT(String nameItIT) {
    this.nameItIT = nameItIT;
  }

  public SFODataHolidayCalendarCreate nameLocalized(String nameLocalized) {
    this.nameLocalized = nameLocalized;
    return this;
  }

   /**
   * Get nameLocalized
   * @return nameLocalized
  **/
  public String getNameLocalized() {
    return nameLocalized;
  }

  public void setNameLocalized(String nameLocalized) {
    this.nameLocalized = nameLocalized;
  }

  public SFODataHolidayCalendarCreate nameNbNO(String nameNbNO) {
    this.nameNbNO = nameNbNO;
    return this;
  }

   /**
   * Get nameNbNO
   * @return nameNbNO
  **/
  public String getNameNbNO() {
    return nameNbNO;
  }

  public void setNameNbNO(String nameNbNO) {
    this.nameNbNO = nameNbNO;
  }

  public SFODataHolidayCalendarCreate nameNlNL(String nameNlNL) {
    this.nameNlNL = nameNlNL;
    return this;
  }

   /**
   * Get nameNlNL
   * @return nameNlNL
  **/
  public String getNameNlNL() {
    return nameNlNL;
  }

  public void setNameNlNL(String nameNlNL) {
    this.nameNlNL = nameNlNL;
  }

  public SFODataHolidayCalendarCreate namePlPL(String namePlPL) {
    this.namePlPL = namePlPL;
    return this;
  }

   /**
   * Get namePlPL
   * @return namePlPL
  **/
  public String getNamePlPL() {
    return namePlPL;
  }

  public void setNamePlPL(String namePlPL) {
    this.namePlPL = namePlPL;
  }

  public SFODataHolidayCalendarCreate namePtPT(String namePtPT) {
    this.namePtPT = namePtPT;
    return this;
  }

   /**
   * Get namePtPT
   * @return namePtPT
  **/
  public String getNamePtPT() {
    return namePtPT;
  }

  public void setNamePtPT(String namePtPT) {
    this.namePtPT = namePtPT;
  }

  public SFODataHolidayCalendarCreate nameSvSE(String nameSvSE) {
    this.nameSvSE = nameSvSE;
    return this;
  }

   /**
   * Get nameSvSE
   * @return nameSvSE
  **/
  public String getNameSvSE() {
    return nameSvSE;
  }

  public void setNameSvSE(String nameSvSE) {
    this.nameSvSE = nameSvSE;
  }

  public SFODataHolidayCalendarCreate oldName(String oldName) {
    this.oldName = oldName;
    return this;
  }

   /**
   * Get oldName
   * @return oldName
  **/
  public String getOldName() {
    return oldName;
  }

  public void setOldName(String oldName) {
    this.oldName = oldName;
  }

  public SFODataHolidayCalendarCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataHolidayCalendarCreate sfODataHolidayCalendarCreate = (SFODataHolidayCalendarCreate) o;
    return Objects.equals(this.country, sfODataHolidayCalendarCreate.country) &&
        Objects.equals(this.createdBy, sfODataHolidayCalendarCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataHolidayCalendarCreate.createdDateTime) &&
        Objects.equals(this.entityUUID, sfODataHolidayCalendarCreate.entityUUID) &&
        Objects.equals(this.externalCode, sfODataHolidayCalendarCreate.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataHolidayCalendarCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataHolidayCalendarCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataHolidayCalendarCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.nameDaDK, sfODataHolidayCalendarCreate.nameDaDK) &&
        Objects.equals(this.nameDeCH, sfODataHolidayCalendarCreate.nameDeCH) &&
        Objects.equals(this.nameDeDE, sfODataHolidayCalendarCreate.nameDeDE) &&
        Objects.equals(this.nameDefaultValue, sfODataHolidayCalendarCreate.nameDefaultValue) &&
        Objects.equals(this.nameEnDEBUG, sfODataHolidayCalendarCreate.nameEnDEBUG) &&
        Objects.equals(this.nameEnGB, sfODataHolidayCalendarCreate.nameEnGB) &&
        Objects.equals(this.nameEsES, sfODataHolidayCalendarCreate.nameEsES) &&
        Objects.equals(this.nameFiFI, sfODataHolidayCalendarCreate.nameFiFI) &&
        Objects.equals(this.nameFrFR, sfODataHolidayCalendarCreate.nameFrFR) &&
        Objects.equals(this.nameHuHU, sfODataHolidayCalendarCreate.nameHuHU) &&
        Objects.equals(this.nameItIT, sfODataHolidayCalendarCreate.nameItIT) &&
        Objects.equals(this.nameLocalized, sfODataHolidayCalendarCreate.nameLocalized) &&
        Objects.equals(this.nameNbNO, sfODataHolidayCalendarCreate.nameNbNO) &&
        Objects.equals(this.nameNlNL, sfODataHolidayCalendarCreate.nameNlNL) &&
        Objects.equals(this.namePlPL, sfODataHolidayCalendarCreate.namePlPL) &&
        Objects.equals(this.namePtPT, sfODataHolidayCalendarCreate.namePtPT) &&
        Objects.equals(this.nameSvSE, sfODataHolidayCalendarCreate.nameSvSE) &&
        Objects.equals(this.oldName, sfODataHolidayCalendarCreate.oldName) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataHolidayCalendarCreate.mdfSystemRecordStatusNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, createdBy, createdDateTime, entityUUID, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, nameDaDK, nameDeCH, nameDeDE, nameDefaultValue, nameEnDEBUG, nameEnGB, nameEsES, nameFiFI, nameFrFR, nameHuHU, nameItIT, nameLocalized, nameNbNO, nameNlNL, namePlPL, namePtPT, nameSvSE, oldName, mdfSystemRecordStatusNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataHolidayCalendarCreate {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    entityUUID: ").append(toIndentedString(entityUUID)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    nameDaDK: ").append(toIndentedString(nameDaDK)).append("\n");
    sb.append("    nameDeCH: ").append(toIndentedString(nameDeCH)).append("\n");
    sb.append("    nameDeDE: ").append(toIndentedString(nameDeDE)).append("\n");
    sb.append("    nameDefaultValue: ").append(toIndentedString(nameDefaultValue)).append("\n");
    sb.append("    nameEnDEBUG: ").append(toIndentedString(nameEnDEBUG)).append("\n");
    sb.append("    nameEnGB: ").append(toIndentedString(nameEnGB)).append("\n");
    sb.append("    nameEsES: ").append(toIndentedString(nameEsES)).append("\n");
    sb.append("    nameFiFI: ").append(toIndentedString(nameFiFI)).append("\n");
    sb.append("    nameFrFR: ").append(toIndentedString(nameFrFR)).append("\n");
    sb.append("    nameHuHU: ").append(toIndentedString(nameHuHU)).append("\n");
    sb.append("    nameItIT: ").append(toIndentedString(nameItIT)).append("\n");
    sb.append("    nameLocalized: ").append(toIndentedString(nameLocalized)).append("\n");
    sb.append("    nameNbNO: ").append(toIndentedString(nameNbNO)).append("\n");
    sb.append("    nameNlNL: ").append(toIndentedString(nameNlNL)).append("\n");
    sb.append("    namePlPL: ").append(toIndentedString(namePlPL)).append("\n");
    sb.append("    namePtPT: ").append(toIndentedString(namePtPT)).append("\n");
    sb.append("    nameSvSE: ").append(toIndentedString(nameSvSE)).append("\n");
    sb.append("    oldName: ").append(toIndentedString(oldName)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
