/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataEmpPayCompRecurringUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataEmpPayCompRecurringUpdate {
  @JsonProperty("basePaycomponent")
  private String basePaycomponent = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("currencyCode")
  private String currencyCode = null;

  @JsonProperty("deferralpercentage")
  private Double deferralpercentage = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("frequency")
  private String frequency = null;

  @JsonProperty("isTarget")
  private Boolean isTarget = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("notes")
  private String notes = null;

  @JsonProperty("operation")
  private String operation = null;

  @JsonProperty("paycompvalue")
  private Double paycompvalue = null;

  @JsonProperty("sentToPayroll")
  private OffsetDateTime sentToPayroll = null;

  @JsonProperty("taxTreatment")
  private String taxTreatment = null;

  public SFODataEmpPayCompRecurringUpdate basePaycomponent(String basePaycomponent) {
    this.basePaycomponent = basePaycomponent;
    return this;
  }

   /**
   * Get basePaycomponent
   * @return basePaycomponent
  **/
  public String getBasePaycomponent() {
    return basePaycomponent;
  }

  public void setBasePaycomponent(String basePaycomponent) {
    this.basePaycomponent = basePaycomponent;
  }

  public SFODataEmpPayCompRecurringUpdate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataEmpPayCompRecurringUpdate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataEmpPayCompRecurringUpdate createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataEmpPayCompRecurringUpdate currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public SFODataEmpPayCompRecurringUpdate deferralpercentage(Double deferralpercentage) {
    this.deferralpercentage = deferralpercentage;
    return this;
  }

   /**
   * Get deferralpercentage
   * @return deferralpercentage
  **/
  public Double getDeferralpercentage() {
    return deferralpercentage;
  }

  public void setDeferralpercentage(Double deferralpercentage) {
    this.deferralpercentage = deferralpercentage;
  }

  public SFODataEmpPayCompRecurringUpdate endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataEmpPayCompRecurringUpdate frequency(String frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  public String getFrequency() {
    return frequency;
  }

  public void setFrequency(String frequency) {
    this.frequency = frequency;
  }

  public SFODataEmpPayCompRecurringUpdate isTarget(Boolean isTarget) {
    this.isTarget = isTarget;
    return this;
  }

   /**
   * Get isTarget
   * @return isTarget
  **/
  public Boolean isIsTarget() {
    return isTarget;
  }

  public void setIsTarget(Boolean isTarget) {
    this.isTarget = isTarget;
  }

  public SFODataEmpPayCompRecurringUpdate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataEmpPayCompRecurringUpdate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataEmpPayCompRecurringUpdate lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataEmpPayCompRecurringUpdate notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public SFODataEmpPayCompRecurringUpdate operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public SFODataEmpPayCompRecurringUpdate paycompvalue(Double paycompvalue) {
    this.paycompvalue = paycompvalue;
    return this;
  }

   /**
   * Get paycompvalue
   * @return paycompvalue
  **/
  public Double getPaycompvalue() {
    return paycompvalue;
  }

  public void setPaycompvalue(Double paycompvalue) {
    this.paycompvalue = paycompvalue;
  }

  public SFODataEmpPayCompRecurringUpdate sentToPayroll(OffsetDateTime sentToPayroll) {
    this.sentToPayroll = sentToPayroll;
    return this;
  }

   /**
   * Get sentToPayroll
   * @return sentToPayroll
  **/
  public OffsetDateTime getSentToPayroll() {
    return sentToPayroll;
  }

  public void setSentToPayroll(OffsetDateTime sentToPayroll) {
    this.sentToPayroll = sentToPayroll;
  }

  public SFODataEmpPayCompRecurringUpdate taxTreatment(String taxTreatment) {
    this.taxTreatment = taxTreatment;
    return this;
  }

   /**
   * Get taxTreatment
   * @return taxTreatment
  **/
  public String getTaxTreatment() {
    return taxTreatment;
  }

  public void setTaxTreatment(String taxTreatment) {
    this.taxTreatment = taxTreatment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataEmpPayCompRecurringUpdate sfODataEmpPayCompRecurringUpdate = (SFODataEmpPayCompRecurringUpdate) o;
    return Objects.equals(this.basePaycomponent, sfODataEmpPayCompRecurringUpdate.basePaycomponent) &&
        Objects.equals(this.createdBy, sfODataEmpPayCompRecurringUpdate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataEmpPayCompRecurringUpdate.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataEmpPayCompRecurringUpdate.createdOn) &&
        Objects.equals(this.currencyCode, sfODataEmpPayCompRecurringUpdate.currencyCode) &&
        Objects.equals(this.deferralpercentage, sfODataEmpPayCompRecurringUpdate.deferralpercentage) &&
        Objects.equals(this.endDate, sfODataEmpPayCompRecurringUpdate.endDate) &&
        Objects.equals(this.frequency, sfODataEmpPayCompRecurringUpdate.frequency) &&
        Objects.equals(this.isTarget, sfODataEmpPayCompRecurringUpdate.isTarget) &&
        Objects.equals(this.lastModifiedBy, sfODataEmpPayCompRecurringUpdate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataEmpPayCompRecurringUpdate.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataEmpPayCompRecurringUpdate.lastModifiedOn) &&
        Objects.equals(this.notes, sfODataEmpPayCompRecurringUpdate.notes) &&
        Objects.equals(this.operation, sfODataEmpPayCompRecurringUpdate.operation) &&
        Objects.equals(this.paycompvalue, sfODataEmpPayCompRecurringUpdate.paycompvalue) &&
        Objects.equals(this.sentToPayroll, sfODataEmpPayCompRecurringUpdate.sentToPayroll) &&
        Objects.equals(this.taxTreatment, sfODataEmpPayCompRecurringUpdate.taxTreatment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basePaycomponent, createdBy, createdDateTime, createdOn, currencyCode, deferralpercentage, endDate, frequency, isTarget, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, notes, operation, paycompvalue, sentToPayroll, taxTreatment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataEmpPayCompRecurringUpdate {\n");
    
    sb.append("    basePaycomponent: ").append(toIndentedString(basePaycomponent)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    deferralpercentage: ").append(toIndentedString(deferralpercentage)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    isTarget: ").append(toIndentedString(isTarget)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    paycompvalue: ").append(toIndentedString(paycompvalue)).append("\n");
    sb.append("    sentToPayroll: ").append(toIndentedString(sentToPayroll)).append("\n");
    sb.append("    taxTreatment: ").append(toIndentedString(taxTreatment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
