/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataCountryUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataCountryUpdate {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("effectiveEndDate")
  private OffsetDateTime effectiveEndDate = null;

  @JsonProperty("externalName_da_DK")
  private String externalNameDaDK = null;

  @JsonProperty("externalName_de_CH")
  private String externalNameDeCH = null;

  @JsonProperty("externalName_de_DE")
  private String externalNameDeDE = null;

  @JsonProperty("externalName_defaultValue")
  private String externalNameDefaultValue = null;

  @JsonProperty("externalName_en_DEBUG")
  private String externalNameEnDEBUG = null;

  @JsonProperty("externalName_en_GB")
  private String externalNameEnGB = null;

  @JsonProperty("externalName_es_ES")
  private String externalNameEsES = null;

  @JsonProperty("externalName_fi_FI")
  private String externalNameFiFI = null;

  @JsonProperty("externalName_fr_FR")
  private String externalNameFrFR = null;

  @JsonProperty("externalName_hu_HU")
  private String externalNameHuHU = null;

  @JsonProperty("externalName_it_IT")
  private String externalNameItIT = null;

  @JsonProperty("externalName_localized")
  private String externalNameLocalized = null;

  @JsonProperty("externalName_nb_NO")
  private String externalNameNbNO = null;

  @JsonProperty("externalName_nl_NL")
  private String externalNameNlNL = null;

  @JsonProperty("externalName_pl_PL")
  private String externalNamePlPL = null;

  @JsonProperty("externalName_pt_PT")
  private String externalNamePtPT = null;

  @JsonProperty("externalName_sv_SE")
  private String externalNameSvSE = null;

  @JsonProperty("isDRMEnabled")
  private Boolean isDRMEnabled = null;

  @JsonProperty("isSetByMigrate")
  private Boolean isSetByMigrate = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("numericCountryCode")
  private AnyOfSFODataCountryUpdateNumericCountryCode numericCountryCode = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("territoryId")
  private AnyOfSFODataCountryUpdateTerritoryId territoryId = null;

  @JsonProperty("twoCharCountryCode")
  private String twoCharCountryCode = null;

  public SFODataCountryUpdate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataCountryUpdate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataCountryUpdate currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public SFODataCountryUpdate effectiveEndDate(OffsetDateTime effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
    return this;
  }

   /**
   * Get effectiveEndDate
   * @return effectiveEndDate
  **/
  public OffsetDateTime getEffectiveEndDate() {
    return effectiveEndDate;
  }

  public void setEffectiveEndDate(OffsetDateTime effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
  }

  public SFODataCountryUpdate externalNameDaDK(String externalNameDaDK) {
    this.externalNameDaDK = externalNameDaDK;
    return this;
  }

   /**
   * Get externalNameDaDK
   * @return externalNameDaDK
  **/
  public String getExternalNameDaDK() {
    return externalNameDaDK;
  }

  public void setExternalNameDaDK(String externalNameDaDK) {
    this.externalNameDaDK = externalNameDaDK;
  }

  public SFODataCountryUpdate externalNameDeCH(String externalNameDeCH) {
    this.externalNameDeCH = externalNameDeCH;
    return this;
  }

   /**
   * Get externalNameDeCH
   * @return externalNameDeCH
  **/
  public String getExternalNameDeCH() {
    return externalNameDeCH;
  }

  public void setExternalNameDeCH(String externalNameDeCH) {
    this.externalNameDeCH = externalNameDeCH;
  }

  public SFODataCountryUpdate externalNameDeDE(String externalNameDeDE) {
    this.externalNameDeDE = externalNameDeDE;
    return this;
  }

   /**
   * Get externalNameDeDE
   * @return externalNameDeDE
  **/
  public String getExternalNameDeDE() {
    return externalNameDeDE;
  }

  public void setExternalNameDeDE(String externalNameDeDE) {
    this.externalNameDeDE = externalNameDeDE;
  }

  public SFODataCountryUpdate externalNameDefaultValue(String externalNameDefaultValue) {
    this.externalNameDefaultValue = externalNameDefaultValue;
    return this;
  }

   /**
   * Get externalNameDefaultValue
   * @return externalNameDefaultValue
  **/
  public String getExternalNameDefaultValue() {
    return externalNameDefaultValue;
  }

  public void setExternalNameDefaultValue(String externalNameDefaultValue) {
    this.externalNameDefaultValue = externalNameDefaultValue;
  }

  public SFODataCountryUpdate externalNameEnDEBUG(String externalNameEnDEBUG) {
    this.externalNameEnDEBUG = externalNameEnDEBUG;
    return this;
  }

   /**
   * Get externalNameEnDEBUG
   * @return externalNameEnDEBUG
  **/
  public String getExternalNameEnDEBUG() {
    return externalNameEnDEBUG;
  }

  public void setExternalNameEnDEBUG(String externalNameEnDEBUG) {
    this.externalNameEnDEBUG = externalNameEnDEBUG;
  }

  public SFODataCountryUpdate externalNameEnGB(String externalNameEnGB) {
    this.externalNameEnGB = externalNameEnGB;
    return this;
  }

   /**
   * Get externalNameEnGB
   * @return externalNameEnGB
  **/
  public String getExternalNameEnGB() {
    return externalNameEnGB;
  }

  public void setExternalNameEnGB(String externalNameEnGB) {
    this.externalNameEnGB = externalNameEnGB;
  }

  public SFODataCountryUpdate externalNameEsES(String externalNameEsES) {
    this.externalNameEsES = externalNameEsES;
    return this;
  }

   /**
   * Get externalNameEsES
   * @return externalNameEsES
  **/
  public String getExternalNameEsES() {
    return externalNameEsES;
  }

  public void setExternalNameEsES(String externalNameEsES) {
    this.externalNameEsES = externalNameEsES;
  }

  public SFODataCountryUpdate externalNameFiFI(String externalNameFiFI) {
    this.externalNameFiFI = externalNameFiFI;
    return this;
  }

   /**
   * Get externalNameFiFI
   * @return externalNameFiFI
  **/
  public String getExternalNameFiFI() {
    return externalNameFiFI;
  }

  public void setExternalNameFiFI(String externalNameFiFI) {
    this.externalNameFiFI = externalNameFiFI;
  }

  public SFODataCountryUpdate externalNameFrFR(String externalNameFrFR) {
    this.externalNameFrFR = externalNameFrFR;
    return this;
  }

   /**
   * Get externalNameFrFR
   * @return externalNameFrFR
  **/
  public String getExternalNameFrFR() {
    return externalNameFrFR;
  }

  public void setExternalNameFrFR(String externalNameFrFR) {
    this.externalNameFrFR = externalNameFrFR;
  }

  public SFODataCountryUpdate externalNameHuHU(String externalNameHuHU) {
    this.externalNameHuHU = externalNameHuHU;
    return this;
  }

   /**
   * Get externalNameHuHU
   * @return externalNameHuHU
  **/
  public String getExternalNameHuHU() {
    return externalNameHuHU;
  }

  public void setExternalNameHuHU(String externalNameHuHU) {
    this.externalNameHuHU = externalNameHuHU;
  }

  public SFODataCountryUpdate externalNameItIT(String externalNameItIT) {
    this.externalNameItIT = externalNameItIT;
    return this;
  }

   /**
   * Get externalNameItIT
   * @return externalNameItIT
  **/
  public String getExternalNameItIT() {
    return externalNameItIT;
  }

  public void setExternalNameItIT(String externalNameItIT) {
    this.externalNameItIT = externalNameItIT;
  }

  public SFODataCountryUpdate externalNameLocalized(String externalNameLocalized) {
    this.externalNameLocalized = externalNameLocalized;
    return this;
  }

   /**
   * Get externalNameLocalized
   * @return externalNameLocalized
  **/
  public String getExternalNameLocalized() {
    return externalNameLocalized;
  }

  public void setExternalNameLocalized(String externalNameLocalized) {
    this.externalNameLocalized = externalNameLocalized;
  }

  public SFODataCountryUpdate externalNameNbNO(String externalNameNbNO) {
    this.externalNameNbNO = externalNameNbNO;
    return this;
  }

   /**
   * Get externalNameNbNO
   * @return externalNameNbNO
  **/
  public String getExternalNameNbNO() {
    return externalNameNbNO;
  }

  public void setExternalNameNbNO(String externalNameNbNO) {
    this.externalNameNbNO = externalNameNbNO;
  }

  public SFODataCountryUpdate externalNameNlNL(String externalNameNlNL) {
    this.externalNameNlNL = externalNameNlNL;
    return this;
  }

   /**
   * Get externalNameNlNL
   * @return externalNameNlNL
  **/
  public String getExternalNameNlNL() {
    return externalNameNlNL;
  }

  public void setExternalNameNlNL(String externalNameNlNL) {
    this.externalNameNlNL = externalNameNlNL;
  }

  public SFODataCountryUpdate externalNamePlPL(String externalNamePlPL) {
    this.externalNamePlPL = externalNamePlPL;
    return this;
  }

   /**
   * Get externalNamePlPL
   * @return externalNamePlPL
  **/
  public String getExternalNamePlPL() {
    return externalNamePlPL;
  }

  public void setExternalNamePlPL(String externalNamePlPL) {
    this.externalNamePlPL = externalNamePlPL;
  }

  public SFODataCountryUpdate externalNamePtPT(String externalNamePtPT) {
    this.externalNamePtPT = externalNamePtPT;
    return this;
  }

   /**
   * Get externalNamePtPT
   * @return externalNamePtPT
  **/
  public String getExternalNamePtPT() {
    return externalNamePtPT;
  }

  public void setExternalNamePtPT(String externalNamePtPT) {
    this.externalNamePtPT = externalNamePtPT;
  }

  public SFODataCountryUpdate externalNameSvSE(String externalNameSvSE) {
    this.externalNameSvSE = externalNameSvSE;
    return this;
  }

   /**
   * Get externalNameSvSE
   * @return externalNameSvSE
  **/
  public String getExternalNameSvSE() {
    return externalNameSvSE;
  }

  public void setExternalNameSvSE(String externalNameSvSE) {
    this.externalNameSvSE = externalNameSvSE;
  }

  public SFODataCountryUpdate isDRMEnabled(Boolean isDRMEnabled) {
    this.isDRMEnabled = isDRMEnabled;
    return this;
  }

   /**
   * Get isDRMEnabled
   * @return isDRMEnabled
  **/
  public Boolean isIsDRMEnabled() {
    return isDRMEnabled;
  }

  public void setIsDRMEnabled(Boolean isDRMEnabled) {
    this.isDRMEnabled = isDRMEnabled;
  }

  public SFODataCountryUpdate isSetByMigrate(Boolean isSetByMigrate) {
    this.isSetByMigrate = isSetByMigrate;
    return this;
  }

   /**
   * Get isSetByMigrate
   * @return isSetByMigrate
  **/
  public Boolean isIsSetByMigrate() {
    return isSetByMigrate;
  }

  public void setIsSetByMigrate(Boolean isSetByMigrate) {
    this.isSetByMigrate = isSetByMigrate;
  }

  public SFODataCountryUpdate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataCountryUpdate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataCountryUpdate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataCountryUpdate numericCountryCode(AnyOfSFODataCountryUpdateNumericCountryCode numericCountryCode) {
    this.numericCountryCode = numericCountryCode;
    return this;
  }

   /**
   * Get numericCountryCode
   * @return numericCountryCode
  **/
  public AnyOfSFODataCountryUpdateNumericCountryCode getNumericCountryCode() {
    return numericCountryCode;
  }

  public void setNumericCountryCode(AnyOfSFODataCountryUpdateNumericCountryCode numericCountryCode) {
    this.numericCountryCode = numericCountryCode;
  }

  public SFODataCountryUpdate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SFODataCountryUpdate territoryId(AnyOfSFODataCountryUpdateTerritoryId territoryId) {
    this.territoryId = territoryId;
    return this;
  }

   /**
   * Get territoryId
   * @return territoryId
  **/
  public AnyOfSFODataCountryUpdateTerritoryId getTerritoryId() {
    return territoryId;
  }

  public void setTerritoryId(AnyOfSFODataCountryUpdateTerritoryId territoryId) {
    this.territoryId = territoryId;
  }

  public SFODataCountryUpdate twoCharCountryCode(String twoCharCountryCode) {
    this.twoCharCountryCode = twoCharCountryCode;
    return this;
  }

   /**
   * Get twoCharCountryCode
   * @return twoCharCountryCode
  **/
  public String getTwoCharCountryCode() {
    return twoCharCountryCode;
  }

  public void setTwoCharCountryCode(String twoCharCountryCode) {
    this.twoCharCountryCode = twoCharCountryCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataCountryUpdate sfODataCountryUpdate = (SFODataCountryUpdate) o;
    return Objects.equals(this.createdBy, sfODataCountryUpdate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataCountryUpdate.createdDateTime) &&
        Objects.equals(this.currency, sfODataCountryUpdate.currency) &&
        Objects.equals(this.effectiveEndDate, sfODataCountryUpdate.effectiveEndDate) &&
        Objects.equals(this.externalNameDaDK, sfODataCountryUpdate.externalNameDaDK) &&
        Objects.equals(this.externalNameDeCH, sfODataCountryUpdate.externalNameDeCH) &&
        Objects.equals(this.externalNameDeDE, sfODataCountryUpdate.externalNameDeDE) &&
        Objects.equals(this.externalNameDefaultValue, sfODataCountryUpdate.externalNameDefaultValue) &&
        Objects.equals(this.externalNameEnDEBUG, sfODataCountryUpdate.externalNameEnDEBUG) &&
        Objects.equals(this.externalNameEnGB, sfODataCountryUpdate.externalNameEnGB) &&
        Objects.equals(this.externalNameEsES, sfODataCountryUpdate.externalNameEsES) &&
        Objects.equals(this.externalNameFiFI, sfODataCountryUpdate.externalNameFiFI) &&
        Objects.equals(this.externalNameFrFR, sfODataCountryUpdate.externalNameFrFR) &&
        Objects.equals(this.externalNameHuHU, sfODataCountryUpdate.externalNameHuHU) &&
        Objects.equals(this.externalNameItIT, sfODataCountryUpdate.externalNameItIT) &&
        Objects.equals(this.externalNameLocalized, sfODataCountryUpdate.externalNameLocalized) &&
        Objects.equals(this.externalNameNbNO, sfODataCountryUpdate.externalNameNbNO) &&
        Objects.equals(this.externalNameNlNL, sfODataCountryUpdate.externalNameNlNL) &&
        Objects.equals(this.externalNamePlPL, sfODataCountryUpdate.externalNamePlPL) &&
        Objects.equals(this.externalNamePtPT, sfODataCountryUpdate.externalNamePtPT) &&
        Objects.equals(this.externalNameSvSE, sfODataCountryUpdate.externalNameSvSE) &&
        Objects.equals(this.isDRMEnabled, sfODataCountryUpdate.isDRMEnabled) &&
        Objects.equals(this.isSetByMigrate, sfODataCountryUpdate.isSetByMigrate) &&
        Objects.equals(this.lastModifiedBy, sfODataCountryUpdate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataCountryUpdate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataCountryUpdate.mdfSystemRecordStatus) &&
        Objects.equals(this.numericCountryCode, sfODataCountryUpdate.numericCountryCode) &&
        Objects.equals(this.status, sfODataCountryUpdate.status) &&
        Objects.equals(this.territoryId, sfODataCountryUpdate.territoryId) &&
        Objects.equals(this.twoCharCountryCode, sfODataCountryUpdate.twoCharCountryCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDateTime, currency, effectiveEndDate, externalNameDaDK, externalNameDeCH, externalNameDeDE, externalNameDefaultValue, externalNameEnDEBUG, externalNameEnGB, externalNameEsES, externalNameFiFI, externalNameFrFR, externalNameHuHU, externalNameItIT, externalNameLocalized, externalNameNbNO, externalNameNlNL, externalNamePlPL, externalNamePtPT, externalNameSvSE, isDRMEnabled, isSetByMigrate, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, numericCountryCode, status, territoryId, twoCharCountryCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataCountryUpdate {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    effectiveEndDate: ").append(toIndentedString(effectiveEndDate)).append("\n");
    sb.append("    externalNameDaDK: ").append(toIndentedString(externalNameDaDK)).append("\n");
    sb.append("    externalNameDeCH: ").append(toIndentedString(externalNameDeCH)).append("\n");
    sb.append("    externalNameDeDE: ").append(toIndentedString(externalNameDeDE)).append("\n");
    sb.append("    externalNameDefaultValue: ").append(toIndentedString(externalNameDefaultValue)).append("\n");
    sb.append("    externalNameEnDEBUG: ").append(toIndentedString(externalNameEnDEBUG)).append("\n");
    sb.append("    externalNameEnGB: ").append(toIndentedString(externalNameEnGB)).append("\n");
    sb.append("    externalNameEsES: ").append(toIndentedString(externalNameEsES)).append("\n");
    sb.append("    externalNameFiFI: ").append(toIndentedString(externalNameFiFI)).append("\n");
    sb.append("    externalNameFrFR: ").append(toIndentedString(externalNameFrFR)).append("\n");
    sb.append("    externalNameHuHU: ").append(toIndentedString(externalNameHuHU)).append("\n");
    sb.append("    externalNameItIT: ").append(toIndentedString(externalNameItIT)).append("\n");
    sb.append("    externalNameLocalized: ").append(toIndentedString(externalNameLocalized)).append("\n");
    sb.append("    externalNameNbNO: ").append(toIndentedString(externalNameNbNO)).append("\n");
    sb.append("    externalNameNlNL: ").append(toIndentedString(externalNameNlNL)).append("\n");
    sb.append("    externalNamePlPL: ").append(toIndentedString(externalNamePlPL)).append("\n");
    sb.append("    externalNamePtPT: ").append(toIndentedString(externalNamePtPT)).append("\n");
    sb.append("    externalNameSvSE: ").append(toIndentedString(externalNameSvSE)).append("\n");
    sb.append("    isDRMEnabled: ").append(toIndentedString(isDRMEnabled)).append("\n");
    sb.append("    isSetByMigrate: ").append(toIndentedString(isSetByMigrate)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    numericCountryCode: ").append(toIndentedString(numericCountryCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    territoryId: ").append(toIndentedString(territoryId)).append("\n");
    sb.append("    twoCharCountryCode: ").append(toIndentedString(twoCharCountryCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
