/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataRBPRuleCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataRBPRuleCreate {
  @JsonProperty("accessGroupLevel")
  private Integer accessGroupLevel = null;

  @JsonProperty("accessUserType")
  private String accessUserType = null;

  @JsonProperty("excludeSelf")
  private Boolean excludeSelf = null;

  @JsonProperty("includeSelf")
  private Boolean includeSelf = null;

  @JsonProperty("myFilter")
  private String myFilter = null;

  @JsonProperty("relationRole")
  private String relationRole = null;

  @JsonProperty("ruleId")
  private AnyOfSFODataRBPRuleCreateRuleId ruleId = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("targetGroupLevel")
  private Integer targetGroupLevel = null;

  @JsonProperty("targetUserType")
  private String targetUserType = null;

  @JsonProperty("roles@odata.bind")
  private String rolesAtOdataBind = null;

  public SFODataRBPRuleCreate accessGroupLevel(Integer accessGroupLevel) {
    this.accessGroupLevel = accessGroupLevel;
    return this;
  }

   /**
   * Get accessGroupLevel
   * @return accessGroupLevel
  **/
  public Integer getAccessGroupLevel() {
    return accessGroupLevel;
  }

  public void setAccessGroupLevel(Integer accessGroupLevel) {
    this.accessGroupLevel = accessGroupLevel;
  }

  public SFODataRBPRuleCreate accessUserType(String accessUserType) {
    this.accessUserType = accessUserType;
    return this;
  }

   /**
   * Get accessUserType
   * @return accessUserType
  **/
  public String getAccessUserType() {
    return accessUserType;
  }

  public void setAccessUserType(String accessUserType) {
    this.accessUserType = accessUserType;
  }

  public SFODataRBPRuleCreate excludeSelf(Boolean excludeSelf) {
    this.excludeSelf = excludeSelf;
    return this;
  }

   /**
   * Get excludeSelf
   * @return excludeSelf
  **/
  public Boolean isExcludeSelf() {
    return excludeSelf;
  }

  public void setExcludeSelf(Boolean excludeSelf) {
    this.excludeSelf = excludeSelf;
  }

  public SFODataRBPRuleCreate includeSelf(Boolean includeSelf) {
    this.includeSelf = includeSelf;
    return this;
  }

   /**
   * Get includeSelf
   * @return includeSelf
  **/
  public Boolean isIncludeSelf() {
    return includeSelf;
  }

  public void setIncludeSelf(Boolean includeSelf) {
    this.includeSelf = includeSelf;
  }

  public SFODataRBPRuleCreate myFilter(String myFilter) {
    this.myFilter = myFilter;
    return this;
  }

   /**
   * Get myFilter
   * @return myFilter
  **/
  public String getMyFilter() {
    return myFilter;
  }

  public void setMyFilter(String myFilter) {
    this.myFilter = myFilter;
  }

  public SFODataRBPRuleCreate relationRole(String relationRole) {
    this.relationRole = relationRole;
    return this;
  }

   /**
   * Get relationRole
   * @return relationRole
  **/
  public String getRelationRole() {
    return relationRole;
  }

  public void setRelationRole(String relationRole) {
    this.relationRole = relationRole;
  }

  public SFODataRBPRuleCreate ruleId(AnyOfSFODataRBPRuleCreateRuleId ruleId) {
    this.ruleId = ruleId;
    return this;
  }

   /**
   * Get ruleId
   * @return ruleId
  **/
  public AnyOfSFODataRBPRuleCreateRuleId getRuleId() {
    return ruleId;
  }

  public void setRuleId(AnyOfSFODataRBPRuleCreateRuleId ruleId) {
    this.ruleId = ruleId;
  }

  public SFODataRBPRuleCreate status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public SFODataRBPRuleCreate targetGroupLevel(Integer targetGroupLevel) {
    this.targetGroupLevel = targetGroupLevel;
    return this;
  }

   /**
   * Get targetGroupLevel
   * @return targetGroupLevel
  **/
  public Integer getTargetGroupLevel() {
    return targetGroupLevel;
  }

  public void setTargetGroupLevel(Integer targetGroupLevel) {
    this.targetGroupLevel = targetGroupLevel;
  }

  public SFODataRBPRuleCreate targetUserType(String targetUserType) {
    this.targetUserType = targetUserType;
    return this;
  }

   /**
   * Get targetUserType
   * @return targetUserType
  **/
  public String getTargetUserType() {
    return targetUserType;
  }

  public void setTargetUserType(String targetUserType) {
    this.targetUserType = targetUserType;
  }

  public SFODataRBPRuleCreate rolesAtOdataBind(String rolesAtOdataBind) {
    this.rolesAtOdataBind = rolesAtOdataBind;
    return this;
  }

   /**
   * Get rolesAtOdataBind
   * @return rolesAtOdataBind
  **/
  public String getRolesAtOdataBind() {
    return rolesAtOdataBind;
  }

  public void setRolesAtOdataBind(String rolesAtOdataBind) {
    this.rolesAtOdataBind = rolesAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataRBPRuleCreate sfODataRBPRuleCreate = (SFODataRBPRuleCreate) o;
    return Objects.equals(this.accessGroupLevel, sfODataRBPRuleCreate.accessGroupLevel) &&
        Objects.equals(this.accessUserType, sfODataRBPRuleCreate.accessUserType) &&
        Objects.equals(this.excludeSelf, sfODataRBPRuleCreate.excludeSelf) &&
        Objects.equals(this.includeSelf, sfODataRBPRuleCreate.includeSelf) &&
        Objects.equals(this.myFilter, sfODataRBPRuleCreate.myFilter) &&
        Objects.equals(this.relationRole, sfODataRBPRuleCreate.relationRole) &&
        Objects.equals(this.ruleId, sfODataRBPRuleCreate.ruleId) &&
        Objects.equals(this.status, sfODataRBPRuleCreate.status) &&
        Objects.equals(this.targetGroupLevel, sfODataRBPRuleCreate.targetGroupLevel) &&
        Objects.equals(this.targetUserType, sfODataRBPRuleCreate.targetUserType) &&
        Objects.equals(this.rolesAtOdataBind, sfODataRBPRuleCreate.rolesAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessGroupLevel, accessUserType, excludeSelf, includeSelf, myFilter, relationRole, ruleId, status, targetGroupLevel, targetUserType, rolesAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataRBPRuleCreate {\n");
    
    sb.append("    accessGroupLevel: ").append(toIndentedString(accessGroupLevel)).append("\n");
    sb.append("    accessUserType: ").append(toIndentedString(accessUserType)).append("\n");
    sb.append("    excludeSelf: ").append(toIndentedString(excludeSelf)).append("\n");
    sb.append("    includeSelf: ").append(toIndentedString(includeSelf)).append("\n");
    sb.append("    myFilter: ").append(toIndentedString(myFilter)).append("\n");
    sb.append("    relationRole: ").append(toIndentedString(relationRole)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    targetGroupLevel: ").append(toIndentedString(targetGroupLevel)).append("\n");
    sb.append("    targetUserType: ").append(toIndentedString(targetUserType)).append("\n");
    sb.append("    rolesAtOdataBind: ").append(toIndentedString(rolesAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
