/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataEPCustomBackgroundPortletUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataEPCustomBackgroundPortletUpdate {
  @JsonProperty("backgroundPropertyLists")
  private AllOfSFODataEPCustomBackgroundPortletUpdateBackgroundPropertyLists backgroundPropertyLists = null;

  @JsonProperty("editable")
  private Boolean editable = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("viewable")
  private Boolean viewable = null;

  public SFODataEPCustomBackgroundPortletUpdate backgroundPropertyLists(AllOfSFODataEPCustomBackgroundPortletUpdateBackgroundPropertyLists backgroundPropertyLists) {
    this.backgroundPropertyLists = backgroundPropertyLists;
    return this;
  }

   /**
   * Get backgroundPropertyLists
   * @return backgroundPropertyLists
  **/
  public AllOfSFODataEPCustomBackgroundPortletUpdateBackgroundPropertyLists getBackgroundPropertyLists() {
    return backgroundPropertyLists;
  }

  public void setBackgroundPropertyLists(AllOfSFODataEPCustomBackgroundPortletUpdateBackgroundPropertyLists backgroundPropertyLists) {
    this.backgroundPropertyLists = backgroundPropertyLists;
  }

  public SFODataEPCustomBackgroundPortletUpdate editable(Boolean editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Get editable
   * @return editable
  **/
  public Boolean isEditable() {
    return editable;
  }

  public void setEditable(Boolean editable) {
    this.editable = editable;
  }

  public SFODataEPCustomBackgroundPortletUpdate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataEPCustomBackgroundPortletUpdate viewable(Boolean viewable) {
    this.viewable = viewable;
    return this;
  }

   /**
   * Get viewable
   * @return viewable
  **/
  public Boolean isViewable() {
    return viewable;
  }

  public void setViewable(Boolean viewable) {
    this.viewable = viewable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataEPCustomBackgroundPortletUpdate sfODataEPCustomBackgroundPortletUpdate = (SFODataEPCustomBackgroundPortletUpdate) o;
    return Objects.equals(this.backgroundPropertyLists, sfODataEPCustomBackgroundPortletUpdate.backgroundPropertyLists) &&
        Objects.equals(this.editable, sfODataEPCustomBackgroundPortletUpdate.editable) &&
        Objects.equals(this.userId, sfODataEPCustomBackgroundPortletUpdate.userId) &&
        Objects.equals(this.viewable, sfODataEPCustomBackgroundPortletUpdate.viewable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundPropertyLists, editable, userId, viewable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataEPCustomBackgroundPortletUpdate {\n");
    
    sb.append("    backgroundPropertyLists: ").append(toIndentedString(backgroundPropertyLists)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    viewable: ").append(toIndentedString(viewable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
