/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataTimeTypeCANCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataTimeTypeCANCreate {
  @JsonProperty("TimeType_externalCode")
  private String timeTypeExternalCode = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("durationOfDisabilityPeriodOne")
  private AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodOne durationOfDisabilityPeriodOne = null;

  @JsonProperty("durationOfDisabilityPeriodThree")
  private AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodThree durationOfDisabilityPeriodThree = null;

  @JsonProperty("durationOfDisabilityPeriodTwo")
  private AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodTwo durationOfDisabilityPeriodTwo = null;

  @JsonProperty("entityUUID")
  private String entityUUID = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataTimeTypeCANCreateExternalCode externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("sicknessVariant")
  private String sicknessVariant = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  @JsonProperty("sicknessVariantNav@odata.bind")
  private String sicknessVariantNavAtOdataBind = null;

  public SFODataTimeTypeCANCreate timeTypeExternalCode(String timeTypeExternalCode) {
    this.timeTypeExternalCode = timeTypeExternalCode;
    return this;
  }

   /**
   * Get timeTypeExternalCode
   * @return timeTypeExternalCode
  **/
  public String getTimeTypeExternalCode() {
    return timeTypeExternalCode;
  }

  public void setTimeTypeExternalCode(String timeTypeExternalCode) {
    this.timeTypeExternalCode = timeTypeExternalCode;
  }

  public SFODataTimeTypeCANCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataTimeTypeCANCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataTimeTypeCANCreate durationOfDisabilityPeriodOne(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodOne durationOfDisabilityPeriodOne) {
    this.durationOfDisabilityPeriodOne = durationOfDisabilityPeriodOne;
    return this;
  }

   /**
   * Get durationOfDisabilityPeriodOne
   * @return durationOfDisabilityPeriodOne
  **/
  public AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodOne getDurationOfDisabilityPeriodOne() {
    return durationOfDisabilityPeriodOne;
  }

  public void setDurationOfDisabilityPeriodOne(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodOne durationOfDisabilityPeriodOne) {
    this.durationOfDisabilityPeriodOne = durationOfDisabilityPeriodOne;
  }

  public SFODataTimeTypeCANCreate durationOfDisabilityPeriodThree(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodThree durationOfDisabilityPeriodThree) {
    this.durationOfDisabilityPeriodThree = durationOfDisabilityPeriodThree;
    return this;
  }

   /**
   * Get durationOfDisabilityPeriodThree
   * @return durationOfDisabilityPeriodThree
  **/
  public AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodThree getDurationOfDisabilityPeriodThree() {
    return durationOfDisabilityPeriodThree;
  }

  public void setDurationOfDisabilityPeriodThree(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodThree durationOfDisabilityPeriodThree) {
    this.durationOfDisabilityPeriodThree = durationOfDisabilityPeriodThree;
  }

  public SFODataTimeTypeCANCreate durationOfDisabilityPeriodTwo(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodTwo durationOfDisabilityPeriodTwo) {
    this.durationOfDisabilityPeriodTwo = durationOfDisabilityPeriodTwo;
    return this;
  }

   /**
   * Get durationOfDisabilityPeriodTwo
   * @return durationOfDisabilityPeriodTwo
  **/
  public AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodTwo getDurationOfDisabilityPeriodTwo() {
    return durationOfDisabilityPeriodTwo;
  }

  public void setDurationOfDisabilityPeriodTwo(AnyOfSFODataTimeTypeCANCreateDurationOfDisabilityPeriodTwo durationOfDisabilityPeriodTwo) {
    this.durationOfDisabilityPeriodTwo = durationOfDisabilityPeriodTwo;
  }

  public SFODataTimeTypeCANCreate entityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
    return this;
  }

   /**
   * Get entityUUID
   * @return entityUUID
  **/
  public String getEntityUUID() {
    return entityUUID;
  }

  public void setEntityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
  }

  public SFODataTimeTypeCANCreate externalCode(AnyOfSFODataTimeTypeCANCreateExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataTimeTypeCANCreateExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataTimeTypeCANCreateExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataTimeTypeCANCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataTimeTypeCANCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataTimeTypeCANCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataTimeTypeCANCreate sicknessVariant(String sicknessVariant) {
    this.sicknessVariant = sicknessVariant;
    return this;
  }

   /**
   * Get sicknessVariant
   * @return sicknessVariant
  **/
  public String getSicknessVariant() {
    return sicknessVariant;
  }

  public void setSicknessVariant(String sicknessVariant) {
    this.sicknessVariant = sicknessVariant;
  }

  public SFODataTimeTypeCANCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }

  public SFODataTimeTypeCANCreate sicknessVariantNavAtOdataBind(String sicknessVariantNavAtOdataBind) {
    this.sicknessVariantNavAtOdataBind = sicknessVariantNavAtOdataBind;
    return this;
  }

   /**
   * Get sicknessVariantNavAtOdataBind
   * @return sicknessVariantNavAtOdataBind
  **/
  public String getSicknessVariantNavAtOdataBind() {
    return sicknessVariantNavAtOdataBind;
  }

  public void setSicknessVariantNavAtOdataBind(String sicknessVariantNavAtOdataBind) {
    this.sicknessVariantNavAtOdataBind = sicknessVariantNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataTimeTypeCANCreate sfODataTimeTypeCANCreate = (SFODataTimeTypeCANCreate) o;
    return Objects.equals(this.timeTypeExternalCode, sfODataTimeTypeCANCreate.timeTypeExternalCode) &&
        Objects.equals(this.createdBy, sfODataTimeTypeCANCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataTimeTypeCANCreate.createdDateTime) &&
        Objects.equals(this.durationOfDisabilityPeriodOne, sfODataTimeTypeCANCreate.durationOfDisabilityPeriodOne) &&
        Objects.equals(this.durationOfDisabilityPeriodThree, sfODataTimeTypeCANCreate.durationOfDisabilityPeriodThree) &&
        Objects.equals(this.durationOfDisabilityPeriodTwo, sfODataTimeTypeCANCreate.durationOfDisabilityPeriodTwo) &&
        Objects.equals(this.entityUUID, sfODataTimeTypeCANCreate.entityUUID) &&
        Objects.equals(this.externalCode, sfODataTimeTypeCANCreate.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataTimeTypeCANCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataTimeTypeCANCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataTimeTypeCANCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.sicknessVariant, sfODataTimeTypeCANCreate.sicknessVariant) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataTimeTypeCANCreate.mdfSystemRecordStatusNavAtOdataBind) &&
        Objects.equals(this.sicknessVariantNavAtOdataBind, sfODataTimeTypeCANCreate.sicknessVariantNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeTypeExternalCode, createdBy, createdDateTime, durationOfDisabilityPeriodOne, durationOfDisabilityPeriodThree, durationOfDisabilityPeriodTwo, entityUUID, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, sicknessVariant, mdfSystemRecordStatusNavAtOdataBind, sicknessVariantNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataTimeTypeCANCreate {\n");
    
    sb.append("    timeTypeExternalCode: ").append(toIndentedString(timeTypeExternalCode)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    durationOfDisabilityPeriodOne: ").append(toIndentedString(durationOfDisabilityPeriodOne)).append("\n");
    sb.append("    durationOfDisabilityPeriodThree: ").append(toIndentedString(durationOfDisabilityPeriodThree)).append("\n");
    sb.append("    durationOfDisabilityPeriodTwo: ").append(toIndentedString(durationOfDisabilityPeriodTwo)).append("\n");
    sb.append("    entityUUID: ").append(toIndentedString(entityUUID)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    sicknessVariant: ").append(toIndentedString(sicknessVariant)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("    sicknessVariantNavAtOdataBind: ").append(toIndentedString(sicknessVariantNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
