/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataBackgroundCertificatesCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataBackgroundCertificatesCreate {
  @JsonProperty("backgroundElementId")
  private AnyOfSFODataBackgroundCertificatesCreateBackgroundElementId backgroundElementId = null;

  @JsonProperty("bgOrderPos")
  private AnyOfSFODataBackgroundCertificatesCreateBgOrderPos bgOrderPos = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("institution")
  private String institution = null;

  @JsonProperty("lastModifiedDate")
  private OffsetDateTime lastModifiedDate = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("userIdNav@odata.bind")
  private String userIdNavAtOdataBind = null;

  public SFODataBackgroundCertificatesCreate backgroundElementId(AnyOfSFODataBackgroundCertificatesCreateBackgroundElementId backgroundElementId) {
    this.backgroundElementId = backgroundElementId;
    return this;
  }

   /**
   * Get backgroundElementId
   * @return backgroundElementId
  **/
  public AnyOfSFODataBackgroundCertificatesCreateBackgroundElementId getBackgroundElementId() {
    return backgroundElementId;
  }

  public void setBackgroundElementId(AnyOfSFODataBackgroundCertificatesCreateBackgroundElementId backgroundElementId) {
    this.backgroundElementId = backgroundElementId;
  }

  public SFODataBackgroundCertificatesCreate bgOrderPos(AnyOfSFODataBackgroundCertificatesCreateBgOrderPos bgOrderPos) {
    this.bgOrderPos = bgOrderPos;
    return this;
  }

   /**
   * Get bgOrderPos
   * @return bgOrderPos
  **/
  public AnyOfSFODataBackgroundCertificatesCreateBgOrderPos getBgOrderPos() {
    return bgOrderPos;
  }

  public void setBgOrderPos(AnyOfSFODataBackgroundCertificatesCreateBgOrderPos bgOrderPos) {
    this.bgOrderPos = bgOrderPos;
  }

  public SFODataBackgroundCertificatesCreate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SFODataBackgroundCertificatesCreate endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataBackgroundCertificatesCreate institution(String institution) {
    this.institution = institution;
    return this;
  }

   /**
   * Get institution
   * @return institution
  **/
  public String getInstitution() {
    return institution;
  }

  public void setInstitution(String institution) {
    this.institution = institution;
  }

  public SFODataBackgroundCertificatesCreate lastModifiedDate(OffsetDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  public OffsetDateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(OffsetDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public SFODataBackgroundCertificatesCreate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SFODataBackgroundCertificatesCreate startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SFODataBackgroundCertificatesCreate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataBackgroundCertificatesCreate userIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
    return this;
  }

   /**
   * Get userIdNavAtOdataBind
   * @return userIdNavAtOdataBind
  **/
  public String getUserIdNavAtOdataBind() {
    return userIdNavAtOdataBind;
  }

  public void setUserIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataBackgroundCertificatesCreate sfODataBackgroundCertificatesCreate = (SFODataBackgroundCertificatesCreate) o;
    return Objects.equals(this.backgroundElementId, sfODataBackgroundCertificatesCreate.backgroundElementId) &&
        Objects.equals(this.bgOrderPos, sfODataBackgroundCertificatesCreate.bgOrderPos) &&
        Objects.equals(this.description, sfODataBackgroundCertificatesCreate.description) &&
        Objects.equals(this.endDate, sfODataBackgroundCertificatesCreate.endDate) &&
        Objects.equals(this.institution, sfODataBackgroundCertificatesCreate.institution) &&
        Objects.equals(this.lastModifiedDate, sfODataBackgroundCertificatesCreate.lastModifiedDate) &&
        Objects.equals(this.name, sfODataBackgroundCertificatesCreate.name) &&
        Objects.equals(this.startDate, sfODataBackgroundCertificatesCreate.startDate) &&
        Objects.equals(this.userId, sfODataBackgroundCertificatesCreate.userId) &&
        Objects.equals(this.userIdNavAtOdataBind, sfODataBackgroundCertificatesCreate.userIdNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundElementId, bgOrderPos, description, endDate, institution, lastModifiedDate, name, startDate, userId, userIdNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataBackgroundCertificatesCreate {\n");
    
    sb.append("    backgroundElementId: ").append(toIndentedString(backgroundElementId)).append("\n");
    sb.append("    bgOrderPos: ").append(toIndentedString(bgOrderPos)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    institution: ").append(toIndentedString(institution)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userIdNavAtOdataBind: ").append(toIndentedString(userIdNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
