/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataCalibrationSessionReviewerUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataCalibrationSessionReviewerUpdate {
  @JsonProperty("calSessionId")
  private AnyOfSFODataCalibrationSessionReviewerUpdateCalSessionId calSessionId = null;

  @JsonProperty("reviewerType")
  private String reviewerType = null;

  @JsonProperty("userId")
  private String userId = null;

  public SFODataCalibrationSessionReviewerUpdate calSessionId(AnyOfSFODataCalibrationSessionReviewerUpdateCalSessionId calSessionId) {
    this.calSessionId = calSessionId;
    return this;
  }

   /**
   * Get calSessionId
   * @return calSessionId
  **/
  public AnyOfSFODataCalibrationSessionReviewerUpdateCalSessionId getCalSessionId() {
    return calSessionId;
  }

  public void setCalSessionId(AnyOfSFODataCalibrationSessionReviewerUpdateCalSessionId calSessionId) {
    this.calSessionId = calSessionId;
  }

  public SFODataCalibrationSessionReviewerUpdate reviewerType(String reviewerType) {
    this.reviewerType = reviewerType;
    return this;
  }

   /**
   * Get reviewerType
   * @return reviewerType
  **/
  public String getReviewerType() {
    return reviewerType;
  }

  public void setReviewerType(String reviewerType) {
    this.reviewerType = reviewerType;
  }

  public SFODataCalibrationSessionReviewerUpdate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataCalibrationSessionReviewerUpdate sfODataCalibrationSessionReviewerUpdate = (SFODataCalibrationSessionReviewerUpdate) o;
    return Objects.equals(this.calSessionId, sfODataCalibrationSessionReviewerUpdate.calSessionId) &&
        Objects.equals(this.reviewerType, sfODataCalibrationSessionReviewerUpdate.reviewerType) &&
        Objects.equals(this.userId, sfODataCalibrationSessionReviewerUpdate.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calSessionId, reviewerType, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataCalibrationSessionReviewerUpdate {\n");
    
    sb.append("    calSessionId: ").append(toIndentedString(calSessionId)).append("\n");
    sb.append("    reviewerType: ").append(toIndentedString(reviewerType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
