/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataUser;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataBackgroundAwards
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataBackgroundAwards {
  @JsonProperty("backgroundElementId")
  private AnyOfSFODataBackgroundAwardsBackgroundElementId backgroundElementId = null;

  @JsonProperty("bgOrderPos")
  private AnyOfSFODataBackgroundAwardsBgOrderPos bgOrderPos = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("institution")
  private String institution = null;

  @JsonProperty("issueDate")
  private OffsetDateTime issueDate = null;

  @JsonProperty("lastModifiedDate")
  private OffsetDateTime lastModifiedDate = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("userIdNav")
  private SFODataUser userIdNav = null;

  public SFODataBackgroundAwards backgroundElementId(AnyOfSFODataBackgroundAwardsBackgroundElementId backgroundElementId) {
    this.backgroundElementId = backgroundElementId;
    return this;
  }

   /**
   * Get backgroundElementId
   * @return backgroundElementId
  **/
  public AnyOfSFODataBackgroundAwardsBackgroundElementId getBackgroundElementId() {
    return backgroundElementId;
  }

  public void setBackgroundElementId(AnyOfSFODataBackgroundAwardsBackgroundElementId backgroundElementId) {
    this.backgroundElementId = backgroundElementId;
  }

  public SFODataBackgroundAwards bgOrderPos(AnyOfSFODataBackgroundAwardsBgOrderPos bgOrderPos) {
    this.bgOrderPos = bgOrderPos;
    return this;
  }

   /**
   * Get bgOrderPos
   * @return bgOrderPos
  **/
  public AnyOfSFODataBackgroundAwardsBgOrderPos getBgOrderPos() {
    return bgOrderPos;
  }

  public void setBgOrderPos(AnyOfSFODataBackgroundAwardsBgOrderPos bgOrderPos) {
    this.bgOrderPos = bgOrderPos;
  }

  public SFODataBackgroundAwards description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SFODataBackgroundAwards institution(String institution) {
    this.institution = institution;
    return this;
  }

   /**
   * Get institution
   * @return institution
  **/
  public String getInstitution() {
    return institution;
  }

  public void setInstitution(String institution) {
    this.institution = institution;
  }

  public SFODataBackgroundAwards issueDate(OffsetDateTime issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/
  public OffsetDateTime getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(OffsetDateTime issueDate) {
    this.issueDate = issueDate;
  }

  public SFODataBackgroundAwards lastModifiedDate(OffsetDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Get lastModifiedDate
   * @return lastModifiedDate
  **/
  public OffsetDateTime getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(OffsetDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public SFODataBackgroundAwards name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SFODataBackgroundAwards userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataBackgroundAwards userIdNav(SFODataUser userIdNav) {
    this.userIdNav = userIdNav;
    return this;
  }

   /**
   * Get userIdNav
   * @return userIdNav
  **/
  public SFODataUser getUserIdNav() {
    return userIdNav;
  }

  public void setUserIdNav(SFODataUser userIdNav) {
    this.userIdNav = userIdNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataBackgroundAwards sfODataBackgroundAwards = (SFODataBackgroundAwards) o;
    return Objects.equals(this.backgroundElementId, sfODataBackgroundAwards.backgroundElementId) &&
        Objects.equals(this.bgOrderPos, sfODataBackgroundAwards.bgOrderPos) &&
        Objects.equals(this.description, sfODataBackgroundAwards.description) &&
        Objects.equals(this.institution, sfODataBackgroundAwards.institution) &&
        Objects.equals(this.issueDate, sfODataBackgroundAwards.issueDate) &&
        Objects.equals(this.lastModifiedDate, sfODataBackgroundAwards.lastModifiedDate) &&
        Objects.equals(this.name, sfODataBackgroundAwards.name) &&
        Objects.equals(this.userId, sfODataBackgroundAwards.userId) &&
        Objects.equals(this.userIdNav, sfODataBackgroundAwards.userIdNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundElementId, bgOrderPos, description, institution, issueDate, lastModifiedDate, name, userId, userIdNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataBackgroundAwards {\n");
    
    sb.append("    backgroundElementId: ").append(toIndentedString(backgroundElementId)).append("\n");
    sb.append("    bgOrderPos: ").append(toIndentedString(bgOrderPos)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    institution: ").append(toIndentedString(institution)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userIdNav: ").append(toIndentedString(userIdNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
