/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataFormReviewInfoSectionUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataFormReviewInfoSectionUpdate {
  @JsonProperty("formDateFormat")
  private String formDateFormat = null;

  @JsonProperty("formOriginator")
  private String formOriginator = null;

  @JsonProperty("isDueDateValidationDisabled")
  private Boolean isDueDateValidationDisabled = null;

  @JsonProperty("isReviewDatesEditable")
  private Boolean isReviewDatesEditable = null;

  @JsonProperty("reviewDueDate")
  private String reviewDueDate = null;

  @JsonProperty("reviewEndDate")
  private String reviewEndDate = null;

  @JsonProperty("reviewStartDate")
  private String reviewStartDate = null;

  @JsonProperty("sectionDescription")
  private String sectionDescription = null;

  @JsonProperty("sectionIndex")
  private Integer sectionIndex = null;

  @JsonProperty("sectionName")
  private String sectionName = null;

  public SFODataFormReviewInfoSectionUpdate formDateFormat(String formDateFormat) {
    this.formDateFormat = formDateFormat;
    return this;
  }

   /**
   * Get formDateFormat
   * @return formDateFormat
  **/
  public String getFormDateFormat() {
    return formDateFormat;
  }

  public void setFormDateFormat(String formDateFormat) {
    this.formDateFormat = formDateFormat;
  }

  public SFODataFormReviewInfoSectionUpdate formOriginator(String formOriginator) {
    this.formOriginator = formOriginator;
    return this;
  }

   /**
   * Get formOriginator
   * @return formOriginator
  **/
  public String getFormOriginator() {
    return formOriginator;
  }

  public void setFormOriginator(String formOriginator) {
    this.formOriginator = formOriginator;
  }

  public SFODataFormReviewInfoSectionUpdate isDueDateValidationDisabled(Boolean isDueDateValidationDisabled) {
    this.isDueDateValidationDisabled = isDueDateValidationDisabled;
    return this;
  }

   /**
   * Get isDueDateValidationDisabled
   * @return isDueDateValidationDisabled
  **/
  public Boolean isIsDueDateValidationDisabled() {
    return isDueDateValidationDisabled;
  }

  public void setIsDueDateValidationDisabled(Boolean isDueDateValidationDisabled) {
    this.isDueDateValidationDisabled = isDueDateValidationDisabled;
  }

  public SFODataFormReviewInfoSectionUpdate isReviewDatesEditable(Boolean isReviewDatesEditable) {
    this.isReviewDatesEditable = isReviewDatesEditable;
    return this;
  }

   /**
   * Get isReviewDatesEditable
   * @return isReviewDatesEditable
  **/
  public Boolean isIsReviewDatesEditable() {
    return isReviewDatesEditable;
  }

  public void setIsReviewDatesEditable(Boolean isReviewDatesEditable) {
    this.isReviewDatesEditable = isReviewDatesEditable;
  }

  public SFODataFormReviewInfoSectionUpdate reviewDueDate(String reviewDueDate) {
    this.reviewDueDate = reviewDueDate;
    return this;
  }

   /**
   * Get reviewDueDate
   * @return reviewDueDate
  **/
  public String getReviewDueDate() {
    return reviewDueDate;
  }

  public void setReviewDueDate(String reviewDueDate) {
    this.reviewDueDate = reviewDueDate;
  }

  public SFODataFormReviewInfoSectionUpdate reviewEndDate(String reviewEndDate) {
    this.reviewEndDate = reviewEndDate;
    return this;
  }

   /**
   * Get reviewEndDate
   * @return reviewEndDate
  **/
  public String getReviewEndDate() {
    return reviewEndDate;
  }

  public void setReviewEndDate(String reviewEndDate) {
    this.reviewEndDate = reviewEndDate;
  }

  public SFODataFormReviewInfoSectionUpdate reviewStartDate(String reviewStartDate) {
    this.reviewStartDate = reviewStartDate;
    return this;
  }

   /**
   * Get reviewStartDate
   * @return reviewStartDate
  **/
  public String getReviewStartDate() {
    return reviewStartDate;
  }

  public void setReviewStartDate(String reviewStartDate) {
    this.reviewStartDate = reviewStartDate;
  }

  public SFODataFormReviewInfoSectionUpdate sectionDescription(String sectionDescription) {
    this.sectionDescription = sectionDescription;
    return this;
  }

   /**
   * Get sectionDescription
   * @return sectionDescription
  **/
  public String getSectionDescription() {
    return sectionDescription;
  }

  public void setSectionDescription(String sectionDescription) {
    this.sectionDescription = sectionDescription;
  }

  public SFODataFormReviewInfoSectionUpdate sectionIndex(Integer sectionIndex) {
    this.sectionIndex = sectionIndex;
    return this;
  }

   /**
   * Get sectionIndex
   * @return sectionIndex
  **/
  public Integer getSectionIndex() {
    return sectionIndex;
  }

  public void setSectionIndex(Integer sectionIndex) {
    this.sectionIndex = sectionIndex;
  }

  public SFODataFormReviewInfoSectionUpdate sectionName(String sectionName) {
    this.sectionName = sectionName;
    return this;
  }

   /**
   * Get sectionName
   * @return sectionName
  **/
  public String getSectionName() {
    return sectionName;
  }

  public void setSectionName(String sectionName) {
    this.sectionName = sectionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataFormReviewInfoSectionUpdate sfODataFormReviewInfoSectionUpdate = (SFODataFormReviewInfoSectionUpdate) o;
    return Objects.equals(this.formDateFormat, sfODataFormReviewInfoSectionUpdate.formDateFormat) &&
        Objects.equals(this.formOriginator, sfODataFormReviewInfoSectionUpdate.formOriginator) &&
        Objects.equals(this.isDueDateValidationDisabled, sfODataFormReviewInfoSectionUpdate.isDueDateValidationDisabled) &&
        Objects.equals(this.isReviewDatesEditable, sfODataFormReviewInfoSectionUpdate.isReviewDatesEditable) &&
        Objects.equals(this.reviewDueDate, sfODataFormReviewInfoSectionUpdate.reviewDueDate) &&
        Objects.equals(this.reviewEndDate, sfODataFormReviewInfoSectionUpdate.reviewEndDate) &&
        Objects.equals(this.reviewStartDate, sfODataFormReviewInfoSectionUpdate.reviewStartDate) &&
        Objects.equals(this.sectionDescription, sfODataFormReviewInfoSectionUpdate.sectionDescription) &&
        Objects.equals(this.sectionIndex, sfODataFormReviewInfoSectionUpdate.sectionIndex) &&
        Objects.equals(this.sectionName, sfODataFormReviewInfoSectionUpdate.sectionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formDateFormat, formOriginator, isDueDateValidationDisabled, isReviewDatesEditable, reviewDueDate, reviewEndDate, reviewStartDate, sectionDescription, sectionIndex, sectionName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataFormReviewInfoSectionUpdate {\n");
    
    sb.append("    formDateFormat: ").append(toIndentedString(formDateFormat)).append("\n");
    sb.append("    formOriginator: ").append(toIndentedString(formOriginator)).append("\n");
    sb.append("    isDueDateValidationDisabled: ").append(toIndentedString(isDueDateValidationDisabled)).append("\n");
    sb.append("    isReviewDatesEditable: ").append(toIndentedString(isReviewDatesEditable)).append("\n");
    sb.append("    reviewDueDate: ").append(toIndentedString(reviewDueDate)).append("\n");
    sb.append("    reviewEndDate: ").append(toIndentedString(reviewEndDate)).append("\n");
    sb.append("    reviewStartDate: ").append(toIndentedString(reviewStartDate)).append("\n");
    sb.append("    sectionDescription: ").append(toIndentedString(sectionDescription)).append("\n");
    sb.append("    sectionIndex: ").append(toIndentedString(sectionIndex)).append("\n");
    sb.append("    sectionName: ").append(toIndentedString(sectionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
