/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataMDFEnumValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataDomainEventAlert
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataDomainEventAlert {
  @JsonProperty("alertId")
  private String alertId = null;

  @JsonProperty("alertTypeId")
  private String alertTypeId = null;

  @JsonProperty("assigneeUserId")
  private String assigneeUserId = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("errorMessage")
  private String errorMessage = null;

  @JsonProperty("eventId")
  private String eventId = null;

  @JsonProperty("eventSubject")
  private String eventSubject = null;

  @JsonProperty("eventType")
  private String eventType = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("fullSubscriberName")
  private String fullSubscriberName = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("messageKey")
  private String messageKey = null;

  @JsonProperty("messageParameter1")
  private String messageParameter1 = null;

  @JsonProperty("messageParameter2")
  private String messageParameter2 = null;

  @JsonProperty("messageParameter3")
  private String messageParameter3 = null;

  @JsonProperty("messageParameter4")
  private String messageParameter4 = null;

  @JsonProperty("messageParameter5")
  private String messageParameter5 = null;

  @JsonProperty("messageParameter6")
  private String messageParameter6 = null;

  @JsonProperty("serviceName")
  private String serviceName = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("subscriberName")
  private String subscriberName = null;

  @JsonProperty("userSysId")
  private String userSysId = null;

  @JsonProperty("assigneeUserIdNav")
  private AllOfSFODataDomainEventAlertAssigneeUserIdNav assigneeUserIdNav = null;

  @JsonProperty("createdByNav")
  private AllOfSFODataDomainEventAlertCreatedByNav createdByNav = null;

  @JsonProperty("lastModifiedByNav")
  private AllOfSFODataDomainEventAlertLastModifiedByNav lastModifiedByNav = null;

  @JsonProperty("mdfSystemRecordStatusNav")
  private SFODataMDFEnumValue mdfSystemRecordStatusNav = null;

  @JsonProperty("statusNav")
  private SFODataMDFEnumValue statusNav = null;

  public SFODataDomainEventAlert alertId(String alertId) {
    this.alertId = alertId;
    return this;
  }

   /**
   * Get alertId
   * @return alertId
  **/
  public String getAlertId() {
    return alertId;
  }

  public void setAlertId(String alertId) {
    this.alertId = alertId;
  }

  public SFODataDomainEventAlert alertTypeId(String alertTypeId) {
    this.alertTypeId = alertTypeId;
    return this;
  }

   /**
   * Get alertTypeId
   * @return alertTypeId
  **/
  public String getAlertTypeId() {
    return alertTypeId;
  }

  public void setAlertTypeId(String alertTypeId) {
    this.alertTypeId = alertTypeId;
  }

  public SFODataDomainEventAlert assigneeUserId(String assigneeUserId) {
    this.assigneeUserId = assigneeUserId;
    return this;
  }

   /**
   * Get assigneeUserId
   * @return assigneeUserId
  **/
  public String getAssigneeUserId() {
    return assigneeUserId;
  }

  public void setAssigneeUserId(String assigneeUserId) {
    this.assigneeUserId = assigneeUserId;
  }

  public SFODataDomainEventAlert createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataDomainEventAlert createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataDomainEventAlert errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public SFODataDomainEventAlert eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public SFODataDomainEventAlert eventSubject(String eventSubject) {
    this.eventSubject = eventSubject;
    return this;
  }

   /**
   * Get eventSubject
   * @return eventSubject
  **/
  public String getEventSubject() {
    return eventSubject;
  }

  public void setEventSubject(String eventSubject) {
    this.eventSubject = eventSubject;
  }

  public SFODataDomainEventAlert eventType(String eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  public String getEventType() {
    return eventType;
  }

  public void setEventType(String eventType) {
    this.eventType = eventType;
  }

  public SFODataDomainEventAlert externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataDomainEventAlert fullSubscriberName(String fullSubscriberName) {
    this.fullSubscriberName = fullSubscriberName;
    return this;
  }

   /**
   * Get fullSubscriberName
   * @return fullSubscriberName
  **/
  public String getFullSubscriberName() {
    return fullSubscriberName;
  }

  public void setFullSubscriberName(String fullSubscriberName) {
    this.fullSubscriberName = fullSubscriberName;
  }

  public SFODataDomainEventAlert lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataDomainEventAlert lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataDomainEventAlert mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataDomainEventAlert message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public SFODataDomainEventAlert messageKey(String messageKey) {
    this.messageKey = messageKey;
    return this;
  }

   /**
   * Get messageKey
   * @return messageKey
  **/
  public String getMessageKey() {
    return messageKey;
  }

  public void setMessageKey(String messageKey) {
    this.messageKey = messageKey;
  }

  public SFODataDomainEventAlert messageParameter1(String messageParameter1) {
    this.messageParameter1 = messageParameter1;
    return this;
  }

   /**
   * Get messageParameter1
   * @return messageParameter1
  **/
  public String getMessageParameter1() {
    return messageParameter1;
  }

  public void setMessageParameter1(String messageParameter1) {
    this.messageParameter1 = messageParameter1;
  }

  public SFODataDomainEventAlert messageParameter2(String messageParameter2) {
    this.messageParameter2 = messageParameter2;
    return this;
  }

   /**
   * Get messageParameter2
   * @return messageParameter2
  **/
  public String getMessageParameter2() {
    return messageParameter2;
  }

  public void setMessageParameter2(String messageParameter2) {
    this.messageParameter2 = messageParameter2;
  }

  public SFODataDomainEventAlert messageParameter3(String messageParameter3) {
    this.messageParameter3 = messageParameter3;
    return this;
  }

   /**
   * Get messageParameter3
   * @return messageParameter3
  **/
  public String getMessageParameter3() {
    return messageParameter3;
  }

  public void setMessageParameter3(String messageParameter3) {
    this.messageParameter3 = messageParameter3;
  }

  public SFODataDomainEventAlert messageParameter4(String messageParameter4) {
    this.messageParameter4 = messageParameter4;
    return this;
  }

   /**
   * Get messageParameter4
   * @return messageParameter4
  **/
  public String getMessageParameter4() {
    return messageParameter4;
  }

  public void setMessageParameter4(String messageParameter4) {
    this.messageParameter4 = messageParameter4;
  }

  public SFODataDomainEventAlert messageParameter5(String messageParameter5) {
    this.messageParameter5 = messageParameter5;
    return this;
  }

   /**
   * Get messageParameter5
   * @return messageParameter5
  **/
  public String getMessageParameter5() {
    return messageParameter5;
  }

  public void setMessageParameter5(String messageParameter5) {
    this.messageParameter5 = messageParameter5;
  }

  public SFODataDomainEventAlert messageParameter6(String messageParameter6) {
    this.messageParameter6 = messageParameter6;
    return this;
  }

   /**
   * Get messageParameter6
   * @return messageParameter6
  **/
  public String getMessageParameter6() {
    return messageParameter6;
  }

  public void setMessageParameter6(String messageParameter6) {
    this.messageParameter6 = messageParameter6;
  }

  public SFODataDomainEventAlert serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public SFODataDomainEventAlert status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SFODataDomainEventAlert subscriberName(String subscriberName) {
    this.subscriberName = subscriberName;
    return this;
  }

   /**
   * Get subscriberName
   * @return subscriberName
  **/
  public String getSubscriberName() {
    return subscriberName;
  }

  public void setSubscriberName(String subscriberName) {
    this.subscriberName = subscriberName;
  }

  public SFODataDomainEventAlert userSysId(String userSysId) {
    this.userSysId = userSysId;
    return this;
  }

   /**
   * Get userSysId
   * @return userSysId
  **/
  public String getUserSysId() {
    return userSysId;
  }

  public void setUserSysId(String userSysId) {
    this.userSysId = userSysId;
  }

  public SFODataDomainEventAlert assigneeUserIdNav(AllOfSFODataDomainEventAlertAssigneeUserIdNav assigneeUserIdNav) {
    this.assigneeUserIdNav = assigneeUserIdNav;
    return this;
  }

   /**
   * Get assigneeUserIdNav
   * @return assigneeUserIdNav
  **/
  public AllOfSFODataDomainEventAlertAssigneeUserIdNav getAssigneeUserIdNav() {
    return assigneeUserIdNav;
  }

  public void setAssigneeUserIdNav(AllOfSFODataDomainEventAlertAssigneeUserIdNav assigneeUserIdNav) {
    this.assigneeUserIdNav = assigneeUserIdNav;
  }

  public SFODataDomainEventAlert createdByNav(AllOfSFODataDomainEventAlertCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
    return this;
  }

   /**
   * Get createdByNav
   * @return createdByNav
  **/
  public AllOfSFODataDomainEventAlertCreatedByNav getCreatedByNav() {
    return createdByNav;
  }

  public void setCreatedByNav(AllOfSFODataDomainEventAlertCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
  }

  public SFODataDomainEventAlert lastModifiedByNav(AllOfSFODataDomainEventAlertLastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
    return this;
  }

   /**
   * Get lastModifiedByNav
   * @return lastModifiedByNav
  **/
  public AllOfSFODataDomainEventAlertLastModifiedByNav getLastModifiedByNav() {
    return lastModifiedByNav;
  }

  public void setLastModifiedByNav(AllOfSFODataDomainEventAlertLastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
  }

  public SFODataDomainEventAlert mdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNav
   * @return mdfSystemRecordStatusNav
  **/
  public SFODataMDFEnumValue getMdfSystemRecordStatusNav() {
    return mdfSystemRecordStatusNav;
  }

  public void setMdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
  }

  public SFODataDomainEventAlert statusNav(SFODataMDFEnumValue statusNav) {
    this.statusNav = statusNav;
    return this;
  }

   /**
   * Get statusNav
   * @return statusNav
  **/
  public SFODataMDFEnumValue getStatusNav() {
    return statusNav;
  }

  public void setStatusNav(SFODataMDFEnumValue statusNav) {
    this.statusNav = statusNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataDomainEventAlert sfODataDomainEventAlert = (SFODataDomainEventAlert) o;
    return Objects.equals(this.alertId, sfODataDomainEventAlert.alertId) &&
        Objects.equals(this.alertTypeId, sfODataDomainEventAlert.alertTypeId) &&
        Objects.equals(this.assigneeUserId, sfODataDomainEventAlert.assigneeUserId) &&
        Objects.equals(this.createdBy, sfODataDomainEventAlert.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataDomainEventAlert.createdDateTime) &&
        Objects.equals(this.errorMessage, sfODataDomainEventAlert.errorMessage) &&
        Objects.equals(this.eventId, sfODataDomainEventAlert.eventId) &&
        Objects.equals(this.eventSubject, sfODataDomainEventAlert.eventSubject) &&
        Objects.equals(this.eventType, sfODataDomainEventAlert.eventType) &&
        Objects.equals(this.externalCode, sfODataDomainEventAlert.externalCode) &&
        Objects.equals(this.fullSubscriberName, sfODataDomainEventAlert.fullSubscriberName) &&
        Objects.equals(this.lastModifiedBy, sfODataDomainEventAlert.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataDomainEventAlert.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataDomainEventAlert.mdfSystemRecordStatus) &&
        Objects.equals(this.message, sfODataDomainEventAlert.message) &&
        Objects.equals(this.messageKey, sfODataDomainEventAlert.messageKey) &&
        Objects.equals(this.messageParameter1, sfODataDomainEventAlert.messageParameter1) &&
        Objects.equals(this.messageParameter2, sfODataDomainEventAlert.messageParameter2) &&
        Objects.equals(this.messageParameter3, sfODataDomainEventAlert.messageParameter3) &&
        Objects.equals(this.messageParameter4, sfODataDomainEventAlert.messageParameter4) &&
        Objects.equals(this.messageParameter5, sfODataDomainEventAlert.messageParameter5) &&
        Objects.equals(this.messageParameter6, sfODataDomainEventAlert.messageParameter6) &&
        Objects.equals(this.serviceName, sfODataDomainEventAlert.serviceName) &&
        Objects.equals(this.status, sfODataDomainEventAlert.status) &&
        Objects.equals(this.subscriberName, sfODataDomainEventAlert.subscriberName) &&
        Objects.equals(this.userSysId, sfODataDomainEventAlert.userSysId) &&
        Objects.equals(this.assigneeUserIdNav, sfODataDomainEventAlert.assigneeUserIdNav) &&
        Objects.equals(this.createdByNav, sfODataDomainEventAlert.createdByNav) &&
        Objects.equals(this.lastModifiedByNav, sfODataDomainEventAlert.lastModifiedByNav) &&
        Objects.equals(this.mdfSystemRecordStatusNav, sfODataDomainEventAlert.mdfSystemRecordStatusNav) &&
        Objects.equals(this.statusNav, sfODataDomainEventAlert.statusNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alertId, alertTypeId, assigneeUserId, createdBy, createdDateTime, errorMessage, eventId, eventSubject, eventType, externalCode, fullSubscriberName, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, message, messageKey, messageParameter1, messageParameter2, messageParameter3, messageParameter4, messageParameter5, messageParameter6, serviceName, status, subscriberName, userSysId, assigneeUserIdNav, createdByNav, lastModifiedByNav, mdfSystemRecordStatusNav, statusNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataDomainEventAlert {\n");
    
    sb.append("    alertId: ").append(toIndentedString(alertId)).append("\n");
    sb.append("    alertTypeId: ").append(toIndentedString(alertTypeId)).append("\n");
    sb.append("    assigneeUserId: ").append(toIndentedString(assigneeUserId)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    eventSubject: ").append(toIndentedString(eventSubject)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    fullSubscriberName: ").append(toIndentedString(fullSubscriberName)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    messageKey: ").append(toIndentedString(messageKey)).append("\n");
    sb.append("    messageParameter1: ").append(toIndentedString(messageParameter1)).append("\n");
    sb.append("    messageParameter2: ").append(toIndentedString(messageParameter2)).append("\n");
    sb.append("    messageParameter3: ").append(toIndentedString(messageParameter3)).append("\n");
    sb.append("    messageParameter4: ").append(toIndentedString(messageParameter4)).append("\n");
    sb.append("    messageParameter5: ").append(toIndentedString(messageParameter5)).append("\n");
    sb.append("    messageParameter6: ").append(toIndentedString(messageParameter6)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    subscriberName: ").append(toIndentedString(subscriberName)).append("\n");
    sb.append("    userSysId: ").append(toIndentedString(userSysId)).append("\n");
    sb.append("    assigneeUserIdNav: ").append(toIndentedString(assigneeUserIdNav)).append("\n");
    sb.append("    createdByNav: ").append(toIndentedString(createdByNav)).append("\n");
    sb.append("    lastModifiedByNav: ").append(toIndentedString(lastModifiedByNav)).append("\n");
    sb.append("    mdfSystemRecordStatusNav: ").append(toIndentedString(mdfSystemRecordStatusNav)).append("\n");
    sb.append("    statusNav: ").append(toIndentedString(statusNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
