/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataTalentRatingsUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataTalentRatingsUpdate {
  @JsonProperty("employeeId")
  private String employeeId = null;

  @JsonProperty("feedbackModule")
  private Integer feedbackModule = null;

  @JsonProperty("feedbackName")
  private String feedbackName = null;

  @JsonProperty("feedbackRating")
  private Double feedbackRating = null;

  @JsonProperty("feedbackRatingLabel")
  private String feedbackRatingLabel = null;

  @JsonProperty("feedbackScaleId")
  private AnyOfSFODataTalentRatingsUpdateFeedbackScaleId feedbackScaleId = null;

  @JsonProperty("feedbackScaleMaximum")
  private Double feedbackScaleMaximum = null;

  @JsonProperty("feedbackScaleMinimum")
  private Double feedbackScaleMinimum = null;

  @JsonProperty("feedbackSource")
  private Integer feedbackSource = null;

  @JsonProperty("feedbackType")
  private Integer feedbackType = null;

  @JsonProperty("feedbackWeight")
  private Double feedbackWeight = null;

  @JsonProperty("formContentId")
  private AnyOfSFODataTalentRatingsUpdateFormContentId formContentId = null;

  @JsonProperty("formDataId")
  private AnyOfSFODataTalentRatingsUpdateFormDataId formDataId = null;

  public SFODataTalentRatingsUpdate employeeId(String employeeId) {
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  public String getEmployeeId() {
    return employeeId;
  }

  public void setEmployeeId(String employeeId) {
    this.employeeId = employeeId;
  }

  public SFODataTalentRatingsUpdate feedbackModule(Integer feedbackModule) {
    this.feedbackModule = feedbackModule;
    return this;
  }

   /**
   * Get feedbackModule
   * @return feedbackModule
  **/
  public Integer getFeedbackModule() {
    return feedbackModule;
  }

  public void setFeedbackModule(Integer feedbackModule) {
    this.feedbackModule = feedbackModule;
  }

  public SFODataTalentRatingsUpdate feedbackName(String feedbackName) {
    this.feedbackName = feedbackName;
    return this;
  }

   /**
   * Get feedbackName
   * @return feedbackName
  **/
  public String getFeedbackName() {
    return feedbackName;
  }

  public void setFeedbackName(String feedbackName) {
    this.feedbackName = feedbackName;
  }

  public SFODataTalentRatingsUpdate feedbackRating(Double feedbackRating) {
    this.feedbackRating = feedbackRating;
    return this;
  }

   /**
   * Get feedbackRating
   * @return feedbackRating
  **/
  public Double getFeedbackRating() {
    return feedbackRating;
  }

  public void setFeedbackRating(Double feedbackRating) {
    this.feedbackRating = feedbackRating;
  }

  public SFODataTalentRatingsUpdate feedbackRatingLabel(String feedbackRatingLabel) {
    this.feedbackRatingLabel = feedbackRatingLabel;
    return this;
  }

   /**
   * Get feedbackRatingLabel
   * @return feedbackRatingLabel
  **/
  public String getFeedbackRatingLabel() {
    return feedbackRatingLabel;
  }

  public void setFeedbackRatingLabel(String feedbackRatingLabel) {
    this.feedbackRatingLabel = feedbackRatingLabel;
  }

  public SFODataTalentRatingsUpdate feedbackScaleId(AnyOfSFODataTalentRatingsUpdateFeedbackScaleId feedbackScaleId) {
    this.feedbackScaleId = feedbackScaleId;
    return this;
  }

   /**
   * Get feedbackScaleId
   * @return feedbackScaleId
  **/
  public AnyOfSFODataTalentRatingsUpdateFeedbackScaleId getFeedbackScaleId() {
    return feedbackScaleId;
  }

  public void setFeedbackScaleId(AnyOfSFODataTalentRatingsUpdateFeedbackScaleId feedbackScaleId) {
    this.feedbackScaleId = feedbackScaleId;
  }

  public SFODataTalentRatingsUpdate feedbackScaleMaximum(Double feedbackScaleMaximum) {
    this.feedbackScaleMaximum = feedbackScaleMaximum;
    return this;
  }

   /**
   * Get feedbackScaleMaximum
   * @return feedbackScaleMaximum
  **/
  public Double getFeedbackScaleMaximum() {
    return feedbackScaleMaximum;
  }

  public void setFeedbackScaleMaximum(Double feedbackScaleMaximum) {
    this.feedbackScaleMaximum = feedbackScaleMaximum;
  }

  public SFODataTalentRatingsUpdate feedbackScaleMinimum(Double feedbackScaleMinimum) {
    this.feedbackScaleMinimum = feedbackScaleMinimum;
    return this;
  }

   /**
   * Get feedbackScaleMinimum
   * @return feedbackScaleMinimum
  **/
  public Double getFeedbackScaleMinimum() {
    return feedbackScaleMinimum;
  }

  public void setFeedbackScaleMinimum(Double feedbackScaleMinimum) {
    this.feedbackScaleMinimum = feedbackScaleMinimum;
  }

  public SFODataTalentRatingsUpdate feedbackSource(Integer feedbackSource) {
    this.feedbackSource = feedbackSource;
    return this;
  }

   /**
   * Get feedbackSource
   * @return feedbackSource
  **/
  public Integer getFeedbackSource() {
    return feedbackSource;
  }

  public void setFeedbackSource(Integer feedbackSource) {
    this.feedbackSource = feedbackSource;
  }

  public SFODataTalentRatingsUpdate feedbackType(Integer feedbackType) {
    this.feedbackType = feedbackType;
    return this;
  }

   /**
   * Get feedbackType
   * @return feedbackType
  **/
  public Integer getFeedbackType() {
    return feedbackType;
  }

  public void setFeedbackType(Integer feedbackType) {
    this.feedbackType = feedbackType;
  }

  public SFODataTalentRatingsUpdate feedbackWeight(Double feedbackWeight) {
    this.feedbackWeight = feedbackWeight;
    return this;
  }

   /**
   * Get feedbackWeight
   * @return feedbackWeight
  **/
  public Double getFeedbackWeight() {
    return feedbackWeight;
  }

  public void setFeedbackWeight(Double feedbackWeight) {
    this.feedbackWeight = feedbackWeight;
  }

  public SFODataTalentRatingsUpdate formContentId(AnyOfSFODataTalentRatingsUpdateFormContentId formContentId) {
    this.formContentId = formContentId;
    return this;
  }

   /**
   * Get formContentId
   * @return formContentId
  **/
  public AnyOfSFODataTalentRatingsUpdateFormContentId getFormContentId() {
    return formContentId;
  }

  public void setFormContentId(AnyOfSFODataTalentRatingsUpdateFormContentId formContentId) {
    this.formContentId = formContentId;
  }

  public SFODataTalentRatingsUpdate formDataId(AnyOfSFODataTalentRatingsUpdateFormDataId formDataId) {
    this.formDataId = formDataId;
    return this;
  }

   /**
   * Get formDataId
   * @return formDataId
  **/
  public AnyOfSFODataTalentRatingsUpdateFormDataId getFormDataId() {
    return formDataId;
  }

  public void setFormDataId(AnyOfSFODataTalentRatingsUpdateFormDataId formDataId) {
    this.formDataId = formDataId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataTalentRatingsUpdate sfODataTalentRatingsUpdate = (SFODataTalentRatingsUpdate) o;
    return Objects.equals(this.employeeId, sfODataTalentRatingsUpdate.employeeId) &&
        Objects.equals(this.feedbackModule, sfODataTalentRatingsUpdate.feedbackModule) &&
        Objects.equals(this.feedbackName, sfODataTalentRatingsUpdate.feedbackName) &&
        Objects.equals(this.feedbackRating, sfODataTalentRatingsUpdate.feedbackRating) &&
        Objects.equals(this.feedbackRatingLabel, sfODataTalentRatingsUpdate.feedbackRatingLabel) &&
        Objects.equals(this.feedbackScaleId, sfODataTalentRatingsUpdate.feedbackScaleId) &&
        Objects.equals(this.feedbackScaleMaximum, sfODataTalentRatingsUpdate.feedbackScaleMaximum) &&
        Objects.equals(this.feedbackScaleMinimum, sfODataTalentRatingsUpdate.feedbackScaleMinimum) &&
        Objects.equals(this.feedbackSource, sfODataTalentRatingsUpdate.feedbackSource) &&
        Objects.equals(this.feedbackType, sfODataTalentRatingsUpdate.feedbackType) &&
        Objects.equals(this.feedbackWeight, sfODataTalentRatingsUpdate.feedbackWeight) &&
        Objects.equals(this.formContentId, sfODataTalentRatingsUpdate.formContentId) &&
        Objects.equals(this.formDataId, sfODataTalentRatingsUpdate.formDataId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeId, feedbackModule, feedbackName, feedbackRating, feedbackRatingLabel, feedbackScaleId, feedbackScaleMaximum, feedbackScaleMinimum, feedbackSource, feedbackType, feedbackWeight, formContentId, formDataId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataTalentRatingsUpdate {\n");
    
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    feedbackModule: ").append(toIndentedString(feedbackModule)).append("\n");
    sb.append("    feedbackName: ").append(toIndentedString(feedbackName)).append("\n");
    sb.append("    feedbackRating: ").append(toIndentedString(feedbackRating)).append("\n");
    sb.append("    feedbackRatingLabel: ").append(toIndentedString(feedbackRatingLabel)).append("\n");
    sb.append("    feedbackScaleId: ").append(toIndentedString(feedbackScaleId)).append("\n");
    sb.append("    feedbackScaleMaximum: ").append(toIndentedString(feedbackScaleMaximum)).append("\n");
    sb.append("    feedbackScaleMinimum: ").append(toIndentedString(feedbackScaleMinimum)).append("\n");
    sb.append("    feedbackSource: ").append(toIndentedString(feedbackSource)).append("\n");
    sb.append("    feedbackType: ").append(toIndentedString(feedbackType)).append("\n");
    sb.append("    feedbackWeight: ").append(toIndentedString(feedbackWeight)).append("\n");
    sb.append("    formContentId: ").append(toIndentedString(formContentId)).append("\n");
    sb.append("    formDataId: ").append(toIndentedString(formDataId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
