/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataMDFEnumValueUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataMDFEnumValueUpdate {
  @JsonProperty("da_DK")
  private String daDK = null;

  @JsonProperty("de_CH")
  private String deCH = null;

  @JsonProperty("de_DE")
  private String deDE = null;

  @JsonProperty("en_DEBUG")
  private String enDEBUG = null;

  @JsonProperty("en_GB")
  private String enGB = null;

  @JsonProperty("es_ES")
  private String esES = null;

  @JsonProperty("fi_FI")
  private String fiFI = null;

  @JsonProperty("fr_FR")
  private String frFR = null;

  @JsonProperty("hu_HU")
  private String huHU = null;

  @JsonProperty("it_IT")
  private String itIT = null;

  @JsonProperty("localized")
  private String localized = null;

  @JsonProperty("nb_NO")
  private String nbNO = null;

  @JsonProperty("nl_NL")
  private String nlNL = null;

  @JsonProperty("pl_PL")
  private String plPL = null;

  @JsonProperty("pt_PT")
  private String ptPT = null;

  @JsonProperty("sv_SE")
  private String svSE = null;

  public SFODataMDFEnumValueUpdate daDK(String daDK) {
    this.daDK = daDK;
    return this;
  }

   /**
   * Get daDK
   * @return daDK
  **/
  public String getDaDK() {
    return daDK;
  }

  public void setDaDK(String daDK) {
    this.daDK = daDK;
  }

  public SFODataMDFEnumValueUpdate deCH(String deCH) {
    this.deCH = deCH;
    return this;
  }

   /**
   * Get deCH
   * @return deCH
  **/
  public String getDeCH() {
    return deCH;
  }

  public void setDeCH(String deCH) {
    this.deCH = deCH;
  }

  public SFODataMDFEnumValueUpdate deDE(String deDE) {
    this.deDE = deDE;
    return this;
  }

   /**
   * Get deDE
   * @return deDE
  **/
  public String getDeDE() {
    return deDE;
  }

  public void setDeDE(String deDE) {
    this.deDE = deDE;
  }

  public SFODataMDFEnumValueUpdate enDEBUG(String enDEBUG) {
    this.enDEBUG = enDEBUG;
    return this;
  }

   /**
   * Get enDEBUG
   * @return enDEBUG
  **/
  public String getEnDEBUG() {
    return enDEBUG;
  }

  public void setEnDEBUG(String enDEBUG) {
    this.enDEBUG = enDEBUG;
  }

  public SFODataMDFEnumValueUpdate enGB(String enGB) {
    this.enGB = enGB;
    return this;
  }

   /**
   * Get enGB
   * @return enGB
  **/
  public String getEnGB() {
    return enGB;
  }

  public void setEnGB(String enGB) {
    this.enGB = enGB;
  }

  public SFODataMDFEnumValueUpdate esES(String esES) {
    this.esES = esES;
    return this;
  }

   /**
   * Get esES
   * @return esES
  **/
  public String getEsES() {
    return esES;
  }

  public void setEsES(String esES) {
    this.esES = esES;
  }

  public SFODataMDFEnumValueUpdate fiFI(String fiFI) {
    this.fiFI = fiFI;
    return this;
  }

   /**
   * Get fiFI
   * @return fiFI
  **/
  public String getFiFI() {
    return fiFI;
  }

  public void setFiFI(String fiFI) {
    this.fiFI = fiFI;
  }

  public SFODataMDFEnumValueUpdate frFR(String frFR) {
    this.frFR = frFR;
    return this;
  }

   /**
   * Get frFR
   * @return frFR
  **/
  public String getFrFR() {
    return frFR;
  }

  public void setFrFR(String frFR) {
    this.frFR = frFR;
  }

  public SFODataMDFEnumValueUpdate huHU(String huHU) {
    this.huHU = huHU;
    return this;
  }

   /**
   * Get huHU
   * @return huHU
  **/
  public String getHuHU() {
    return huHU;
  }

  public void setHuHU(String huHU) {
    this.huHU = huHU;
  }

  public SFODataMDFEnumValueUpdate itIT(String itIT) {
    this.itIT = itIT;
    return this;
  }

   /**
   * Get itIT
   * @return itIT
  **/
  public String getItIT() {
    return itIT;
  }

  public void setItIT(String itIT) {
    this.itIT = itIT;
  }

  public SFODataMDFEnumValueUpdate localized(String localized) {
    this.localized = localized;
    return this;
  }

   /**
   * Get localized
   * @return localized
  **/
  public String getLocalized() {
    return localized;
  }

  public void setLocalized(String localized) {
    this.localized = localized;
  }

  public SFODataMDFEnumValueUpdate nbNO(String nbNO) {
    this.nbNO = nbNO;
    return this;
  }

   /**
   * Get nbNO
   * @return nbNO
  **/
  public String getNbNO() {
    return nbNO;
  }

  public void setNbNO(String nbNO) {
    this.nbNO = nbNO;
  }

  public SFODataMDFEnumValueUpdate nlNL(String nlNL) {
    this.nlNL = nlNL;
    return this;
  }

   /**
   * Get nlNL
   * @return nlNL
  **/
  public String getNlNL() {
    return nlNL;
  }

  public void setNlNL(String nlNL) {
    this.nlNL = nlNL;
  }

  public SFODataMDFEnumValueUpdate plPL(String plPL) {
    this.plPL = plPL;
    return this;
  }

   /**
   * Get plPL
   * @return plPL
  **/
  public String getPlPL() {
    return plPL;
  }

  public void setPlPL(String plPL) {
    this.plPL = plPL;
  }

  public SFODataMDFEnumValueUpdate ptPT(String ptPT) {
    this.ptPT = ptPT;
    return this;
  }

   /**
   * Get ptPT
   * @return ptPT
  **/
  public String getPtPT() {
    return ptPT;
  }

  public void setPtPT(String ptPT) {
    this.ptPT = ptPT;
  }

  public SFODataMDFEnumValueUpdate svSE(String svSE) {
    this.svSE = svSE;
    return this;
  }

   /**
   * Get svSE
   * @return svSE
  **/
  public String getSvSE() {
    return svSE;
  }

  public void setSvSE(String svSE) {
    this.svSE = svSE;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataMDFEnumValueUpdate sfODataMDFEnumValueUpdate = (SFODataMDFEnumValueUpdate) o;
    return Objects.equals(this.daDK, sfODataMDFEnumValueUpdate.daDK) &&
        Objects.equals(this.deCH, sfODataMDFEnumValueUpdate.deCH) &&
        Objects.equals(this.deDE, sfODataMDFEnumValueUpdate.deDE) &&
        Objects.equals(this.enDEBUG, sfODataMDFEnumValueUpdate.enDEBUG) &&
        Objects.equals(this.enGB, sfODataMDFEnumValueUpdate.enGB) &&
        Objects.equals(this.esES, sfODataMDFEnumValueUpdate.esES) &&
        Objects.equals(this.fiFI, sfODataMDFEnumValueUpdate.fiFI) &&
        Objects.equals(this.frFR, sfODataMDFEnumValueUpdate.frFR) &&
        Objects.equals(this.huHU, sfODataMDFEnumValueUpdate.huHU) &&
        Objects.equals(this.itIT, sfODataMDFEnumValueUpdate.itIT) &&
        Objects.equals(this.localized, sfODataMDFEnumValueUpdate.localized) &&
        Objects.equals(this.nbNO, sfODataMDFEnumValueUpdate.nbNO) &&
        Objects.equals(this.nlNL, sfODataMDFEnumValueUpdate.nlNL) &&
        Objects.equals(this.plPL, sfODataMDFEnumValueUpdate.plPL) &&
        Objects.equals(this.ptPT, sfODataMDFEnumValueUpdate.ptPT) &&
        Objects.equals(this.svSE, sfODataMDFEnumValueUpdate.svSE);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daDK, deCH, deDE, enDEBUG, enGB, esES, fiFI, frFR, huHU, itIT, localized, nbNO, nlNL, plPL, ptPT, svSE);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataMDFEnumValueUpdate {\n");
    
    sb.append("    daDK: ").append(toIndentedString(daDK)).append("\n");
    sb.append("    deCH: ").append(toIndentedString(deCH)).append("\n");
    sb.append("    deDE: ").append(toIndentedString(deDE)).append("\n");
    sb.append("    enDEBUG: ").append(toIndentedString(enDEBUG)).append("\n");
    sb.append("    enGB: ").append(toIndentedString(enGB)).append("\n");
    sb.append("    esES: ").append(toIndentedString(esES)).append("\n");
    sb.append("    fiFI: ").append(toIndentedString(fiFI)).append("\n");
    sb.append("    frFR: ").append(toIndentedString(frFR)).append("\n");
    sb.append("    huHU: ").append(toIndentedString(huHU)).append("\n");
    sb.append("    itIT: ").append(toIndentedString(itIT)).append("\n");
    sb.append("    localized: ").append(toIndentedString(localized)).append("\n");
    sb.append("    nbNO: ").append(toIndentedString(nbNO)).append("\n");
    sb.append("    nlNL: ").append(toIndentedString(nlNL)).append("\n");
    sb.append("    plPL: ").append(toIndentedString(plPL)).append("\n");
    sb.append("    ptPT: ").append(toIndentedString(ptPT)).append("\n");
    sb.append("    svSE: ").append(toIndentedString(svSE)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
