/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataEPProfileViewUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataEPProfileViewUpdate {
  @JsonProperty("dashboardTitle")
  private String dashboardTitle = null;

  @JsonProperty("dashboardType")
  private String dashboardType = null;

  @JsonProperty("liveProfilePhotoPermission")
  private String liveProfilePhotoPermission = null;

  public SFODataEPProfileViewUpdate dashboardTitle(String dashboardTitle) {
    this.dashboardTitle = dashboardTitle;
    return this;
  }

   /**
   * Get dashboardTitle
   * @return dashboardTitle
  **/
  public String getDashboardTitle() {
    return dashboardTitle;
  }

  public void setDashboardTitle(String dashboardTitle) {
    this.dashboardTitle = dashboardTitle;
  }

  public SFODataEPProfileViewUpdate dashboardType(String dashboardType) {
    this.dashboardType = dashboardType;
    return this;
  }

   /**
   * Get dashboardType
   * @return dashboardType
  **/
  public String getDashboardType() {
    return dashboardType;
  }

  public void setDashboardType(String dashboardType) {
    this.dashboardType = dashboardType;
  }

  public SFODataEPProfileViewUpdate liveProfilePhotoPermission(String liveProfilePhotoPermission) {
    this.liveProfilePhotoPermission = liveProfilePhotoPermission;
    return this;
  }

   /**
   * Get liveProfilePhotoPermission
   * @return liveProfilePhotoPermission
  **/
  public String getLiveProfilePhotoPermission() {
    return liveProfilePhotoPermission;
  }

  public void setLiveProfilePhotoPermission(String liveProfilePhotoPermission) {
    this.liveProfilePhotoPermission = liveProfilePhotoPermission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataEPProfileViewUpdate sfODataEPProfileViewUpdate = (SFODataEPProfileViewUpdate) o;
    return Objects.equals(this.dashboardTitle, sfODataEPProfileViewUpdate.dashboardTitle) &&
        Objects.equals(this.dashboardType, sfODataEPProfileViewUpdate.dashboardType) &&
        Objects.equals(this.liveProfilePhotoPermission, sfODataEPProfileViewUpdate.liveProfilePhotoPermission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dashboardTitle, dashboardType, liveProfilePhotoPermission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataEPProfileViewUpdate {\n");
    
    sb.append("    dashboardTitle: ").append(toIndentedString(dashboardTitle)).append("\n");
    sb.append("    dashboardType: ").append(toIndentedString(dashboardType)).append("\n");
    sb.append("    liveProfilePhotoPermission: ").append(toIndentedString(liveProfilePhotoPermission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
