/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataWfRequestParticipatorCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataWfRequestParticipatorCreate {
  @JsonProperty("actorType")
  private String actorType = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("ownerId")
  private String ownerId = null;

  @JsonProperty("participatorType")
  private String participatorType = null;

  @JsonProperty("processingOrder")
  private AnyOfSFODataWfRequestParticipatorCreateProcessingOrder processingOrder = null;

  @JsonProperty("relatedTo")
  private String relatedTo = null;

  @JsonProperty("roleId")
  private String roleId = null;

  @JsonProperty("wfRequestId")
  private AnyOfSFODataWfRequestParticipatorCreateWfRequestId wfRequestId = null;

  @JsonProperty("wfRequestParticipatorId")
  private AnyOfSFODataWfRequestParticipatorCreateWfRequestParticipatorId wfRequestParticipatorId = null;

  public SFODataWfRequestParticipatorCreate actorType(String actorType) {
    this.actorType = actorType;
    return this;
  }

   /**
   * Get actorType
   * @return actorType
  **/
  public String getActorType() {
    return actorType;
  }

  public void setActorType(String actorType) {
    this.actorType = actorType;
  }

  public SFODataWfRequestParticipatorCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataWfRequestParticipatorCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataWfRequestParticipatorCreate createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataWfRequestParticipatorCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataWfRequestParticipatorCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataWfRequestParticipatorCreate lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataWfRequestParticipatorCreate ownerId(String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }

  public SFODataWfRequestParticipatorCreate participatorType(String participatorType) {
    this.participatorType = participatorType;
    return this;
  }

   /**
   * Get participatorType
   * @return participatorType
  **/
  public String getParticipatorType() {
    return participatorType;
  }

  public void setParticipatorType(String participatorType) {
    this.participatorType = participatorType;
  }

  public SFODataWfRequestParticipatorCreate processingOrder(AnyOfSFODataWfRequestParticipatorCreateProcessingOrder processingOrder) {
    this.processingOrder = processingOrder;
    return this;
  }

   /**
   * Get processingOrder
   * @return processingOrder
  **/
  public AnyOfSFODataWfRequestParticipatorCreateProcessingOrder getProcessingOrder() {
    return processingOrder;
  }

  public void setProcessingOrder(AnyOfSFODataWfRequestParticipatorCreateProcessingOrder processingOrder) {
    this.processingOrder = processingOrder;
  }

  public SFODataWfRequestParticipatorCreate relatedTo(String relatedTo) {
    this.relatedTo = relatedTo;
    return this;
  }

   /**
   * Get relatedTo
   * @return relatedTo
  **/
  public String getRelatedTo() {
    return relatedTo;
  }

  public void setRelatedTo(String relatedTo) {
    this.relatedTo = relatedTo;
  }

  public SFODataWfRequestParticipatorCreate roleId(String roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * Get roleId
   * @return roleId
  **/
  public String getRoleId() {
    return roleId;
  }

  public void setRoleId(String roleId) {
    this.roleId = roleId;
  }

  public SFODataWfRequestParticipatorCreate wfRequestId(AnyOfSFODataWfRequestParticipatorCreateWfRequestId wfRequestId) {
    this.wfRequestId = wfRequestId;
    return this;
  }

   /**
   * Get wfRequestId
   * @return wfRequestId
  **/
  public AnyOfSFODataWfRequestParticipatorCreateWfRequestId getWfRequestId() {
    return wfRequestId;
  }

  public void setWfRequestId(AnyOfSFODataWfRequestParticipatorCreateWfRequestId wfRequestId) {
    this.wfRequestId = wfRequestId;
  }

  public SFODataWfRequestParticipatorCreate wfRequestParticipatorId(AnyOfSFODataWfRequestParticipatorCreateWfRequestParticipatorId wfRequestParticipatorId) {
    this.wfRequestParticipatorId = wfRequestParticipatorId;
    return this;
  }

   /**
   * Get wfRequestParticipatorId
   * @return wfRequestParticipatorId
  **/
  public AnyOfSFODataWfRequestParticipatorCreateWfRequestParticipatorId getWfRequestParticipatorId() {
    return wfRequestParticipatorId;
  }

  public void setWfRequestParticipatorId(AnyOfSFODataWfRequestParticipatorCreateWfRequestParticipatorId wfRequestParticipatorId) {
    this.wfRequestParticipatorId = wfRequestParticipatorId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataWfRequestParticipatorCreate sfODataWfRequestParticipatorCreate = (SFODataWfRequestParticipatorCreate) o;
    return Objects.equals(this.actorType, sfODataWfRequestParticipatorCreate.actorType) &&
        Objects.equals(this.createdBy, sfODataWfRequestParticipatorCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataWfRequestParticipatorCreate.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataWfRequestParticipatorCreate.createdOn) &&
        Objects.equals(this.lastModifiedBy, sfODataWfRequestParticipatorCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataWfRequestParticipatorCreate.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataWfRequestParticipatorCreate.lastModifiedOn) &&
        Objects.equals(this.ownerId, sfODataWfRequestParticipatorCreate.ownerId) &&
        Objects.equals(this.participatorType, sfODataWfRequestParticipatorCreate.participatorType) &&
        Objects.equals(this.processingOrder, sfODataWfRequestParticipatorCreate.processingOrder) &&
        Objects.equals(this.relatedTo, sfODataWfRequestParticipatorCreate.relatedTo) &&
        Objects.equals(this.roleId, sfODataWfRequestParticipatorCreate.roleId) &&
        Objects.equals(this.wfRequestId, sfODataWfRequestParticipatorCreate.wfRequestId) &&
        Objects.equals(this.wfRequestParticipatorId, sfODataWfRequestParticipatorCreate.wfRequestParticipatorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actorType, createdBy, createdDateTime, createdOn, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, ownerId, participatorType, processingOrder, relatedTo, roleId, wfRequestId, wfRequestParticipatorId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataWfRequestParticipatorCreate {\n");
    
    sb.append("    actorType: ").append(toIndentedString(actorType)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    participatorType: ").append(toIndentedString(participatorType)).append("\n");
    sb.append("    processingOrder: ").append(toIndentedString(processingOrder)).append("\n");
    sb.append("    relatedTo: ").append(toIndentedString(relatedTo)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    wfRequestId: ").append(toIndentedString(wfRequestId)).append("\n");
    sb.append("    wfRequestParticipatorId: ").append(toIndentedString(wfRequestParticipatorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
