/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataPerPerson;
import com.axonivy.connector.successfactors.connector.rest.SFODataPicklistOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataPerPersonal
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataPerPersonal {
  @JsonProperty("attachmentId")
  private String attachmentId = null;

  @JsonProperty("birthName")
  private String birthName = null;

  @JsonProperty("challengeStatus")
  private Boolean challengeStatus = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("customString9")
  private String customString9 = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("firstNameAlt1")
  private String firstNameAlt1 = null;

  @JsonProperty("formalName")
  private String formalName = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("includeAllRecords")
  private Boolean includeAllRecords = null;

  @JsonProperty("initials")
  private String initials = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("maritalStatus")
  private String maritalStatus = null;

  @JsonProperty("middleName")
  private String middleName = null;

  @JsonProperty("nameFormatCode")
  private String nameFormatCode = null;

  @JsonProperty("namePrefix")
  private String namePrefix = null;

  @JsonProperty("nationality")
  private String nationality = null;

  @JsonProperty("nativePreferredLang")
  private String nativePreferredLang = null;

  @JsonProperty("notes")
  private String notes = null;

  @JsonProperty("operation")
  private String operation = null;

  @JsonProperty("personIdExternal")
  private String personIdExternal = null;

  @JsonProperty("preferredName")
  private String preferredName = null;

  @JsonProperty("salutation")
  private String salutation = null;

  @JsonProperty("secondLastName")
  private String secondLastName = null;

  @JsonProperty("secondNationality")
  private String secondNationality = null;

  @JsonProperty("secondTitle")
  private String secondTitle = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("suffix")
  private String suffix = null;

  @JsonProperty("thirdNationality")
  private String thirdNationality = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("localNavAUT")
  private AllOfSFODataPerPersonalLocalNavAUT localNavAUT = null;

  @JsonProperty("localNavBEL")
  private AllOfSFODataPerPersonalLocalNavBEL localNavBEL = null;

  @JsonProperty("localNavCHE")
  private AllOfSFODataPerPersonalLocalNavCHE localNavCHE = null;

  @JsonProperty("localNavDEU")
  private AllOfSFODataPerPersonalLocalNavDEU localNavDEU = null;

  @JsonProperty("localNavDNK")
  private AllOfSFODataPerPersonalLocalNavDNK localNavDNK = null;

  @JsonProperty("localNavESP")
  private AllOfSFODataPerPersonalLocalNavESP localNavESP = null;

  @JsonProperty("localNavFIN")
  private AllOfSFODataPerPersonalLocalNavFIN localNavFIN = null;

  @JsonProperty("localNavFRA")
  private AllOfSFODataPerPersonalLocalNavFRA localNavFRA = null;

  @JsonProperty("localNavGBR")
  private AllOfSFODataPerPersonalLocalNavGBR localNavGBR = null;

  @JsonProperty("localNavHUN")
  private AllOfSFODataPerPersonalLocalNavHUN localNavHUN = null;

  @JsonProperty("localNavIRL")
  private AllOfSFODataPerPersonalLocalNavIRL localNavIRL = null;

  @JsonProperty("localNavITA")
  private AllOfSFODataPerPersonalLocalNavITA localNavITA = null;

  @JsonProperty("localNavLUX")
  private AllOfSFODataPerPersonalLocalNavLUX localNavLUX = null;

  @JsonProperty("localNavNLD")
  private AllOfSFODataPerPersonalLocalNavNLD localNavNLD = null;

  @JsonProperty("localNavNOR")
  private AllOfSFODataPerPersonalLocalNavNOR localNavNOR = null;

  @JsonProperty("localNavPOL")
  private AllOfSFODataPerPersonalLocalNavPOL localNavPOL = null;

  @JsonProperty("localNavPRT")
  private AllOfSFODataPerPersonalLocalNavPRT localNavPRT = null;

  @JsonProperty("localNavSWE")
  private AllOfSFODataPerPersonalLocalNavSWE localNavSWE = null;

  @JsonProperty("localNavZAF")
  private AllOfSFODataPerPersonalLocalNavZAF localNavZAF = null;

  @JsonProperty("maritalStatusNav")
  private SFODataPicklistOption maritalStatusNav = null;

  @JsonProperty("nameFormatCodeNav")
  private AllOfSFODataPerPersonalNameFormatCodeNav nameFormatCodeNav = null;

  @JsonProperty("namePrefixNav")
  private SFODataPicklistOption namePrefixNav = null;

  @JsonProperty("nativePreferredLangNav")
  private SFODataPicklistOption nativePreferredLangNav = null;

  @JsonProperty("personNav")
  private SFODataPerPerson personNav = null;

  @JsonProperty("salutationNav")
  private SFODataPicklistOption salutationNav = null;

  @JsonProperty("secondTitleNav")
  private SFODataPicklistOption secondTitleNav = null;

  @JsonProperty("suffixNav")
  private SFODataPicklistOption suffixNav = null;

  @JsonProperty("titleNav")
  private SFODataPicklistOption titleNav = null;

  @JsonProperty("wfRequestNav")
  private AllOfSFODataPerPersonalWfRequestNav wfRequestNav = null;

  public SFODataPerPersonal attachmentId(String attachmentId) {
    this.attachmentId = attachmentId;
    return this;
  }

   /**
   * Get attachmentId
   * @return attachmentId
  **/
  public String getAttachmentId() {
    return attachmentId;
  }

  public void setAttachmentId(String attachmentId) {
    this.attachmentId = attachmentId;
  }

  public SFODataPerPersonal birthName(String birthName) {
    this.birthName = birthName;
    return this;
  }

   /**
   * Get birthName
   * @return birthName
  **/
  public String getBirthName() {
    return birthName;
  }

  public void setBirthName(String birthName) {
    this.birthName = birthName;
  }

  public SFODataPerPersonal challengeStatus(Boolean challengeStatus) {
    this.challengeStatus = challengeStatus;
    return this;
  }

   /**
   * Get challengeStatus
   * @return challengeStatus
  **/
  public Boolean isChallengeStatus() {
    return challengeStatus;
  }

  public void setChallengeStatus(Boolean challengeStatus) {
    this.challengeStatus = challengeStatus;
  }

  public SFODataPerPersonal createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataPerPersonal createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataPerPersonal createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataPerPersonal customString9(String customString9) {
    this.customString9 = customString9;
    return this;
  }

   /**
   * Get customString9
   * @return customString9
  **/
  public String getCustomString9() {
    return customString9;
  }

  public void setCustomString9(String customString9) {
    this.customString9 = customString9;
  }

  public SFODataPerPersonal endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataPerPersonal firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public SFODataPerPersonal firstNameAlt1(String firstNameAlt1) {
    this.firstNameAlt1 = firstNameAlt1;
    return this;
  }

   /**
   * Get firstNameAlt1
   * @return firstNameAlt1
  **/
  public String getFirstNameAlt1() {
    return firstNameAlt1;
  }

  public void setFirstNameAlt1(String firstNameAlt1) {
    this.firstNameAlt1 = firstNameAlt1;
  }

  public SFODataPerPersonal formalName(String formalName) {
    this.formalName = formalName;
    return this;
  }

   /**
   * Get formalName
   * @return formalName
  **/
  public String getFormalName() {
    return formalName;
  }

  public void setFormalName(String formalName) {
    this.formalName = formalName;
  }

  public SFODataPerPersonal gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public SFODataPerPersonal includeAllRecords(Boolean includeAllRecords) {
    this.includeAllRecords = includeAllRecords;
    return this;
  }

   /**
   * Get includeAllRecords
   * @return includeAllRecords
  **/
  public Boolean isIncludeAllRecords() {
    return includeAllRecords;
  }

  public void setIncludeAllRecords(Boolean includeAllRecords) {
    this.includeAllRecords = includeAllRecords;
  }

  public SFODataPerPersonal initials(String initials) {
    this.initials = initials;
    return this;
  }

   /**
   * Get initials
   * @return initials
  **/
  public String getInitials() {
    return initials;
  }

  public void setInitials(String initials) {
    this.initials = initials;
  }

  public SFODataPerPersonal lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataPerPersonal lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataPerPersonal lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataPerPersonal lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public SFODataPerPersonal maritalStatus(String maritalStatus) {
    this.maritalStatus = maritalStatus;
    return this;
  }

   /**
   * Get maritalStatus
   * @return maritalStatus
  **/
  public String getMaritalStatus() {
    return maritalStatus;
  }

  public void setMaritalStatus(String maritalStatus) {
    this.maritalStatus = maritalStatus;
  }

  public SFODataPerPersonal middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public SFODataPerPersonal nameFormatCode(String nameFormatCode) {
    this.nameFormatCode = nameFormatCode;
    return this;
  }

   /**
   * Get nameFormatCode
   * @return nameFormatCode
  **/
  public String getNameFormatCode() {
    return nameFormatCode;
  }

  public void setNameFormatCode(String nameFormatCode) {
    this.nameFormatCode = nameFormatCode;
  }

  public SFODataPerPersonal namePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
    return this;
  }

   /**
   * Get namePrefix
   * @return namePrefix
  **/
  public String getNamePrefix() {
    return namePrefix;
  }

  public void setNamePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
  }

  public SFODataPerPersonal nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public SFODataPerPersonal nativePreferredLang(String nativePreferredLang) {
    this.nativePreferredLang = nativePreferredLang;
    return this;
  }

   /**
   * Get nativePreferredLang
   * @return nativePreferredLang
  **/
  public String getNativePreferredLang() {
    return nativePreferredLang;
  }

  public void setNativePreferredLang(String nativePreferredLang) {
    this.nativePreferredLang = nativePreferredLang;
  }

  public SFODataPerPersonal notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public SFODataPerPersonal operation(String operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public SFODataPerPersonal personIdExternal(String personIdExternal) {
    this.personIdExternal = personIdExternal;
    return this;
  }

   /**
   * Get personIdExternal
   * @return personIdExternal
  **/
  public String getPersonIdExternal() {
    return personIdExternal;
  }

  public void setPersonIdExternal(String personIdExternal) {
    this.personIdExternal = personIdExternal;
  }

  public SFODataPerPersonal preferredName(String preferredName) {
    this.preferredName = preferredName;
    return this;
  }

   /**
   * Get preferredName
   * @return preferredName
  **/
  public String getPreferredName() {
    return preferredName;
  }

  public void setPreferredName(String preferredName) {
    this.preferredName = preferredName;
  }

  public SFODataPerPersonal salutation(String salutation) {
    this.salutation = salutation;
    return this;
  }

   /**
   * Get salutation
   * @return salutation
  **/
  public String getSalutation() {
    return salutation;
  }

  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  public SFODataPerPersonal secondLastName(String secondLastName) {
    this.secondLastName = secondLastName;
    return this;
  }

   /**
   * Get secondLastName
   * @return secondLastName
  **/
  public String getSecondLastName() {
    return secondLastName;
  }

  public void setSecondLastName(String secondLastName) {
    this.secondLastName = secondLastName;
  }

  public SFODataPerPersonal secondNationality(String secondNationality) {
    this.secondNationality = secondNationality;
    return this;
  }

   /**
   * Get secondNationality
   * @return secondNationality
  **/
  public String getSecondNationality() {
    return secondNationality;
  }

  public void setSecondNationality(String secondNationality) {
    this.secondNationality = secondNationality;
  }

  public SFODataPerPersonal secondTitle(String secondTitle) {
    this.secondTitle = secondTitle;
    return this;
  }

   /**
   * Get secondTitle
   * @return secondTitle
  **/
  public String getSecondTitle() {
    return secondTitle;
  }

  public void setSecondTitle(String secondTitle) {
    this.secondTitle = secondTitle;
  }

  public SFODataPerPersonal startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SFODataPerPersonal suffix(String suffix) {
    this.suffix = suffix;
    return this;
  }

   /**
   * Get suffix
   * @return suffix
  **/
  public String getSuffix() {
    return suffix;
  }

  public void setSuffix(String suffix) {
    this.suffix = suffix;
  }

  public SFODataPerPersonal thirdNationality(String thirdNationality) {
    this.thirdNationality = thirdNationality;
    return this;
  }

   /**
   * Get thirdNationality
   * @return thirdNationality
  **/
  public String getThirdNationality() {
    return thirdNationality;
  }

  public void setThirdNationality(String thirdNationality) {
    this.thirdNationality = thirdNationality;
  }

  public SFODataPerPersonal title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SFODataPerPersonal localNavAUT(AllOfSFODataPerPersonalLocalNavAUT localNavAUT) {
    this.localNavAUT = localNavAUT;
    return this;
  }

   /**
   * Get localNavAUT
   * @return localNavAUT
  **/
  public AllOfSFODataPerPersonalLocalNavAUT getLocalNavAUT() {
    return localNavAUT;
  }

  public void setLocalNavAUT(AllOfSFODataPerPersonalLocalNavAUT localNavAUT) {
    this.localNavAUT = localNavAUT;
  }

  public SFODataPerPersonal localNavBEL(AllOfSFODataPerPersonalLocalNavBEL localNavBEL) {
    this.localNavBEL = localNavBEL;
    return this;
  }

   /**
   * Get localNavBEL
   * @return localNavBEL
  **/
  public AllOfSFODataPerPersonalLocalNavBEL getLocalNavBEL() {
    return localNavBEL;
  }

  public void setLocalNavBEL(AllOfSFODataPerPersonalLocalNavBEL localNavBEL) {
    this.localNavBEL = localNavBEL;
  }

  public SFODataPerPersonal localNavCHE(AllOfSFODataPerPersonalLocalNavCHE localNavCHE) {
    this.localNavCHE = localNavCHE;
    return this;
  }

   /**
   * Get localNavCHE
   * @return localNavCHE
  **/
  public AllOfSFODataPerPersonalLocalNavCHE getLocalNavCHE() {
    return localNavCHE;
  }

  public void setLocalNavCHE(AllOfSFODataPerPersonalLocalNavCHE localNavCHE) {
    this.localNavCHE = localNavCHE;
  }

  public SFODataPerPersonal localNavDEU(AllOfSFODataPerPersonalLocalNavDEU localNavDEU) {
    this.localNavDEU = localNavDEU;
    return this;
  }

   /**
   * Get localNavDEU
   * @return localNavDEU
  **/
  public AllOfSFODataPerPersonalLocalNavDEU getLocalNavDEU() {
    return localNavDEU;
  }

  public void setLocalNavDEU(AllOfSFODataPerPersonalLocalNavDEU localNavDEU) {
    this.localNavDEU = localNavDEU;
  }

  public SFODataPerPersonal localNavDNK(AllOfSFODataPerPersonalLocalNavDNK localNavDNK) {
    this.localNavDNK = localNavDNK;
    return this;
  }

   /**
   * Get localNavDNK
   * @return localNavDNK
  **/
  public AllOfSFODataPerPersonalLocalNavDNK getLocalNavDNK() {
    return localNavDNK;
  }

  public void setLocalNavDNK(AllOfSFODataPerPersonalLocalNavDNK localNavDNK) {
    this.localNavDNK = localNavDNK;
  }

  public SFODataPerPersonal localNavESP(AllOfSFODataPerPersonalLocalNavESP localNavESP) {
    this.localNavESP = localNavESP;
    return this;
  }

   /**
   * Get localNavESP
   * @return localNavESP
  **/
  public AllOfSFODataPerPersonalLocalNavESP getLocalNavESP() {
    return localNavESP;
  }

  public void setLocalNavESP(AllOfSFODataPerPersonalLocalNavESP localNavESP) {
    this.localNavESP = localNavESP;
  }

  public SFODataPerPersonal localNavFIN(AllOfSFODataPerPersonalLocalNavFIN localNavFIN) {
    this.localNavFIN = localNavFIN;
    return this;
  }

   /**
   * Get localNavFIN
   * @return localNavFIN
  **/
  public AllOfSFODataPerPersonalLocalNavFIN getLocalNavFIN() {
    return localNavFIN;
  }

  public void setLocalNavFIN(AllOfSFODataPerPersonalLocalNavFIN localNavFIN) {
    this.localNavFIN = localNavFIN;
  }

  public SFODataPerPersonal localNavFRA(AllOfSFODataPerPersonalLocalNavFRA localNavFRA) {
    this.localNavFRA = localNavFRA;
    return this;
  }

   /**
   * Get localNavFRA
   * @return localNavFRA
  **/
  public AllOfSFODataPerPersonalLocalNavFRA getLocalNavFRA() {
    return localNavFRA;
  }

  public void setLocalNavFRA(AllOfSFODataPerPersonalLocalNavFRA localNavFRA) {
    this.localNavFRA = localNavFRA;
  }

  public SFODataPerPersonal localNavGBR(AllOfSFODataPerPersonalLocalNavGBR localNavGBR) {
    this.localNavGBR = localNavGBR;
    return this;
  }

   /**
   * Get localNavGBR
   * @return localNavGBR
  **/
  public AllOfSFODataPerPersonalLocalNavGBR getLocalNavGBR() {
    return localNavGBR;
  }

  public void setLocalNavGBR(AllOfSFODataPerPersonalLocalNavGBR localNavGBR) {
    this.localNavGBR = localNavGBR;
  }

  public SFODataPerPersonal localNavHUN(AllOfSFODataPerPersonalLocalNavHUN localNavHUN) {
    this.localNavHUN = localNavHUN;
    return this;
  }

   /**
   * Get localNavHUN
   * @return localNavHUN
  **/
  public AllOfSFODataPerPersonalLocalNavHUN getLocalNavHUN() {
    return localNavHUN;
  }

  public void setLocalNavHUN(AllOfSFODataPerPersonalLocalNavHUN localNavHUN) {
    this.localNavHUN = localNavHUN;
  }

  public SFODataPerPersonal localNavIRL(AllOfSFODataPerPersonalLocalNavIRL localNavIRL) {
    this.localNavIRL = localNavIRL;
    return this;
  }

   /**
   * Get localNavIRL
   * @return localNavIRL
  **/
  public AllOfSFODataPerPersonalLocalNavIRL getLocalNavIRL() {
    return localNavIRL;
  }

  public void setLocalNavIRL(AllOfSFODataPerPersonalLocalNavIRL localNavIRL) {
    this.localNavIRL = localNavIRL;
  }

  public SFODataPerPersonal localNavITA(AllOfSFODataPerPersonalLocalNavITA localNavITA) {
    this.localNavITA = localNavITA;
    return this;
  }

   /**
   * Get localNavITA
   * @return localNavITA
  **/
  public AllOfSFODataPerPersonalLocalNavITA getLocalNavITA() {
    return localNavITA;
  }

  public void setLocalNavITA(AllOfSFODataPerPersonalLocalNavITA localNavITA) {
    this.localNavITA = localNavITA;
  }

  public SFODataPerPersonal localNavLUX(AllOfSFODataPerPersonalLocalNavLUX localNavLUX) {
    this.localNavLUX = localNavLUX;
    return this;
  }

   /**
   * Get localNavLUX
   * @return localNavLUX
  **/
  public AllOfSFODataPerPersonalLocalNavLUX getLocalNavLUX() {
    return localNavLUX;
  }

  public void setLocalNavLUX(AllOfSFODataPerPersonalLocalNavLUX localNavLUX) {
    this.localNavLUX = localNavLUX;
  }

  public SFODataPerPersonal localNavNLD(AllOfSFODataPerPersonalLocalNavNLD localNavNLD) {
    this.localNavNLD = localNavNLD;
    return this;
  }

   /**
   * Get localNavNLD
   * @return localNavNLD
  **/
  public AllOfSFODataPerPersonalLocalNavNLD getLocalNavNLD() {
    return localNavNLD;
  }

  public void setLocalNavNLD(AllOfSFODataPerPersonalLocalNavNLD localNavNLD) {
    this.localNavNLD = localNavNLD;
  }

  public SFODataPerPersonal localNavNOR(AllOfSFODataPerPersonalLocalNavNOR localNavNOR) {
    this.localNavNOR = localNavNOR;
    return this;
  }

   /**
   * Get localNavNOR
   * @return localNavNOR
  **/
  public AllOfSFODataPerPersonalLocalNavNOR getLocalNavNOR() {
    return localNavNOR;
  }

  public void setLocalNavNOR(AllOfSFODataPerPersonalLocalNavNOR localNavNOR) {
    this.localNavNOR = localNavNOR;
  }

  public SFODataPerPersonal localNavPOL(AllOfSFODataPerPersonalLocalNavPOL localNavPOL) {
    this.localNavPOL = localNavPOL;
    return this;
  }

   /**
   * Get localNavPOL
   * @return localNavPOL
  **/
  public AllOfSFODataPerPersonalLocalNavPOL getLocalNavPOL() {
    return localNavPOL;
  }

  public void setLocalNavPOL(AllOfSFODataPerPersonalLocalNavPOL localNavPOL) {
    this.localNavPOL = localNavPOL;
  }

  public SFODataPerPersonal localNavPRT(AllOfSFODataPerPersonalLocalNavPRT localNavPRT) {
    this.localNavPRT = localNavPRT;
    return this;
  }

   /**
   * Get localNavPRT
   * @return localNavPRT
  **/
  public AllOfSFODataPerPersonalLocalNavPRT getLocalNavPRT() {
    return localNavPRT;
  }

  public void setLocalNavPRT(AllOfSFODataPerPersonalLocalNavPRT localNavPRT) {
    this.localNavPRT = localNavPRT;
  }

  public SFODataPerPersonal localNavSWE(AllOfSFODataPerPersonalLocalNavSWE localNavSWE) {
    this.localNavSWE = localNavSWE;
    return this;
  }

   /**
   * Get localNavSWE
   * @return localNavSWE
  **/
  public AllOfSFODataPerPersonalLocalNavSWE getLocalNavSWE() {
    return localNavSWE;
  }

  public void setLocalNavSWE(AllOfSFODataPerPersonalLocalNavSWE localNavSWE) {
    this.localNavSWE = localNavSWE;
  }

  public SFODataPerPersonal localNavZAF(AllOfSFODataPerPersonalLocalNavZAF localNavZAF) {
    this.localNavZAF = localNavZAF;
    return this;
  }

   /**
   * Get localNavZAF
   * @return localNavZAF
  **/
  public AllOfSFODataPerPersonalLocalNavZAF getLocalNavZAF() {
    return localNavZAF;
  }

  public void setLocalNavZAF(AllOfSFODataPerPersonalLocalNavZAF localNavZAF) {
    this.localNavZAF = localNavZAF;
  }

  public SFODataPerPersonal maritalStatusNav(SFODataPicklistOption maritalStatusNav) {
    this.maritalStatusNav = maritalStatusNav;
    return this;
  }

   /**
   * Get maritalStatusNav
   * @return maritalStatusNav
  **/
  public SFODataPicklistOption getMaritalStatusNav() {
    return maritalStatusNav;
  }

  public void setMaritalStatusNav(SFODataPicklistOption maritalStatusNav) {
    this.maritalStatusNav = maritalStatusNav;
  }

  public SFODataPerPersonal nameFormatCodeNav(AllOfSFODataPerPersonalNameFormatCodeNav nameFormatCodeNav) {
    this.nameFormatCodeNav = nameFormatCodeNav;
    return this;
  }

   /**
   * Get nameFormatCodeNav
   * @return nameFormatCodeNav
  **/
  public AllOfSFODataPerPersonalNameFormatCodeNav getNameFormatCodeNav() {
    return nameFormatCodeNav;
  }

  public void setNameFormatCodeNav(AllOfSFODataPerPersonalNameFormatCodeNav nameFormatCodeNav) {
    this.nameFormatCodeNav = nameFormatCodeNav;
  }

  public SFODataPerPersonal namePrefixNav(SFODataPicklistOption namePrefixNav) {
    this.namePrefixNav = namePrefixNav;
    return this;
  }

   /**
   * Get namePrefixNav
   * @return namePrefixNav
  **/
  public SFODataPicklistOption getNamePrefixNav() {
    return namePrefixNav;
  }

  public void setNamePrefixNav(SFODataPicklistOption namePrefixNav) {
    this.namePrefixNav = namePrefixNav;
  }

  public SFODataPerPersonal nativePreferredLangNav(SFODataPicklistOption nativePreferredLangNav) {
    this.nativePreferredLangNav = nativePreferredLangNav;
    return this;
  }

   /**
   * Get nativePreferredLangNav
   * @return nativePreferredLangNav
  **/
  public SFODataPicklistOption getNativePreferredLangNav() {
    return nativePreferredLangNav;
  }

  public void setNativePreferredLangNav(SFODataPicklistOption nativePreferredLangNav) {
    this.nativePreferredLangNav = nativePreferredLangNav;
  }

  public SFODataPerPersonal personNav(SFODataPerPerson personNav) {
    this.personNav = personNav;
    return this;
  }

   /**
   * Get personNav
   * @return personNav
  **/
  public SFODataPerPerson getPersonNav() {
    return personNav;
  }

  public void setPersonNav(SFODataPerPerson personNav) {
    this.personNav = personNav;
  }

  public SFODataPerPersonal salutationNav(SFODataPicklistOption salutationNav) {
    this.salutationNav = salutationNav;
    return this;
  }

   /**
   * Get salutationNav
   * @return salutationNav
  **/
  public SFODataPicklistOption getSalutationNav() {
    return salutationNav;
  }

  public void setSalutationNav(SFODataPicklistOption salutationNav) {
    this.salutationNav = salutationNav;
  }

  public SFODataPerPersonal secondTitleNav(SFODataPicklistOption secondTitleNav) {
    this.secondTitleNav = secondTitleNav;
    return this;
  }

   /**
   * Get secondTitleNav
   * @return secondTitleNav
  **/
  public SFODataPicklistOption getSecondTitleNav() {
    return secondTitleNav;
  }

  public void setSecondTitleNav(SFODataPicklistOption secondTitleNav) {
    this.secondTitleNav = secondTitleNav;
  }

  public SFODataPerPersonal suffixNav(SFODataPicklistOption suffixNav) {
    this.suffixNav = suffixNav;
    return this;
  }

   /**
   * Get suffixNav
   * @return suffixNav
  **/
  public SFODataPicklistOption getSuffixNav() {
    return suffixNav;
  }

  public void setSuffixNav(SFODataPicklistOption suffixNav) {
    this.suffixNav = suffixNav;
  }

  public SFODataPerPersonal titleNav(SFODataPicklistOption titleNav) {
    this.titleNav = titleNav;
    return this;
  }

   /**
   * Get titleNav
   * @return titleNav
  **/
  public SFODataPicklistOption getTitleNav() {
    return titleNav;
  }

  public void setTitleNav(SFODataPicklistOption titleNav) {
    this.titleNav = titleNav;
  }

  public SFODataPerPersonal wfRequestNav(AllOfSFODataPerPersonalWfRequestNav wfRequestNav) {
    this.wfRequestNav = wfRequestNav;
    return this;
  }

   /**
   * Get wfRequestNav
   * @return wfRequestNav
  **/
  public AllOfSFODataPerPersonalWfRequestNav getWfRequestNav() {
    return wfRequestNav;
  }

  public void setWfRequestNav(AllOfSFODataPerPersonalWfRequestNav wfRequestNav) {
    this.wfRequestNav = wfRequestNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataPerPersonal sfODataPerPersonal = (SFODataPerPersonal) o;
    return Objects.equals(this.attachmentId, sfODataPerPersonal.attachmentId) &&
        Objects.equals(this.birthName, sfODataPerPersonal.birthName) &&
        Objects.equals(this.challengeStatus, sfODataPerPersonal.challengeStatus) &&
        Objects.equals(this.createdBy, sfODataPerPersonal.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataPerPersonal.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataPerPersonal.createdOn) &&
        Objects.equals(this.customString9, sfODataPerPersonal.customString9) &&
        Objects.equals(this.endDate, sfODataPerPersonal.endDate) &&
        Objects.equals(this.firstName, sfODataPerPersonal.firstName) &&
        Objects.equals(this.firstNameAlt1, sfODataPerPersonal.firstNameAlt1) &&
        Objects.equals(this.formalName, sfODataPerPersonal.formalName) &&
        Objects.equals(this.gender, sfODataPerPersonal.gender) &&
        Objects.equals(this.includeAllRecords, sfODataPerPersonal.includeAllRecords) &&
        Objects.equals(this.initials, sfODataPerPersonal.initials) &&
        Objects.equals(this.lastModifiedBy, sfODataPerPersonal.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataPerPersonal.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataPerPersonal.lastModifiedOn) &&
        Objects.equals(this.lastName, sfODataPerPersonal.lastName) &&
        Objects.equals(this.maritalStatus, sfODataPerPersonal.maritalStatus) &&
        Objects.equals(this.middleName, sfODataPerPersonal.middleName) &&
        Objects.equals(this.nameFormatCode, sfODataPerPersonal.nameFormatCode) &&
        Objects.equals(this.namePrefix, sfODataPerPersonal.namePrefix) &&
        Objects.equals(this.nationality, sfODataPerPersonal.nationality) &&
        Objects.equals(this.nativePreferredLang, sfODataPerPersonal.nativePreferredLang) &&
        Objects.equals(this.notes, sfODataPerPersonal.notes) &&
        Objects.equals(this.operation, sfODataPerPersonal.operation) &&
        Objects.equals(this.personIdExternal, sfODataPerPersonal.personIdExternal) &&
        Objects.equals(this.preferredName, sfODataPerPersonal.preferredName) &&
        Objects.equals(this.salutation, sfODataPerPersonal.salutation) &&
        Objects.equals(this.secondLastName, sfODataPerPersonal.secondLastName) &&
        Objects.equals(this.secondNationality, sfODataPerPersonal.secondNationality) &&
        Objects.equals(this.secondTitle, sfODataPerPersonal.secondTitle) &&
        Objects.equals(this.startDate, sfODataPerPersonal.startDate) &&
        Objects.equals(this.suffix, sfODataPerPersonal.suffix) &&
        Objects.equals(this.thirdNationality, sfODataPerPersonal.thirdNationality) &&
        Objects.equals(this.title, sfODataPerPersonal.title) &&
        Objects.equals(this.localNavAUT, sfODataPerPersonal.localNavAUT) &&
        Objects.equals(this.localNavBEL, sfODataPerPersonal.localNavBEL) &&
        Objects.equals(this.localNavCHE, sfODataPerPersonal.localNavCHE) &&
        Objects.equals(this.localNavDEU, sfODataPerPersonal.localNavDEU) &&
        Objects.equals(this.localNavDNK, sfODataPerPersonal.localNavDNK) &&
        Objects.equals(this.localNavESP, sfODataPerPersonal.localNavESP) &&
        Objects.equals(this.localNavFIN, sfODataPerPersonal.localNavFIN) &&
        Objects.equals(this.localNavFRA, sfODataPerPersonal.localNavFRA) &&
        Objects.equals(this.localNavGBR, sfODataPerPersonal.localNavGBR) &&
        Objects.equals(this.localNavHUN, sfODataPerPersonal.localNavHUN) &&
        Objects.equals(this.localNavIRL, sfODataPerPersonal.localNavIRL) &&
        Objects.equals(this.localNavITA, sfODataPerPersonal.localNavITA) &&
        Objects.equals(this.localNavLUX, sfODataPerPersonal.localNavLUX) &&
        Objects.equals(this.localNavNLD, sfODataPerPersonal.localNavNLD) &&
        Objects.equals(this.localNavNOR, sfODataPerPersonal.localNavNOR) &&
        Objects.equals(this.localNavPOL, sfODataPerPersonal.localNavPOL) &&
        Objects.equals(this.localNavPRT, sfODataPerPersonal.localNavPRT) &&
        Objects.equals(this.localNavSWE, sfODataPerPersonal.localNavSWE) &&
        Objects.equals(this.localNavZAF, sfODataPerPersonal.localNavZAF) &&
        Objects.equals(this.maritalStatusNav, sfODataPerPersonal.maritalStatusNav) &&
        Objects.equals(this.nameFormatCodeNav, sfODataPerPersonal.nameFormatCodeNav) &&
        Objects.equals(this.namePrefixNav, sfODataPerPersonal.namePrefixNav) &&
        Objects.equals(this.nativePreferredLangNav, sfODataPerPersonal.nativePreferredLangNav) &&
        Objects.equals(this.personNav, sfODataPerPersonal.personNav) &&
        Objects.equals(this.salutationNav, sfODataPerPersonal.salutationNav) &&
        Objects.equals(this.secondTitleNav, sfODataPerPersonal.secondTitleNav) &&
        Objects.equals(this.suffixNav, sfODataPerPersonal.suffixNav) &&
        Objects.equals(this.titleNav, sfODataPerPersonal.titleNav) &&
        Objects.equals(this.wfRequestNav, sfODataPerPersonal.wfRequestNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachmentId, birthName, challengeStatus, createdBy, createdDateTime, createdOn, customString9, endDate, firstName, firstNameAlt1, formalName, gender, includeAllRecords, initials, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, lastName, maritalStatus, middleName, nameFormatCode, namePrefix, nationality, nativePreferredLang, notes, operation, personIdExternal, preferredName, salutation, secondLastName, secondNationality, secondTitle, startDate, suffix, thirdNationality, title, localNavAUT, localNavBEL, localNavCHE, localNavDEU, localNavDNK, localNavESP, localNavFIN, localNavFRA, localNavGBR, localNavHUN, localNavIRL, localNavITA, localNavLUX, localNavNLD, localNavNOR, localNavPOL, localNavPRT, localNavSWE, localNavZAF, maritalStatusNav, nameFormatCodeNav, namePrefixNav, nativePreferredLangNav, personNav, salutationNav, secondTitleNav, suffixNav, titleNav, wfRequestNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataPerPersonal {\n");
    
    sb.append("    attachmentId: ").append(toIndentedString(attachmentId)).append("\n");
    sb.append("    birthName: ").append(toIndentedString(birthName)).append("\n");
    sb.append("    challengeStatus: ").append(toIndentedString(challengeStatus)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    customString9: ").append(toIndentedString(customString9)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    firstNameAlt1: ").append(toIndentedString(firstNameAlt1)).append("\n");
    sb.append("    formalName: ").append(toIndentedString(formalName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    includeAllRecords: ").append(toIndentedString(includeAllRecords)).append("\n");
    sb.append("    initials: ").append(toIndentedString(initials)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    maritalStatus: ").append(toIndentedString(maritalStatus)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    nameFormatCode: ").append(toIndentedString(nameFormatCode)).append("\n");
    sb.append("    namePrefix: ").append(toIndentedString(namePrefix)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    nativePreferredLang: ").append(toIndentedString(nativePreferredLang)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    personIdExternal: ").append(toIndentedString(personIdExternal)).append("\n");
    sb.append("    preferredName: ").append(toIndentedString(preferredName)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    secondLastName: ").append(toIndentedString(secondLastName)).append("\n");
    sb.append("    secondNationality: ").append(toIndentedString(secondNationality)).append("\n");
    sb.append("    secondTitle: ").append(toIndentedString(secondTitle)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    thirdNationality: ").append(toIndentedString(thirdNationality)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    localNavAUT: ").append(toIndentedString(localNavAUT)).append("\n");
    sb.append("    localNavBEL: ").append(toIndentedString(localNavBEL)).append("\n");
    sb.append("    localNavCHE: ").append(toIndentedString(localNavCHE)).append("\n");
    sb.append("    localNavDEU: ").append(toIndentedString(localNavDEU)).append("\n");
    sb.append("    localNavDNK: ").append(toIndentedString(localNavDNK)).append("\n");
    sb.append("    localNavESP: ").append(toIndentedString(localNavESP)).append("\n");
    sb.append("    localNavFIN: ").append(toIndentedString(localNavFIN)).append("\n");
    sb.append("    localNavFRA: ").append(toIndentedString(localNavFRA)).append("\n");
    sb.append("    localNavGBR: ").append(toIndentedString(localNavGBR)).append("\n");
    sb.append("    localNavHUN: ").append(toIndentedString(localNavHUN)).append("\n");
    sb.append("    localNavIRL: ").append(toIndentedString(localNavIRL)).append("\n");
    sb.append("    localNavITA: ").append(toIndentedString(localNavITA)).append("\n");
    sb.append("    localNavLUX: ").append(toIndentedString(localNavLUX)).append("\n");
    sb.append("    localNavNLD: ").append(toIndentedString(localNavNLD)).append("\n");
    sb.append("    localNavNOR: ").append(toIndentedString(localNavNOR)).append("\n");
    sb.append("    localNavPOL: ").append(toIndentedString(localNavPOL)).append("\n");
    sb.append("    localNavPRT: ").append(toIndentedString(localNavPRT)).append("\n");
    sb.append("    localNavSWE: ").append(toIndentedString(localNavSWE)).append("\n");
    sb.append("    localNavZAF: ").append(toIndentedString(localNavZAF)).append("\n");
    sb.append("    maritalStatusNav: ").append(toIndentedString(maritalStatusNav)).append("\n");
    sb.append("    nameFormatCodeNav: ").append(toIndentedString(nameFormatCodeNav)).append("\n");
    sb.append("    namePrefixNav: ").append(toIndentedString(namePrefixNav)).append("\n");
    sb.append("    nativePreferredLangNav: ").append(toIndentedString(nativePreferredLangNav)).append("\n");
    sb.append("    personNav: ").append(toIndentedString(personNav)).append("\n");
    sb.append("    salutationNav: ").append(toIndentedString(salutationNav)).append("\n");
    sb.append("    secondTitleNav: ").append(toIndentedString(secondTitleNav)).append("\n");
    sb.append("    suffixNav: ").append(toIndentedString(suffixNav)).append("\n");
    sb.append("    titleNav: ").append(toIndentedString(titleNav)).append("\n");
    sb.append("    wfRequestNav: ").append(toIndentedString(wfRequestNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
