/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataAccrualCalculationBaseCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataAccrualCalculationBaseCreate {
  @JsonProperty("actualQuantity")
  private AnyOfSFODataAccrualCalculationBaseCreateActualQuantity actualQuantity = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("date")
  private OffsetDateTime date = null;

  @JsonProperty("entityUUID")
  private String entityUUID = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("quantity1")
  private AnyOfSFODataAccrualCalculationBaseCreateQuantity1 quantity1 = null;

  @JsonProperty("quantity2")
  private AnyOfSFODataAccrualCalculationBaseCreateQuantity2 quantity2 = null;

  @JsonProperty("quantity3")
  private AnyOfSFODataAccrualCalculationBaseCreateQuantity3 quantity3 = null;

  @JsonProperty("quantity4")
  private AnyOfSFODataAccrualCalculationBaseCreateQuantity4 quantity4 = null;

  @JsonProperty("quantity5")
  private AnyOfSFODataAccrualCalculationBaseCreateQuantity5 quantity5 = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  @JsonProperty("userIdNav@odata.bind")
  private String userIdNavAtOdataBind = null;

  public SFODataAccrualCalculationBaseCreate actualQuantity(AnyOfSFODataAccrualCalculationBaseCreateActualQuantity actualQuantity) {
    this.actualQuantity = actualQuantity;
    return this;
  }

   /**
   * Get actualQuantity
   * @return actualQuantity
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateActualQuantity getActualQuantity() {
    return actualQuantity;
  }

  public void setActualQuantity(AnyOfSFODataAccrualCalculationBaseCreateActualQuantity actualQuantity) {
    this.actualQuantity = actualQuantity;
  }

  public SFODataAccrualCalculationBaseCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataAccrualCalculationBaseCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataAccrualCalculationBaseCreate date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public SFODataAccrualCalculationBaseCreate entityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
    return this;
  }

   /**
   * Get entityUUID
   * @return entityUUID
  **/
  public String getEntityUUID() {
    return entityUUID;
  }

  public void setEntityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
  }

  public SFODataAccrualCalculationBaseCreate externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataAccrualCalculationBaseCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataAccrualCalculationBaseCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataAccrualCalculationBaseCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataAccrualCalculationBaseCreate quantity1(AnyOfSFODataAccrualCalculationBaseCreateQuantity1 quantity1) {
    this.quantity1 = quantity1;
    return this;
  }

   /**
   * Get quantity1
   * @return quantity1
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateQuantity1 getQuantity1() {
    return quantity1;
  }

  public void setQuantity1(AnyOfSFODataAccrualCalculationBaseCreateQuantity1 quantity1) {
    this.quantity1 = quantity1;
  }

  public SFODataAccrualCalculationBaseCreate quantity2(AnyOfSFODataAccrualCalculationBaseCreateQuantity2 quantity2) {
    this.quantity2 = quantity2;
    return this;
  }

   /**
   * Get quantity2
   * @return quantity2
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateQuantity2 getQuantity2() {
    return quantity2;
  }

  public void setQuantity2(AnyOfSFODataAccrualCalculationBaseCreateQuantity2 quantity2) {
    this.quantity2 = quantity2;
  }

  public SFODataAccrualCalculationBaseCreate quantity3(AnyOfSFODataAccrualCalculationBaseCreateQuantity3 quantity3) {
    this.quantity3 = quantity3;
    return this;
  }

   /**
   * Get quantity3
   * @return quantity3
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateQuantity3 getQuantity3() {
    return quantity3;
  }

  public void setQuantity3(AnyOfSFODataAccrualCalculationBaseCreateQuantity3 quantity3) {
    this.quantity3 = quantity3;
  }

  public SFODataAccrualCalculationBaseCreate quantity4(AnyOfSFODataAccrualCalculationBaseCreateQuantity4 quantity4) {
    this.quantity4 = quantity4;
    return this;
  }

   /**
   * Get quantity4
   * @return quantity4
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateQuantity4 getQuantity4() {
    return quantity4;
  }

  public void setQuantity4(AnyOfSFODataAccrualCalculationBaseCreateQuantity4 quantity4) {
    this.quantity4 = quantity4;
  }

  public SFODataAccrualCalculationBaseCreate quantity5(AnyOfSFODataAccrualCalculationBaseCreateQuantity5 quantity5) {
    this.quantity5 = quantity5;
    return this;
  }

   /**
   * Get quantity5
   * @return quantity5
  **/
  public AnyOfSFODataAccrualCalculationBaseCreateQuantity5 getQuantity5() {
    return quantity5;
  }

  public void setQuantity5(AnyOfSFODataAccrualCalculationBaseCreateQuantity5 quantity5) {
    this.quantity5 = quantity5;
  }

  public SFODataAccrualCalculationBaseCreate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataAccrualCalculationBaseCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }

  public SFODataAccrualCalculationBaseCreate userIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
    return this;
  }

   /**
   * Get userIdNavAtOdataBind
   * @return userIdNavAtOdataBind
  **/
  public String getUserIdNavAtOdataBind() {
    return userIdNavAtOdataBind;
  }

  public void setUserIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataAccrualCalculationBaseCreate sfODataAccrualCalculationBaseCreate = (SFODataAccrualCalculationBaseCreate) o;
    return Objects.equals(this.actualQuantity, sfODataAccrualCalculationBaseCreate.actualQuantity) &&
        Objects.equals(this.createdBy, sfODataAccrualCalculationBaseCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataAccrualCalculationBaseCreate.createdDateTime) &&
        Objects.equals(this.date, sfODataAccrualCalculationBaseCreate.date) &&
        Objects.equals(this.entityUUID, sfODataAccrualCalculationBaseCreate.entityUUID) &&
        Objects.equals(this.externalCode, sfODataAccrualCalculationBaseCreate.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataAccrualCalculationBaseCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataAccrualCalculationBaseCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataAccrualCalculationBaseCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.quantity1, sfODataAccrualCalculationBaseCreate.quantity1) &&
        Objects.equals(this.quantity2, sfODataAccrualCalculationBaseCreate.quantity2) &&
        Objects.equals(this.quantity3, sfODataAccrualCalculationBaseCreate.quantity3) &&
        Objects.equals(this.quantity4, sfODataAccrualCalculationBaseCreate.quantity4) &&
        Objects.equals(this.quantity5, sfODataAccrualCalculationBaseCreate.quantity5) &&
        Objects.equals(this.userId, sfODataAccrualCalculationBaseCreate.userId) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataAccrualCalculationBaseCreate.mdfSystemRecordStatusNavAtOdataBind) &&
        Objects.equals(this.userIdNavAtOdataBind, sfODataAccrualCalculationBaseCreate.userIdNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actualQuantity, createdBy, createdDateTime, date, entityUUID, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, quantity1, quantity2, quantity3, quantity4, quantity5, userId, mdfSystemRecordStatusNavAtOdataBind, userIdNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataAccrualCalculationBaseCreate {\n");
    
    sb.append("    actualQuantity: ").append(toIndentedString(actualQuantity)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    entityUUID: ").append(toIndentedString(entityUUID)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    quantity1: ").append(toIndentedString(quantity1)).append("\n");
    sb.append("    quantity2: ").append(toIndentedString(quantity2)).append("\n");
    sb.append("    quantity3: ").append(toIndentedString(quantity3)).append("\n");
    sb.append("    quantity4: ").append(toIndentedString(quantity4)).append("\n");
    sb.append("    quantity5: ").append(toIndentedString(quantity5)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("    userIdNavAtOdataBind: ").append(toIndentedString(userIdNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
