/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataMDFBlockConfigCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataMDFBlockConfigCreate {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("objectType")
  private String objectType = null;

  @JsonProperty("screenId")
  private String screenId = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  public SFODataMDFBlockConfigCreate code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public SFODataMDFBlockConfigCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataMDFBlockConfigCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataMDFBlockConfigCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataMDFBlockConfigCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataMDFBlockConfigCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataMDFBlockConfigCreate objectType(String objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Get objectType
   * @return objectType
  **/
  public String getObjectType() {
    return objectType;
  }

  public void setObjectType(String objectType) {
    this.objectType = objectType;
  }

  public SFODataMDFBlockConfigCreate screenId(String screenId) {
    this.screenId = screenId;
    return this;
  }

   /**
   * Get screenId
   * @return screenId
  **/
  public String getScreenId() {
    return screenId;
  }

  public void setScreenId(String screenId) {
    this.screenId = screenId;
  }

  public SFODataMDFBlockConfigCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataMDFBlockConfigCreate sfODataMDFBlockConfigCreate = (SFODataMDFBlockConfigCreate) o;
    return Objects.equals(this.code, sfODataMDFBlockConfigCreate.code) &&
        Objects.equals(this.createdBy, sfODataMDFBlockConfigCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataMDFBlockConfigCreate.createdDateTime) &&
        Objects.equals(this.lastModifiedBy, sfODataMDFBlockConfigCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataMDFBlockConfigCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataMDFBlockConfigCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.objectType, sfODataMDFBlockConfigCreate.objectType) &&
        Objects.equals(this.screenId, sfODataMDFBlockConfigCreate.screenId) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataMDFBlockConfigCreate.mdfSystemRecordStatusNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, createdBy, createdDateTime, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, objectType, screenId, mdfSystemRecordStatusNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataMDFBlockConfigCreate {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    screenId: ").append(toIndentedString(screenId)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
