/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataWfRequestCommentsCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataWfRequestCommentsCreate {
  @JsonProperty("actionType")
  private String actionType = null;

  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("wfRequestCommentId")
  private AnyOfSFODataWfRequestCommentsCreateWfRequestCommentId wfRequestCommentId = null;

  @JsonProperty("wfRequestId")
  private AnyOfSFODataWfRequestCommentsCreateWfRequestId wfRequestId = null;

  @JsonProperty("wfRequestStepId")
  private AnyOfSFODataWfRequestCommentsCreateWfRequestStepId wfRequestStepId = null;

  public SFODataWfRequestCommentsCreate actionType(String actionType) {
    this.actionType = actionType;
    return this;
  }

   /**
   * Get actionType
   * @return actionType
  **/
  public String getActionType() {
    return actionType;
  }

  public void setActionType(String actionType) {
    this.actionType = actionType;
  }

  public SFODataWfRequestCommentsCreate comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public SFODataWfRequestCommentsCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataWfRequestCommentsCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataWfRequestCommentsCreate createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataWfRequestCommentsCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataWfRequestCommentsCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataWfRequestCommentsCreate lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataWfRequestCommentsCreate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataWfRequestCommentsCreate wfRequestCommentId(AnyOfSFODataWfRequestCommentsCreateWfRequestCommentId wfRequestCommentId) {
    this.wfRequestCommentId = wfRequestCommentId;
    return this;
  }

   /**
   * Get wfRequestCommentId
   * @return wfRequestCommentId
  **/
  public AnyOfSFODataWfRequestCommentsCreateWfRequestCommentId getWfRequestCommentId() {
    return wfRequestCommentId;
  }

  public void setWfRequestCommentId(AnyOfSFODataWfRequestCommentsCreateWfRequestCommentId wfRequestCommentId) {
    this.wfRequestCommentId = wfRequestCommentId;
  }

  public SFODataWfRequestCommentsCreate wfRequestId(AnyOfSFODataWfRequestCommentsCreateWfRequestId wfRequestId) {
    this.wfRequestId = wfRequestId;
    return this;
  }

   /**
   * Get wfRequestId
   * @return wfRequestId
  **/
  public AnyOfSFODataWfRequestCommentsCreateWfRequestId getWfRequestId() {
    return wfRequestId;
  }

  public void setWfRequestId(AnyOfSFODataWfRequestCommentsCreateWfRequestId wfRequestId) {
    this.wfRequestId = wfRequestId;
  }

  public SFODataWfRequestCommentsCreate wfRequestStepId(AnyOfSFODataWfRequestCommentsCreateWfRequestStepId wfRequestStepId) {
    this.wfRequestStepId = wfRequestStepId;
    return this;
  }

   /**
   * Get wfRequestStepId
   * @return wfRequestStepId
  **/
  public AnyOfSFODataWfRequestCommentsCreateWfRequestStepId getWfRequestStepId() {
    return wfRequestStepId;
  }

  public void setWfRequestStepId(AnyOfSFODataWfRequestCommentsCreateWfRequestStepId wfRequestStepId) {
    this.wfRequestStepId = wfRequestStepId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataWfRequestCommentsCreate sfODataWfRequestCommentsCreate = (SFODataWfRequestCommentsCreate) o;
    return Objects.equals(this.actionType, sfODataWfRequestCommentsCreate.actionType) &&
        Objects.equals(this.comments, sfODataWfRequestCommentsCreate.comments) &&
        Objects.equals(this.createdBy, sfODataWfRequestCommentsCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataWfRequestCommentsCreate.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataWfRequestCommentsCreate.createdOn) &&
        Objects.equals(this.lastModifiedBy, sfODataWfRequestCommentsCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataWfRequestCommentsCreate.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataWfRequestCommentsCreate.lastModifiedOn) &&
        Objects.equals(this.userId, sfODataWfRequestCommentsCreate.userId) &&
        Objects.equals(this.wfRequestCommentId, sfODataWfRequestCommentsCreate.wfRequestCommentId) &&
        Objects.equals(this.wfRequestId, sfODataWfRequestCommentsCreate.wfRequestId) &&
        Objects.equals(this.wfRequestStepId, sfODataWfRequestCommentsCreate.wfRequestStepId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionType, comments, createdBy, createdDateTime, createdOn, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, userId, wfRequestCommentId, wfRequestId, wfRequestStepId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataWfRequestCommentsCreate {\n");
    
    sb.append("    actionType: ").append(toIndentedString(actionType)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    wfRequestCommentId: ").append(toIndentedString(wfRequestCommentId)).append("\n");
    sb.append("    wfRequestId: ").append(toIndentedString(wfRequestId)).append("\n");
    sb.append("    wfRequestStepId: ").append(toIndentedString(wfRequestStepId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
