/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.Count;
import com.axonivy.connector.successfactors.connector.rest.SFODataMDFEnumValue;
import com.axonivy.connector.successfactors.connector.rest.SFODataPickListValueV2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * SFODataJobClassificationUSA
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataJobClassificationUSA {
  @JsonProperty("JobClassificationCountry_country")
  private String jobClassificationCountryCountry = null;

  @JsonProperty("JobClassification_effectiveStartDate")
  private OffsetDateTime jobClassificationEffectiveStartDate = null;

  @JsonProperty("JobClassification_externalCode")
  private String jobClassificationExternalCode = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("eeo1JobCategory")
  private String eeo1JobCategory = null;

  @JsonProperty("eeo4JobCategory")
  private String eeo4JobCategory = null;

  @JsonProperty("eeo5JobCategory")
  private String eeo5JobCategory = null;

  @JsonProperty("eeo6JobCategory")
  private String eeo6JobCategory = null;

  @JsonProperty("eeoJobGroup")
  private String eeoJobGroup = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataJobClassificationUSAExternalCode externalCode = null;

  @JsonProperty("flsaStatusUSA")
  private String flsaStatusUSA = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("localJobTitle")
  private String localJobTitle = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("createdByNav")
  private AllOfSFODataJobClassificationUSACreatedByNav createdByNav = null;

  @JsonProperty("eeo1JobCategoryNav")
  private List<SFODataPickListValueV2> eeo1JobCategoryNav = null;

  @JsonProperty("eeo1JobCategoryNav@odata.count")
  private Count eeo1JobCategoryNavAtOdataCount = null;

  @JsonProperty("eeo4JobCategoryNav")
  private List<SFODataPickListValueV2> eeo4JobCategoryNav = null;

  @JsonProperty("eeo4JobCategoryNav@odata.count")
  private Count eeo4JobCategoryNavAtOdataCount = null;

  @JsonProperty("eeo5JobCategoryNav")
  private List<SFODataPickListValueV2> eeo5JobCategoryNav = null;

  @JsonProperty("eeo5JobCategoryNav@odata.count")
  private Count eeo5JobCategoryNavAtOdataCount = null;

  @JsonProperty("eeo6JobCategoryNav")
  private List<SFODataPickListValueV2> eeo6JobCategoryNav = null;

  @JsonProperty("eeo6JobCategoryNav@odata.count")
  private Count eeo6JobCategoryNavAtOdataCount = null;

  @JsonProperty("eeoJobGroupNav")
  private List<SFODataPickListValueV2> eeoJobGroupNav = null;

  @JsonProperty("eeoJobGroupNav@odata.count")
  private Count eeoJobGroupNavAtOdataCount = null;

  @JsonProperty("flsaStatusUSANav")
  private List<SFODataPickListValueV2> flsaStatusUSANav = null;

  @JsonProperty("flsaStatusUSANav@odata.count")
  private Count flsaStatusUSANavAtOdataCount = null;

  @JsonProperty("lastModifiedByNav")
  private AllOfSFODataJobClassificationUSALastModifiedByNav lastModifiedByNav = null;

  @JsonProperty("mdfSystemRecordStatusNav")
  private SFODataMDFEnumValue mdfSystemRecordStatusNav = null;

  public SFODataJobClassificationUSA jobClassificationCountryCountry(String jobClassificationCountryCountry) {
    this.jobClassificationCountryCountry = jobClassificationCountryCountry;
    return this;
  }

   /**
   * Get jobClassificationCountryCountry
   * @return jobClassificationCountryCountry
  **/
  public String getJobClassificationCountryCountry() {
    return jobClassificationCountryCountry;
  }

  public void setJobClassificationCountryCountry(String jobClassificationCountryCountry) {
    this.jobClassificationCountryCountry = jobClassificationCountryCountry;
  }

  public SFODataJobClassificationUSA jobClassificationEffectiveStartDate(OffsetDateTime jobClassificationEffectiveStartDate) {
    this.jobClassificationEffectiveStartDate = jobClassificationEffectiveStartDate;
    return this;
  }

   /**
   * Get jobClassificationEffectiveStartDate
   * @return jobClassificationEffectiveStartDate
  **/
  public OffsetDateTime getJobClassificationEffectiveStartDate() {
    return jobClassificationEffectiveStartDate;
  }

  public void setJobClassificationEffectiveStartDate(OffsetDateTime jobClassificationEffectiveStartDate) {
    this.jobClassificationEffectiveStartDate = jobClassificationEffectiveStartDate;
  }

  public SFODataJobClassificationUSA jobClassificationExternalCode(String jobClassificationExternalCode) {
    this.jobClassificationExternalCode = jobClassificationExternalCode;
    return this;
  }

   /**
   * Get jobClassificationExternalCode
   * @return jobClassificationExternalCode
  **/
  public String getJobClassificationExternalCode() {
    return jobClassificationExternalCode;
  }

  public void setJobClassificationExternalCode(String jobClassificationExternalCode) {
    this.jobClassificationExternalCode = jobClassificationExternalCode;
  }

  public SFODataJobClassificationUSA createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataJobClassificationUSA createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataJobClassificationUSA eeo1JobCategory(String eeo1JobCategory) {
    this.eeo1JobCategory = eeo1JobCategory;
    return this;
  }

   /**
   * Get eeo1JobCategory
   * @return eeo1JobCategory
  **/
  public String getEeo1JobCategory() {
    return eeo1JobCategory;
  }

  public void setEeo1JobCategory(String eeo1JobCategory) {
    this.eeo1JobCategory = eeo1JobCategory;
  }

  public SFODataJobClassificationUSA eeo4JobCategory(String eeo4JobCategory) {
    this.eeo4JobCategory = eeo4JobCategory;
    return this;
  }

   /**
   * Get eeo4JobCategory
   * @return eeo4JobCategory
  **/
  public String getEeo4JobCategory() {
    return eeo4JobCategory;
  }

  public void setEeo4JobCategory(String eeo4JobCategory) {
    this.eeo4JobCategory = eeo4JobCategory;
  }

  public SFODataJobClassificationUSA eeo5JobCategory(String eeo5JobCategory) {
    this.eeo5JobCategory = eeo5JobCategory;
    return this;
  }

   /**
   * Get eeo5JobCategory
   * @return eeo5JobCategory
  **/
  public String getEeo5JobCategory() {
    return eeo5JobCategory;
  }

  public void setEeo5JobCategory(String eeo5JobCategory) {
    this.eeo5JobCategory = eeo5JobCategory;
  }

  public SFODataJobClassificationUSA eeo6JobCategory(String eeo6JobCategory) {
    this.eeo6JobCategory = eeo6JobCategory;
    return this;
  }

   /**
   * Get eeo6JobCategory
   * @return eeo6JobCategory
  **/
  public String getEeo6JobCategory() {
    return eeo6JobCategory;
  }

  public void setEeo6JobCategory(String eeo6JobCategory) {
    this.eeo6JobCategory = eeo6JobCategory;
  }

  public SFODataJobClassificationUSA eeoJobGroup(String eeoJobGroup) {
    this.eeoJobGroup = eeoJobGroup;
    return this;
  }

   /**
   * Get eeoJobGroup
   * @return eeoJobGroup
  **/
  public String getEeoJobGroup() {
    return eeoJobGroup;
  }

  public void setEeoJobGroup(String eeoJobGroup) {
    this.eeoJobGroup = eeoJobGroup;
  }

  public SFODataJobClassificationUSA externalCode(AnyOfSFODataJobClassificationUSAExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataJobClassificationUSAExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataJobClassificationUSAExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataJobClassificationUSA flsaStatusUSA(String flsaStatusUSA) {
    this.flsaStatusUSA = flsaStatusUSA;
    return this;
  }

   /**
   * Get flsaStatusUSA
   * @return flsaStatusUSA
  **/
  public String getFlsaStatusUSA() {
    return flsaStatusUSA;
  }

  public void setFlsaStatusUSA(String flsaStatusUSA) {
    this.flsaStatusUSA = flsaStatusUSA;
  }

  public SFODataJobClassificationUSA lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataJobClassificationUSA lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataJobClassificationUSA localJobTitle(String localJobTitle) {
    this.localJobTitle = localJobTitle;
    return this;
  }

   /**
   * Get localJobTitle
   * @return localJobTitle
  **/
  public String getLocalJobTitle() {
    return localJobTitle;
  }

  public void setLocalJobTitle(String localJobTitle) {
    this.localJobTitle = localJobTitle;
  }

  public SFODataJobClassificationUSA mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataJobClassificationUSA createdByNav(AllOfSFODataJobClassificationUSACreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
    return this;
  }

   /**
   * Get createdByNav
   * @return createdByNav
  **/
  public AllOfSFODataJobClassificationUSACreatedByNav getCreatedByNav() {
    return createdByNav;
  }

  public void setCreatedByNav(AllOfSFODataJobClassificationUSACreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
  }

  public SFODataJobClassificationUSA eeo1JobCategoryNav(List<SFODataPickListValueV2> eeo1JobCategoryNav) {
    this.eeo1JobCategoryNav = eeo1JobCategoryNav;
    return this;
  }

  public SFODataJobClassificationUSA addEeo1JobCategoryNavItem(SFODataPickListValueV2 eeo1JobCategoryNavItem) {
    if (this.eeo1JobCategoryNav == null) {
      this.eeo1JobCategoryNav = new ArrayList<>();
    }
    this.eeo1JobCategoryNav.add(eeo1JobCategoryNavItem);
    return this;
  }

   /**
   * Get eeo1JobCategoryNav
   * @return eeo1JobCategoryNav
  **/
  public List<SFODataPickListValueV2> getEeo1JobCategoryNav() {
    return eeo1JobCategoryNav;
  }

  public void setEeo1JobCategoryNav(List<SFODataPickListValueV2> eeo1JobCategoryNav) {
    this.eeo1JobCategoryNav = eeo1JobCategoryNav;
  }

  public SFODataJobClassificationUSA eeo1JobCategoryNavAtOdataCount(Count eeo1JobCategoryNavAtOdataCount) {
    this.eeo1JobCategoryNavAtOdataCount = eeo1JobCategoryNavAtOdataCount;
    return this;
  }

   /**
   * Get eeo1JobCategoryNavAtOdataCount
   * @return eeo1JobCategoryNavAtOdataCount
  **/
  public Count getEeo1JobCategoryNavAtOdataCount() {
    return eeo1JobCategoryNavAtOdataCount;
  }

  public void setEeo1JobCategoryNavAtOdataCount(Count eeo1JobCategoryNavAtOdataCount) {
    this.eeo1JobCategoryNavAtOdataCount = eeo1JobCategoryNavAtOdataCount;
  }

  public SFODataJobClassificationUSA eeo4JobCategoryNav(List<SFODataPickListValueV2> eeo4JobCategoryNav) {
    this.eeo4JobCategoryNav = eeo4JobCategoryNav;
    return this;
  }

  public SFODataJobClassificationUSA addEeo4JobCategoryNavItem(SFODataPickListValueV2 eeo4JobCategoryNavItem) {
    if (this.eeo4JobCategoryNav == null) {
      this.eeo4JobCategoryNav = new ArrayList<>();
    }
    this.eeo4JobCategoryNav.add(eeo4JobCategoryNavItem);
    return this;
  }

   /**
   * Get eeo4JobCategoryNav
   * @return eeo4JobCategoryNav
  **/
  public List<SFODataPickListValueV2> getEeo4JobCategoryNav() {
    return eeo4JobCategoryNav;
  }

  public void setEeo4JobCategoryNav(List<SFODataPickListValueV2> eeo4JobCategoryNav) {
    this.eeo4JobCategoryNav = eeo4JobCategoryNav;
  }

  public SFODataJobClassificationUSA eeo4JobCategoryNavAtOdataCount(Count eeo4JobCategoryNavAtOdataCount) {
    this.eeo4JobCategoryNavAtOdataCount = eeo4JobCategoryNavAtOdataCount;
    return this;
  }

   /**
   * Get eeo4JobCategoryNavAtOdataCount
   * @return eeo4JobCategoryNavAtOdataCount
  **/
  public Count getEeo4JobCategoryNavAtOdataCount() {
    return eeo4JobCategoryNavAtOdataCount;
  }

  public void setEeo4JobCategoryNavAtOdataCount(Count eeo4JobCategoryNavAtOdataCount) {
    this.eeo4JobCategoryNavAtOdataCount = eeo4JobCategoryNavAtOdataCount;
  }

  public SFODataJobClassificationUSA eeo5JobCategoryNav(List<SFODataPickListValueV2> eeo5JobCategoryNav) {
    this.eeo5JobCategoryNav = eeo5JobCategoryNav;
    return this;
  }

  public SFODataJobClassificationUSA addEeo5JobCategoryNavItem(SFODataPickListValueV2 eeo5JobCategoryNavItem) {
    if (this.eeo5JobCategoryNav == null) {
      this.eeo5JobCategoryNav = new ArrayList<>();
    }
    this.eeo5JobCategoryNav.add(eeo5JobCategoryNavItem);
    return this;
  }

   /**
   * Get eeo5JobCategoryNav
   * @return eeo5JobCategoryNav
  **/
  public List<SFODataPickListValueV2> getEeo5JobCategoryNav() {
    return eeo5JobCategoryNav;
  }

  public void setEeo5JobCategoryNav(List<SFODataPickListValueV2> eeo5JobCategoryNav) {
    this.eeo5JobCategoryNav = eeo5JobCategoryNav;
  }

  public SFODataJobClassificationUSA eeo5JobCategoryNavAtOdataCount(Count eeo5JobCategoryNavAtOdataCount) {
    this.eeo5JobCategoryNavAtOdataCount = eeo5JobCategoryNavAtOdataCount;
    return this;
  }

   /**
   * Get eeo5JobCategoryNavAtOdataCount
   * @return eeo5JobCategoryNavAtOdataCount
  **/
  public Count getEeo5JobCategoryNavAtOdataCount() {
    return eeo5JobCategoryNavAtOdataCount;
  }

  public void setEeo5JobCategoryNavAtOdataCount(Count eeo5JobCategoryNavAtOdataCount) {
    this.eeo5JobCategoryNavAtOdataCount = eeo5JobCategoryNavAtOdataCount;
  }

  public SFODataJobClassificationUSA eeo6JobCategoryNav(List<SFODataPickListValueV2> eeo6JobCategoryNav) {
    this.eeo6JobCategoryNav = eeo6JobCategoryNav;
    return this;
  }

  public SFODataJobClassificationUSA addEeo6JobCategoryNavItem(SFODataPickListValueV2 eeo6JobCategoryNavItem) {
    if (this.eeo6JobCategoryNav == null) {
      this.eeo6JobCategoryNav = new ArrayList<>();
    }
    this.eeo6JobCategoryNav.add(eeo6JobCategoryNavItem);
    return this;
  }

   /**
   * Get eeo6JobCategoryNav
   * @return eeo6JobCategoryNav
  **/
  public List<SFODataPickListValueV2> getEeo6JobCategoryNav() {
    return eeo6JobCategoryNav;
  }

  public void setEeo6JobCategoryNav(List<SFODataPickListValueV2> eeo6JobCategoryNav) {
    this.eeo6JobCategoryNav = eeo6JobCategoryNav;
  }

  public SFODataJobClassificationUSA eeo6JobCategoryNavAtOdataCount(Count eeo6JobCategoryNavAtOdataCount) {
    this.eeo6JobCategoryNavAtOdataCount = eeo6JobCategoryNavAtOdataCount;
    return this;
  }

   /**
   * Get eeo6JobCategoryNavAtOdataCount
   * @return eeo6JobCategoryNavAtOdataCount
  **/
  public Count getEeo6JobCategoryNavAtOdataCount() {
    return eeo6JobCategoryNavAtOdataCount;
  }

  public void setEeo6JobCategoryNavAtOdataCount(Count eeo6JobCategoryNavAtOdataCount) {
    this.eeo6JobCategoryNavAtOdataCount = eeo6JobCategoryNavAtOdataCount;
  }

  public SFODataJobClassificationUSA eeoJobGroupNav(List<SFODataPickListValueV2> eeoJobGroupNav) {
    this.eeoJobGroupNav = eeoJobGroupNav;
    return this;
  }

  public SFODataJobClassificationUSA addEeoJobGroupNavItem(SFODataPickListValueV2 eeoJobGroupNavItem) {
    if (this.eeoJobGroupNav == null) {
      this.eeoJobGroupNav = new ArrayList<>();
    }
    this.eeoJobGroupNav.add(eeoJobGroupNavItem);
    return this;
  }

   /**
   * Get eeoJobGroupNav
   * @return eeoJobGroupNav
  **/
  public List<SFODataPickListValueV2> getEeoJobGroupNav() {
    return eeoJobGroupNav;
  }

  public void setEeoJobGroupNav(List<SFODataPickListValueV2> eeoJobGroupNav) {
    this.eeoJobGroupNav = eeoJobGroupNav;
  }

  public SFODataJobClassificationUSA eeoJobGroupNavAtOdataCount(Count eeoJobGroupNavAtOdataCount) {
    this.eeoJobGroupNavAtOdataCount = eeoJobGroupNavAtOdataCount;
    return this;
  }

   /**
   * Get eeoJobGroupNavAtOdataCount
   * @return eeoJobGroupNavAtOdataCount
  **/
  public Count getEeoJobGroupNavAtOdataCount() {
    return eeoJobGroupNavAtOdataCount;
  }

  public void setEeoJobGroupNavAtOdataCount(Count eeoJobGroupNavAtOdataCount) {
    this.eeoJobGroupNavAtOdataCount = eeoJobGroupNavAtOdataCount;
  }

  public SFODataJobClassificationUSA flsaStatusUSANav(List<SFODataPickListValueV2> flsaStatusUSANav) {
    this.flsaStatusUSANav = flsaStatusUSANav;
    return this;
  }

  public SFODataJobClassificationUSA addFlsaStatusUSANavItem(SFODataPickListValueV2 flsaStatusUSANavItem) {
    if (this.flsaStatusUSANav == null) {
      this.flsaStatusUSANav = new ArrayList<>();
    }
    this.flsaStatusUSANav.add(flsaStatusUSANavItem);
    return this;
  }

   /**
   * Get flsaStatusUSANav
   * @return flsaStatusUSANav
  **/
  public List<SFODataPickListValueV2> getFlsaStatusUSANav() {
    return flsaStatusUSANav;
  }

  public void setFlsaStatusUSANav(List<SFODataPickListValueV2> flsaStatusUSANav) {
    this.flsaStatusUSANav = flsaStatusUSANav;
  }

  public SFODataJobClassificationUSA flsaStatusUSANavAtOdataCount(Count flsaStatusUSANavAtOdataCount) {
    this.flsaStatusUSANavAtOdataCount = flsaStatusUSANavAtOdataCount;
    return this;
  }

   /**
   * Get flsaStatusUSANavAtOdataCount
   * @return flsaStatusUSANavAtOdataCount
  **/
  public Count getFlsaStatusUSANavAtOdataCount() {
    return flsaStatusUSANavAtOdataCount;
  }

  public void setFlsaStatusUSANavAtOdataCount(Count flsaStatusUSANavAtOdataCount) {
    this.flsaStatusUSANavAtOdataCount = flsaStatusUSANavAtOdataCount;
  }

  public SFODataJobClassificationUSA lastModifiedByNav(AllOfSFODataJobClassificationUSALastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
    return this;
  }

   /**
   * Get lastModifiedByNav
   * @return lastModifiedByNav
  **/
  public AllOfSFODataJobClassificationUSALastModifiedByNav getLastModifiedByNav() {
    return lastModifiedByNav;
  }

  public void setLastModifiedByNav(AllOfSFODataJobClassificationUSALastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
  }

  public SFODataJobClassificationUSA mdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNav
   * @return mdfSystemRecordStatusNav
  **/
  public SFODataMDFEnumValue getMdfSystemRecordStatusNav() {
    return mdfSystemRecordStatusNav;
  }

  public void setMdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataJobClassificationUSA sfODataJobClassificationUSA = (SFODataJobClassificationUSA) o;
    return Objects.equals(this.jobClassificationCountryCountry, sfODataJobClassificationUSA.jobClassificationCountryCountry) &&
        Objects.equals(this.jobClassificationEffectiveStartDate, sfODataJobClassificationUSA.jobClassificationEffectiveStartDate) &&
        Objects.equals(this.jobClassificationExternalCode, sfODataJobClassificationUSA.jobClassificationExternalCode) &&
        Objects.equals(this.createdBy, sfODataJobClassificationUSA.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataJobClassificationUSA.createdDateTime) &&
        Objects.equals(this.eeo1JobCategory, sfODataJobClassificationUSA.eeo1JobCategory) &&
        Objects.equals(this.eeo4JobCategory, sfODataJobClassificationUSA.eeo4JobCategory) &&
        Objects.equals(this.eeo5JobCategory, sfODataJobClassificationUSA.eeo5JobCategory) &&
        Objects.equals(this.eeo6JobCategory, sfODataJobClassificationUSA.eeo6JobCategory) &&
        Objects.equals(this.eeoJobGroup, sfODataJobClassificationUSA.eeoJobGroup) &&
        Objects.equals(this.externalCode, sfODataJobClassificationUSA.externalCode) &&
        Objects.equals(this.flsaStatusUSA, sfODataJobClassificationUSA.flsaStatusUSA) &&
        Objects.equals(this.lastModifiedBy, sfODataJobClassificationUSA.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataJobClassificationUSA.lastModifiedDateTime) &&
        Objects.equals(this.localJobTitle, sfODataJobClassificationUSA.localJobTitle) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataJobClassificationUSA.mdfSystemRecordStatus) &&
        Objects.equals(this.createdByNav, sfODataJobClassificationUSA.createdByNav) &&
        Objects.equals(this.eeo1JobCategoryNav, sfODataJobClassificationUSA.eeo1JobCategoryNav) &&
        Objects.equals(this.eeo1JobCategoryNavAtOdataCount, sfODataJobClassificationUSA.eeo1JobCategoryNavAtOdataCount) &&
        Objects.equals(this.eeo4JobCategoryNav, sfODataJobClassificationUSA.eeo4JobCategoryNav) &&
        Objects.equals(this.eeo4JobCategoryNavAtOdataCount, sfODataJobClassificationUSA.eeo4JobCategoryNavAtOdataCount) &&
        Objects.equals(this.eeo5JobCategoryNav, sfODataJobClassificationUSA.eeo5JobCategoryNav) &&
        Objects.equals(this.eeo5JobCategoryNavAtOdataCount, sfODataJobClassificationUSA.eeo5JobCategoryNavAtOdataCount) &&
        Objects.equals(this.eeo6JobCategoryNav, sfODataJobClassificationUSA.eeo6JobCategoryNav) &&
        Objects.equals(this.eeo6JobCategoryNavAtOdataCount, sfODataJobClassificationUSA.eeo6JobCategoryNavAtOdataCount) &&
        Objects.equals(this.eeoJobGroupNav, sfODataJobClassificationUSA.eeoJobGroupNav) &&
        Objects.equals(this.eeoJobGroupNavAtOdataCount, sfODataJobClassificationUSA.eeoJobGroupNavAtOdataCount) &&
        Objects.equals(this.flsaStatusUSANav, sfODataJobClassificationUSA.flsaStatusUSANav) &&
        Objects.equals(this.flsaStatusUSANavAtOdataCount, sfODataJobClassificationUSA.flsaStatusUSANavAtOdataCount) &&
        Objects.equals(this.lastModifiedByNav, sfODataJobClassificationUSA.lastModifiedByNav) &&
        Objects.equals(this.mdfSystemRecordStatusNav, sfODataJobClassificationUSA.mdfSystemRecordStatusNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobClassificationCountryCountry, jobClassificationEffectiveStartDate, jobClassificationExternalCode, createdBy, createdDateTime, eeo1JobCategory, eeo4JobCategory, eeo5JobCategory, eeo6JobCategory, eeoJobGroup, externalCode, flsaStatusUSA, lastModifiedBy, lastModifiedDateTime, localJobTitle, mdfSystemRecordStatus, createdByNav, eeo1JobCategoryNav, eeo1JobCategoryNavAtOdataCount, eeo4JobCategoryNav, eeo4JobCategoryNavAtOdataCount, eeo5JobCategoryNav, eeo5JobCategoryNavAtOdataCount, eeo6JobCategoryNav, eeo6JobCategoryNavAtOdataCount, eeoJobGroupNav, eeoJobGroupNavAtOdataCount, flsaStatusUSANav, flsaStatusUSANavAtOdataCount, lastModifiedByNav, mdfSystemRecordStatusNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataJobClassificationUSA {\n");
    
    sb.append("    jobClassificationCountryCountry: ").append(toIndentedString(jobClassificationCountryCountry)).append("\n");
    sb.append("    jobClassificationEffectiveStartDate: ").append(toIndentedString(jobClassificationEffectiveStartDate)).append("\n");
    sb.append("    jobClassificationExternalCode: ").append(toIndentedString(jobClassificationExternalCode)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    eeo1JobCategory: ").append(toIndentedString(eeo1JobCategory)).append("\n");
    sb.append("    eeo4JobCategory: ").append(toIndentedString(eeo4JobCategory)).append("\n");
    sb.append("    eeo5JobCategory: ").append(toIndentedString(eeo5JobCategory)).append("\n");
    sb.append("    eeo6JobCategory: ").append(toIndentedString(eeo6JobCategory)).append("\n");
    sb.append("    eeoJobGroup: ").append(toIndentedString(eeoJobGroup)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    flsaStatusUSA: ").append(toIndentedString(flsaStatusUSA)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    localJobTitle: ").append(toIndentedString(localJobTitle)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    createdByNav: ").append(toIndentedString(createdByNav)).append("\n");
    sb.append("    eeo1JobCategoryNav: ").append(toIndentedString(eeo1JobCategoryNav)).append("\n");
    sb.append("    eeo1JobCategoryNavAtOdataCount: ").append(toIndentedString(eeo1JobCategoryNavAtOdataCount)).append("\n");
    sb.append("    eeo4JobCategoryNav: ").append(toIndentedString(eeo4JobCategoryNav)).append("\n");
    sb.append("    eeo4JobCategoryNavAtOdataCount: ").append(toIndentedString(eeo4JobCategoryNavAtOdataCount)).append("\n");
    sb.append("    eeo5JobCategoryNav: ").append(toIndentedString(eeo5JobCategoryNav)).append("\n");
    sb.append("    eeo5JobCategoryNavAtOdataCount: ").append(toIndentedString(eeo5JobCategoryNavAtOdataCount)).append("\n");
    sb.append("    eeo6JobCategoryNav: ").append(toIndentedString(eeo6JobCategoryNav)).append("\n");
    sb.append("    eeo6JobCategoryNavAtOdataCount: ").append(toIndentedString(eeo6JobCategoryNavAtOdataCount)).append("\n");
    sb.append("    eeoJobGroupNav: ").append(toIndentedString(eeoJobGroupNav)).append("\n");
    sb.append("    eeoJobGroupNavAtOdataCount: ").append(toIndentedString(eeoJobGroupNavAtOdataCount)).append("\n");
    sb.append("    flsaStatusUSANav: ").append(toIndentedString(flsaStatusUSANav)).append("\n");
    sb.append("    flsaStatusUSANavAtOdataCount: ").append(toIndentedString(flsaStatusUSANavAtOdataCount)).append("\n");
    sb.append("    lastModifiedByNav: ").append(toIndentedString(lastModifiedByNav)).append("\n");
    sb.append("    mdfSystemRecordStatusNav: ").append(toIndentedString(mdfSystemRecordStatusNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
