/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.SFODataMDFEnumValue;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataPaymentInformationDetailV3LocalizeUpsert
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataPaymentInformationDetailV3LocalizeUpsert {
  @JsonProperty("metadataUri")
  private String metadataUri = null;

  @JsonProperty("PaymentInformationDetailV3_externalCode")
  private String paymentInformationDetailV3ExternalCode = null;

  @JsonProperty("PaymentInformationV3_effectiveStartDate")
  private String paymentInformationV3EffectiveStartDate = null;

  @JsonProperty("PaymentInformationV3_worker")
  private String paymentInformationV3Worker = null;

  @JsonProperty("buildingSocietyRollNumber")
  private String buildingSocietyRollNumber = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("accountHolderRelationship")
  private String accountHolderRelationship = null;

  @JsonProperty("accountType")
  private String accountType = null;

  @JsonProperty("mdfSystemRecordStatusNav")
  private SFODataMDFEnumValue mdfSystemRecordStatusNav = null;

  public SFODataPaymentInformationDetailV3LocalizeUpsert metadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
    return this;
  }

   /**
   * Get metadataUri
   * @return metadataUri
  **/
  public String getMetadataUri() {
    return metadataUri;
  }

  public void setMetadataUri(String metadataUri) {
    this.metadataUri = metadataUri;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert paymentInformationDetailV3ExternalCode(String paymentInformationDetailV3ExternalCode) {
    this.paymentInformationDetailV3ExternalCode = paymentInformationDetailV3ExternalCode;
    return this;
  }

   /**
   * Get paymentInformationDetailV3ExternalCode
   * @return paymentInformationDetailV3ExternalCode
  **/
  public String getPaymentInformationDetailV3ExternalCode() {
    return paymentInformationDetailV3ExternalCode;
  }

  public void setPaymentInformationDetailV3ExternalCode(String paymentInformationDetailV3ExternalCode) {
    this.paymentInformationDetailV3ExternalCode = paymentInformationDetailV3ExternalCode;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert paymentInformationV3EffectiveStartDate(String paymentInformationV3EffectiveStartDate) {
    this.paymentInformationV3EffectiveStartDate = paymentInformationV3EffectiveStartDate;
    return this;
  }

   /**
   * Get paymentInformationV3EffectiveStartDate
   * @return paymentInformationV3EffectiveStartDate
  **/
  public String getPaymentInformationV3EffectiveStartDate() {
    return paymentInformationV3EffectiveStartDate;
  }

  public void setPaymentInformationV3EffectiveStartDate(String paymentInformationV3EffectiveStartDate) {
    this.paymentInformationV3EffectiveStartDate = paymentInformationV3EffectiveStartDate;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert paymentInformationV3Worker(String paymentInformationV3Worker) {
    this.paymentInformationV3Worker = paymentInformationV3Worker;
    return this;
  }

   /**
   * Get paymentInformationV3Worker
   * @return paymentInformationV3Worker
  **/
  public String getPaymentInformationV3Worker() {
    return paymentInformationV3Worker;
  }

  public void setPaymentInformationV3Worker(String paymentInformationV3Worker) {
    this.paymentInformationV3Worker = paymentInformationV3Worker;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert buildingSocietyRollNumber(String buildingSocietyRollNumber) {
    this.buildingSocietyRollNumber = buildingSocietyRollNumber;
    return this;
  }

   /**
   * Get buildingSocietyRollNumber
   * @return buildingSocietyRollNumber
  **/
  public String getBuildingSocietyRollNumber() {
    return buildingSocietyRollNumber;
  }

  public void setBuildingSocietyRollNumber(String buildingSocietyRollNumber) {
    this.buildingSocietyRollNumber = buildingSocietyRollNumber;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert accountHolderRelationship(String accountHolderRelationship) {
    this.accountHolderRelationship = accountHolderRelationship;
    return this;
  }

   /**
   * Get accountHolderRelationship
   * @return accountHolderRelationship
  **/
  public String getAccountHolderRelationship() {
    return accountHolderRelationship;
  }

  public void setAccountHolderRelationship(String accountHolderRelationship) {
    this.accountHolderRelationship = accountHolderRelationship;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public SFODataPaymentInformationDetailV3LocalizeUpsert mdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNav
   * @return mdfSystemRecordStatusNav
  **/
  public SFODataMDFEnumValue getMdfSystemRecordStatusNav() {
    return mdfSystemRecordStatusNav;
  }

  public void setMdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataPaymentInformationDetailV3LocalizeUpsert sfODataPaymentInformationDetailV3LocalizeUpsert = (SFODataPaymentInformationDetailV3LocalizeUpsert) o;
    return Objects.equals(this.metadataUri, sfODataPaymentInformationDetailV3LocalizeUpsert.metadataUri) &&
        Objects.equals(this.paymentInformationDetailV3ExternalCode, sfODataPaymentInformationDetailV3LocalizeUpsert.paymentInformationDetailV3ExternalCode) &&
        Objects.equals(this.paymentInformationV3EffectiveStartDate, sfODataPaymentInformationDetailV3LocalizeUpsert.paymentInformationV3EffectiveStartDate) &&
        Objects.equals(this.paymentInformationV3Worker, sfODataPaymentInformationDetailV3LocalizeUpsert.paymentInformationV3Worker) &&
        Objects.equals(this.buildingSocietyRollNumber, sfODataPaymentInformationDetailV3LocalizeUpsert.buildingSocietyRollNumber) &&
        Objects.equals(this.externalCode, sfODataPaymentInformationDetailV3LocalizeUpsert.externalCode) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataPaymentInformationDetailV3LocalizeUpsert.mdfSystemRecordStatus) &&
        Objects.equals(this.accountHolderRelationship, sfODataPaymentInformationDetailV3LocalizeUpsert.accountHolderRelationship) &&
        Objects.equals(this.accountType, sfODataPaymentInformationDetailV3LocalizeUpsert.accountType) &&
        Objects.equals(this.mdfSystemRecordStatusNav, sfODataPaymentInformationDetailV3LocalizeUpsert.mdfSystemRecordStatusNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadataUri, paymentInformationDetailV3ExternalCode, paymentInformationV3EffectiveStartDate, paymentInformationV3Worker, buildingSocietyRollNumber, externalCode, mdfSystemRecordStatus, accountHolderRelationship, accountType, mdfSystemRecordStatusNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataPaymentInformationDetailV3LocalizeUpsert {\n");
    
    sb.append("    metadataUri: ").append(toIndentedString(metadataUri)).append("\n");
    sb.append("    paymentInformationDetailV3ExternalCode: ").append(toIndentedString(paymentInformationDetailV3ExternalCode)).append("\n");
    sb.append("    paymentInformationV3EffectiveStartDate: ").append(toIndentedString(paymentInformationV3EffectiveStartDate)).append("\n");
    sb.append("    paymentInformationV3Worker: ").append(toIndentedString(paymentInformationV3Worker)).append("\n");
    sb.append("    buildingSocietyRollNumber: ").append(toIndentedString(buildingSocietyRollNumber)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    accountHolderRelationship: ").append(toIndentedString(accountHolderRelationship)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    mdfSystemRecordStatusNav: ").append(toIndentedString(mdfSystemRecordStatusNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
