/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataFormCustomElementListValueUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataFormCustomElementListValueUpdate {
  @JsonProperty("listIndex")
  private Integer listIndex = null;

  @JsonProperty("selected")
  private Boolean selected = null;

  @JsonProperty("value")
  private String value = null;

  public SFODataFormCustomElementListValueUpdate listIndex(Integer listIndex) {
    this.listIndex = listIndex;
    return this;
  }

   /**
   * Get listIndex
   * @return listIndex
  **/
  public Integer getListIndex() {
    return listIndex;
  }

  public void setListIndex(Integer listIndex) {
    this.listIndex = listIndex;
  }

  public SFODataFormCustomElementListValueUpdate selected(Boolean selected) {
    this.selected = selected;
    return this;
  }

   /**
   * Get selected
   * @return selected
  **/
  public Boolean isSelected() {
    return selected;
  }

  public void setSelected(Boolean selected) {
    this.selected = selected;
  }

  public SFODataFormCustomElementListValueUpdate value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataFormCustomElementListValueUpdate sfODataFormCustomElementListValueUpdate = (SFODataFormCustomElementListValueUpdate) o;
    return Objects.equals(this.listIndex, sfODataFormCustomElementListValueUpdate.listIndex) &&
        Objects.equals(this.selected, sfODataFormCustomElementListValueUpdate.selected) &&
        Objects.equals(this.value, sfODataFormCustomElementListValueUpdate.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listIndex, selected, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataFormCustomElementListValueUpdate {\n");
    
    sb.append("    listIndex: ").append(toIndentedString(listIndex)).append("\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
