/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataUpsertResultCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataUpsertResultCreate {
  @JsonProperty("editStatus")
  private String editStatus = null;

  @JsonProperty("httpCode")
  private Integer httpCode = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("key")
  private String key = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("innermessage@odata.bind")
  private String innermessageAtOdataBind = null;

  public SFODataUpsertResultCreate editStatus(String editStatus) {
    this.editStatus = editStatus;
    return this;
  }

   /**
   * Get editStatus
   * @return editStatus
  **/
  public String getEditStatus() {
    return editStatus;
  }

  public void setEditStatus(String editStatus) {
    this.editStatus = editStatus;
  }

  public SFODataUpsertResultCreate httpCode(Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  public SFODataUpsertResultCreate index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public SFODataUpsertResultCreate key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public SFODataUpsertResultCreate message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public SFODataUpsertResultCreate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SFODataUpsertResultCreate innermessageAtOdataBind(String innermessageAtOdataBind) {
    this.innermessageAtOdataBind = innermessageAtOdataBind;
    return this;
  }

   /**
   * Get innermessageAtOdataBind
   * @return innermessageAtOdataBind
  **/
  public String getInnermessageAtOdataBind() {
    return innermessageAtOdataBind;
  }

  public void setInnermessageAtOdataBind(String innermessageAtOdataBind) {
    this.innermessageAtOdataBind = innermessageAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataUpsertResultCreate sfODataUpsertResultCreate = (SFODataUpsertResultCreate) o;
    return Objects.equals(this.editStatus, sfODataUpsertResultCreate.editStatus) &&
        Objects.equals(this.httpCode, sfODataUpsertResultCreate.httpCode) &&
        Objects.equals(this.index, sfODataUpsertResultCreate.index) &&
        Objects.equals(this.key, sfODataUpsertResultCreate.key) &&
        Objects.equals(this.message, sfODataUpsertResultCreate.message) &&
        Objects.equals(this.status, sfODataUpsertResultCreate.status) &&
        Objects.equals(this.innermessageAtOdataBind, sfODataUpsertResultCreate.innermessageAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(editStatus, httpCode, index, key, message, status, innermessageAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataUpsertResultCreate {\n");
    
    sb.append("    editStatus: ").append(toIndentedString(editStatus)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    innermessageAtOdataBind: ").append(toIndentedString(innermessageAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
