/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataMultiplicity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataMultiplicity {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("symbolString")
  private String symbolString = null;

  public SFODataMultiplicity name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SFODataMultiplicity symbolString(String symbolString) {
    this.symbolString = symbolString;
    return this;
  }

   /**
   * Get symbolString
   * @return symbolString
  **/
  public String getSymbolString() {
    return symbolString;
  }

  public void setSymbolString(String symbolString) {
    this.symbolString = symbolString;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataMultiplicity sfODataMultiplicity = (SFODataMultiplicity) o;
    return Objects.equals(this.name, sfODataMultiplicity.name) &&
        Objects.equals(this.symbolString, sfODataMultiplicity.symbolString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, symbolString);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataMultiplicity {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbolString: ").append(toIndentedString(symbolString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
