/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataCustEMEAHRdataUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataCustEMEAHRdataUpdate {
  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("cust_amount")
  private String custAmount = null;

  @JsonProperty("cust_effdate")
  private OffsetDateTime custEffdate = null;

  @JsonProperty("cust_freet")
  private String custFreet = null;

  @JsonProperty("cust_freq")
  private String custFreq = null;

  @JsonProperty("cust_iPerform")
  private String custIPerform = null;

  @JsonProperty("cust_jobLevel")
  private String custJobLevel = null;

  @JsonProperty("cust_mperc")
  private AnyOfSFODataCustEMEAHRdataUpdateCustMperc custMperc = null;

  @JsonProperty("cust_scheme")
  private String custScheme = null;

  @JsonProperty("cust_type")
  private String custType = null;

  @JsonProperty("cust_varpay")
  private String custVarpay = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemEffectiveEndDate")
  private OffsetDateTime mdfSystemEffectiveEndDate = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  public SFODataCustEMEAHRdataUpdate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataCustEMEAHRdataUpdate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataCustEMEAHRdataUpdate custAmount(String custAmount) {
    this.custAmount = custAmount;
    return this;
  }

   /**
   * Get custAmount
   * @return custAmount
  **/
  public String getCustAmount() {
    return custAmount;
  }

  public void setCustAmount(String custAmount) {
    this.custAmount = custAmount;
  }

  public SFODataCustEMEAHRdataUpdate custEffdate(OffsetDateTime custEffdate) {
    this.custEffdate = custEffdate;
    return this;
  }

   /**
   * Get custEffdate
   * @return custEffdate
  **/
  public OffsetDateTime getCustEffdate() {
    return custEffdate;
  }

  public void setCustEffdate(OffsetDateTime custEffdate) {
    this.custEffdate = custEffdate;
  }

  public SFODataCustEMEAHRdataUpdate custFreet(String custFreet) {
    this.custFreet = custFreet;
    return this;
  }

   /**
   * Get custFreet
   * @return custFreet
  **/
  public String getCustFreet() {
    return custFreet;
  }

  public void setCustFreet(String custFreet) {
    this.custFreet = custFreet;
  }

  public SFODataCustEMEAHRdataUpdate custFreq(String custFreq) {
    this.custFreq = custFreq;
    return this;
  }

   /**
   * Get custFreq
   * @return custFreq
  **/
  public String getCustFreq() {
    return custFreq;
  }

  public void setCustFreq(String custFreq) {
    this.custFreq = custFreq;
  }

  public SFODataCustEMEAHRdataUpdate custIPerform(String custIPerform) {
    this.custIPerform = custIPerform;
    return this;
  }

   /**
   * Get custIPerform
   * @return custIPerform
  **/
  public String getCustIPerform() {
    return custIPerform;
  }

  public void setCustIPerform(String custIPerform) {
    this.custIPerform = custIPerform;
  }

  public SFODataCustEMEAHRdataUpdate custJobLevel(String custJobLevel) {
    this.custJobLevel = custJobLevel;
    return this;
  }

   /**
   * Get custJobLevel
   * @return custJobLevel
  **/
  public String getCustJobLevel() {
    return custJobLevel;
  }

  public void setCustJobLevel(String custJobLevel) {
    this.custJobLevel = custJobLevel;
  }

  public SFODataCustEMEAHRdataUpdate custMperc(AnyOfSFODataCustEMEAHRdataUpdateCustMperc custMperc) {
    this.custMperc = custMperc;
    return this;
  }

   /**
   * Get custMperc
   * @return custMperc
  **/
  public AnyOfSFODataCustEMEAHRdataUpdateCustMperc getCustMperc() {
    return custMperc;
  }

  public void setCustMperc(AnyOfSFODataCustEMEAHRdataUpdateCustMperc custMperc) {
    this.custMperc = custMperc;
  }

  public SFODataCustEMEAHRdataUpdate custScheme(String custScheme) {
    this.custScheme = custScheme;
    return this;
  }

   /**
   * Get custScheme
   * @return custScheme
  **/
  public String getCustScheme() {
    return custScheme;
  }

  public void setCustScheme(String custScheme) {
    this.custScheme = custScheme;
  }

  public SFODataCustEMEAHRdataUpdate custType(String custType) {
    this.custType = custType;
    return this;
  }

   /**
   * Get custType
   * @return custType
  **/
  public String getCustType() {
    return custType;
  }

  public void setCustType(String custType) {
    this.custType = custType;
  }

  public SFODataCustEMEAHRdataUpdate custVarpay(String custVarpay) {
    this.custVarpay = custVarpay;
    return this;
  }

   /**
   * Get custVarpay
   * @return custVarpay
  **/
  public String getCustVarpay() {
    return custVarpay;
  }

  public void setCustVarpay(String custVarpay) {
    this.custVarpay = custVarpay;
  }

  public SFODataCustEMEAHRdataUpdate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataCustEMEAHRdataUpdate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataCustEMEAHRdataUpdate mdfSystemEffectiveEndDate(OffsetDateTime mdfSystemEffectiveEndDate) {
    this.mdfSystemEffectiveEndDate = mdfSystemEffectiveEndDate;
    return this;
  }

   /**
   * Get mdfSystemEffectiveEndDate
   * @return mdfSystemEffectiveEndDate
  **/
  public OffsetDateTime getMdfSystemEffectiveEndDate() {
    return mdfSystemEffectiveEndDate;
  }

  public void setMdfSystemEffectiveEndDate(OffsetDateTime mdfSystemEffectiveEndDate) {
    this.mdfSystemEffectiveEndDate = mdfSystemEffectiveEndDate;
  }

  public SFODataCustEMEAHRdataUpdate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataCustEMEAHRdataUpdate sfODataCustEMEAHRdataUpdate = (SFODataCustEMEAHRdataUpdate) o;
    return Objects.equals(this.createdBy, sfODataCustEMEAHRdataUpdate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataCustEMEAHRdataUpdate.createdDateTime) &&
        Objects.equals(this.custAmount, sfODataCustEMEAHRdataUpdate.custAmount) &&
        Objects.equals(this.custEffdate, sfODataCustEMEAHRdataUpdate.custEffdate) &&
        Objects.equals(this.custFreet, sfODataCustEMEAHRdataUpdate.custFreet) &&
        Objects.equals(this.custFreq, sfODataCustEMEAHRdataUpdate.custFreq) &&
        Objects.equals(this.custIPerform, sfODataCustEMEAHRdataUpdate.custIPerform) &&
        Objects.equals(this.custJobLevel, sfODataCustEMEAHRdataUpdate.custJobLevel) &&
        Objects.equals(this.custMperc, sfODataCustEMEAHRdataUpdate.custMperc) &&
        Objects.equals(this.custScheme, sfODataCustEMEAHRdataUpdate.custScheme) &&
        Objects.equals(this.custType, sfODataCustEMEAHRdataUpdate.custType) &&
        Objects.equals(this.custVarpay, sfODataCustEMEAHRdataUpdate.custVarpay) &&
        Objects.equals(this.lastModifiedBy, sfODataCustEMEAHRdataUpdate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataCustEMEAHRdataUpdate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemEffectiveEndDate, sfODataCustEMEAHRdataUpdate.mdfSystemEffectiveEndDate) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataCustEMEAHRdataUpdate.mdfSystemRecordStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdBy, createdDateTime, custAmount, custEffdate, custFreet, custFreq, custIPerform, custJobLevel, custMperc, custScheme, custType, custVarpay, lastModifiedBy, lastModifiedDateTime, mdfSystemEffectiveEndDate, mdfSystemRecordStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataCustEMEAHRdataUpdate {\n");
    
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    custAmount: ").append(toIndentedString(custAmount)).append("\n");
    sb.append("    custEffdate: ").append(toIndentedString(custEffdate)).append("\n");
    sb.append("    custFreet: ").append(toIndentedString(custFreet)).append("\n");
    sb.append("    custFreq: ").append(toIndentedString(custFreq)).append("\n");
    sb.append("    custIPerform: ").append(toIndentedString(custIPerform)).append("\n");
    sb.append("    custJobLevel: ").append(toIndentedString(custJobLevel)).append("\n");
    sb.append("    custMperc: ").append(toIndentedString(custMperc)).append("\n");
    sb.append("    custScheme: ").append(toIndentedString(custScheme)).append("\n");
    sb.append("    custType: ").append(toIndentedString(custType)).append("\n");
    sb.append("    custVarpay: ").append(toIndentedString(custVarpay)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemEffectiveEndDate: ").append(toIndentedString(mdfSystemEffectiveEndDate)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
