/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.axonivy.connector.successfactors.connector.rest.Count;
import com.axonivy.connector.successfactors.connector.rest.SFODataMDFEnumValue;
import com.axonivy.connector.successfactors.connector.rest.SFODataPickListValueV2;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * SFODataPayPeriod
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataPayPeriod {
  @JsonProperty("PayCalendar_payGroup")
  private String payCalendarPayGroup = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataPayPeriodExternalCode externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("offcycle")
  private Boolean offcycle = null;

  @JsonProperty("payCheckIssueDate")
  private OffsetDateTime payCheckIssueDate = null;

  @JsonProperty("payPeriodBeginDate")
  private OffsetDateTime payPeriodBeginDate = null;

  @JsonProperty("payPeriodEndDate")
  private OffsetDateTime payPeriodEndDate = null;

  @JsonProperty("processingRunId")
  private String processingRunId = null;

  @JsonProperty("runType")
  private String runType = null;

  @JsonProperty("createdByNav")
  private AllOfSFODataPayPeriodCreatedByNav createdByNav = null;

  @JsonProperty("lastModifiedByNav")
  private AllOfSFODataPayPeriodLastModifiedByNav lastModifiedByNav = null;

  @JsonProperty("mdfSystemRecordStatusNav")
  private SFODataMDFEnumValue mdfSystemRecordStatusNav = null;

  @JsonProperty("runTypeNav")
  private List<SFODataPickListValueV2> runTypeNav = null;

  @JsonProperty("runTypeNav@odata.count")
  private Count runTypeNavAtOdataCount = null;

  public SFODataPayPeriod payCalendarPayGroup(String payCalendarPayGroup) {
    this.payCalendarPayGroup = payCalendarPayGroup;
    return this;
  }

   /**
   * Get payCalendarPayGroup
   * @return payCalendarPayGroup
  **/
  public String getPayCalendarPayGroup() {
    return payCalendarPayGroup;
  }

  public void setPayCalendarPayGroup(String payCalendarPayGroup) {
    this.payCalendarPayGroup = payCalendarPayGroup;
  }

  public SFODataPayPeriod createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataPayPeriod createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataPayPeriod externalCode(AnyOfSFODataPayPeriodExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataPayPeriodExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataPayPeriodExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataPayPeriod lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataPayPeriod lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataPayPeriod mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataPayPeriod offcycle(Boolean offcycle) {
    this.offcycle = offcycle;
    return this;
  }

   /**
   * Get offcycle
   * @return offcycle
  **/
  public Boolean isOffcycle() {
    return offcycle;
  }

  public void setOffcycle(Boolean offcycle) {
    this.offcycle = offcycle;
  }

  public SFODataPayPeriod payCheckIssueDate(OffsetDateTime payCheckIssueDate) {
    this.payCheckIssueDate = payCheckIssueDate;
    return this;
  }

   /**
   * Get payCheckIssueDate
   * @return payCheckIssueDate
  **/
  public OffsetDateTime getPayCheckIssueDate() {
    return payCheckIssueDate;
  }

  public void setPayCheckIssueDate(OffsetDateTime payCheckIssueDate) {
    this.payCheckIssueDate = payCheckIssueDate;
  }

  public SFODataPayPeriod payPeriodBeginDate(OffsetDateTime payPeriodBeginDate) {
    this.payPeriodBeginDate = payPeriodBeginDate;
    return this;
  }

   /**
   * Get payPeriodBeginDate
   * @return payPeriodBeginDate
  **/
  public OffsetDateTime getPayPeriodBeginDate() {
    return payPeriodBeginDate;
  }

  public void setPayPeriodBeginDate(OffsetDateTime payPeriodBeginDate) {
    this.payPeriodBeginDate = payPeriodBeginDate;
  }

  public SFODataPayPeriod payPeriodEndDate(OffsetDateTime payPeriodEndDate) {
    this.payPeriodEndDate = payPeriodEndDate;
    return this;
  }

   /**
   * Get payPeriodEndDate
   * @return payPeriodEndDate
  **/
  public OffsetDateTime getPayPeriodEndDate() {
    return payPeriodEndDate;
  }

  public void setPayPeriodEndDate(OffsetDateTime payPeriodEndDate) {
    this.payPeriodEndDate = payPeriodEndDate;
  }

  public SFODataPayPeriod processingRunId(String processingRunId) {
    this.processingRunId = processingRunId;
    return this;
  }

   /**
   * Get processingRunId
   * @return processingRunId
  **/
  public String getProcessingRunId() {
    return processingRunId;
  }

  public void setProcessingRunId(String processingRunId) {
    this.processingRunId = processingRunId;
  }

  public SFODataPayPeriod runType(String runType) {
    this.runType = runType;
    return this;
  }

   /**
   * Get runType
   * @return runType
  **/
  public String getRunType() {
    return runType;
  }

  public void setRunType(String runType) {
    this.runType = runType;
  }

  public SFODataPayPeriod createdByNav(AllOfSFODataPayPeriodCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
    return this;
  }

   /**
   * Get createdByNav
   * @return createdByNav
  **/
  public AllOfSFODataPayPeriodCreatedByNav getCreatedByNav() {
    return createdByNav;
  }

  public void setCreatedByNav(AllOfSFODataPayPeriodCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
  }

  public SFODataPayPeriod lastModifiedByNav(AllOfSFODataPayPeriodLastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
    return this;
  }

   /**
   * Get lastModifiedByNav
   * @return lastModifiedByNav
  **/
  public AllOfSFODataPayPeriodLastModifiedByNav getLastModifiedByNav() {
    return lastModifiedByNav;
  }

  public void setLastModifiedByNav(AllOfSFODataPayPeriodLastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
  }

  public SFODataPayPeriod mdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNav
   * @return mdfSystemRecordStatusNav
  **/
  public SFODataMDFEnumValue getMdfSystemRecordStatusNav() {
    return mdfSystemRecordStatusNav;
  }

  public void setMdfSystemRecordStatusNav(SFODataMDFEnumValue mdfSystemRecordStatusNav) {
    this.mdfSystemRecordStatusNav = mdfSystemRecordStatusNav;
  }

  public SFODataPayPeriod runTypeNav(List<SFODataPickListValueV2> runTypeNav) {
    this.runTypeNav = runTypeNav;
    return this;
  }

  public SFODataPayPeriod addRunTypeNavItem(SFODataPickListValueV2 runTypeNavItem) {
    if (this.runTypeNav == null) {
      this.runTypeNav = new ArrayList<>();
    }
    this.runTypeNav.add(runTypeNavItem);
    return this;
  }

   /**
   * Get runTypeNav
   * @return runTypeNav
  **/
  public List<SFODataPickListValueV2> getRunTypeNav() {
    return runTypeNav;
  }

  public void setRunTypeNav(List<SFODataPickListValueV2> runTypeNav) {
    this.runTypeNav = runTypeNav;
  }

  public SFODataPayPeriod runTypeNavAtOdataCount(Count runTypeNavAtOdataCount) {
    this.runTypeNavAtOdataCount = runTypeNavAtOdataCount;
    return this;
  }

   /**
   * Get runTypeNavAtOdataCount
   * @return runTypeNavAtOdataCount
  **/
  public Count getRunTypeNavAtOdataCount() {
    return runTypeNavAtOdataCount;
  }

  public void setRunTypeNavAtOdataCount(Count runTypeNavAtOdataCount) {
    this.runTypeNavAtOdataCount = runTypeNavAtOdataCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataPayPeriod sfODataPayPeriod = (SFODataPayPeriod) o;
    return Objects.equals(this.payCalendarPayGroup, sfODataPayPeriod.payCalendarPayGroup) &&
        Objects.equals(this.createdBy, sfODataPayPeriod.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataPayPeriod.createdDateTime) &&
        Objects.equals(this.externalCode, sfODataPayPeriod.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataPayPeriod.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataPayPeriod.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataPayPeriod.mdfSystemRecordStatus) &&
        Objects.equals(this.offcycle, sfODataPayPeriod.offcycle) &&
        Objects.equals(this.payCheckIssueDate, sfODataPayPeriod.payCheckIssueDate) &&
        Objects.equals(this.payPeriodBeginDate, sfODataPayPeriod.payPeriodBeginDate) &&
        Objects.equals(this.payPeriodEndDate, sfODataPayPeriod.payPeriodEndDate) &&
        Objects.equals(this.processingRunId, sfODataPayPeriod.processingRunId) &&
        Objects.equals(this.runType, sfODataPayPeriod.runType) &&
        Objects.equals(this.createdByNav, sfODataPayPeriod.createdByNav) &&
        Objects.equals(this.lastModifiedByNav, sfODataPayPeriod.lastModifiedByNav) &&
        Objects.equals(this.mdfSystemRecordStatusNav, sfODataPayPeriod.mdfSystemRecordStatusNav) &&
        Objects.equals(this.runTypeNav, sfODataPayPeriod.runTypeNav) &&
        Objects.equals(this.runTypeNavAtOdataCount, sfODataPayPeriod.runTypeNavAtOdataCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payCalendarPayGroup, createdBy, createdDateTime, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, offcycle, payCheckIssueDate, payPeriodBeginDate, payPeriodEndDate, processingRunId, runType, createdByNav, lastModifiedByNav, mdfSystemRecordStatusNav, runTypeNav, runTypeNavAtOdataCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataPayPeriod {\n");
    
    sb.append("    payCalendarPayGroup: ").append(toIndentedString(payCalendarPayGroup)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    offcycle: ").append(toIndentedString(offcycle)).append("\n");
    sb.append("    payCheckIssueDate: ").append(toIndentedString(payCheckIssueDate)).append("\n");
    sb.append("    payPeriodBeginDate: ").append(toIndentedString(payPeriodBeginDate)).append("\n");
    sb.append("    payPeriodEndDate: ").append(toIndentedString(payPeriodEndDate)).append("\n");
    sb.append("    processingRunId: ").append(toIndentedString(processingRunId)).append("\n");
    sb.append("    runType: ").append(toIndentedString(runType)).append("\n");
    sb.append("    createdByNav: ").append(toIndentedString(createdByNav)).append("\n");
    sb.append("    lastModifiedByNav: ").append(toIndentedString(lastModifiedByNav)).append("\n");
    sb.append("    mdfSystemRecordStatusNav: ").append(toIndentedString(mdfSystemRecordStatusNav)).append("\n");
    sb.append("    runTypeNav: ").append(toIndentedString(runTypeNav)).append("\n");
    sb.append("    runTypeNavAtOdataCount: ").append(toIndentedString(runTypeNavAtOdataCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
