/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataTemporaryTimeInformationCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataTemporaryTimeInformationCreate {
  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("dayModel")
  private String dayModel = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("entityUUID")
  private String entityUUID = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("mdfSystemStatus")
  private String mdfSystemStatus = null;

  @JsonProperty("recordId")
  private String recordId = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("workSchedule")
  private String workSchedule = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  @JsonProperty("mdfSystemStatusNav@odata.bind")
  private String mdfSystemStatusNavAtOdataBind = null;

  @JsonProperty("userIdNav@odata.bind")
  private String userIdNavAtOdataBind = null;

  public SFODataTemporaryTimeInformationCreate comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public SFODataTemporaryTimeInformationCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataTemporaryTimeInformationCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataTemporaryTimeInformationCreate dayModel(String dayModel) {
    this.dayModel = dayModel;
    return this;
  }

   /**
   * Get dayModel
   * @return dayModel
  **/
  public String getDayModel() {
    return dayModel;
  }

  public void setDayModel(String dayModel) {
    this.dayModel = dayModel;
  }

  public SFODataTemporaryTimeInformationCreate endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataTemporaryTimeInformationCreate entityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
    return this;
  }

   /**
   * Get entityUUID
   * @return entityUUID
  **/
  public String getEntityUUID() {
    return entityUUID;
  }

  public void setEntityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
  }

  public SFODataTemporaryTimeInformationCreate externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataTemporaryTimeInformationCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataTemporaryTimeInformationCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataTemporaryTimeInformationCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataTemporaryTimeInformationCreate mdfSystemStatus(String mdfSystemStatus) {
    this.mdfSystemStatus = mdfSystemStatus;
    return this;
  }

   /**
   * Get mdfSystemStatus
   * @return mdfSystemStatus
  **/
  public String getMdfSystemStatus() {
    return mdfSystemStatus;
  }

  public void setMdfSystemStatus(String mdfSystemStatus) {
    this.mdfSystemStatus = mdfSystemStatus;
  }

  public SFODataTemporaryTimeInformationCreate recordId(String recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * Get recordId
   * @return recordId
  **/
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(String recordId) {
    this.recordId = recordId;
  }

  public SFODataTemporaryTimeInformationCreate startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SFODataTemporaryTimeInformationCreate userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public SFODataTemporaryTimeInformationCreate workSchedule(String workSchedule) {
    this.workSchedule = workSchedule;
    return this;
  }

   /**
   * Get workSchedule
   * @return workSchedule
  **/
  public String getWorkSchedule() {
    return workSchedule;
  }

  public void setWorkSchedule(String workSchedule) {
    this.workSchedule = workSchedule;
  }

  public SFODataTemporaryTimeInformationCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }

  public SFODataTemporaryTimeInformationCreate mdfSystemStatusNavAtOdataBind(String mdfSystemStatusNavAtOdataBind) {
    this.mdfSystemStatusNavAtOdataBind = mdfSystemStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemStatusNavAtOdataBind
   * @return mdfSystemStatusNavAtOdataBind
  **/
  public String getMdfSystemStatusNavAtOdataBind() {
    return mdfSystemStatusNavAtOdataBind;
  }

  public void setMdfSystemStatusNavAtOdataBind(String mdfSystemStatusNavAtOdataBind) {
    this.mdfSystemStatusNavAtOdataBind = mdfSystemStatusNavAtOdataBind;
  }

  public SFODataTemporaryTimeInformationCreate userIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
    return this;
  }

   /**
   * Get userIdNavAtOdataBind
   * @return userIdNavAtOdataBind
  **/
  public String getUserIdNavAtOdataBind() {
    return userIdNavAtOdataBind;
  }

  public void setUserIdNavAtOdataBind(String userIdNavAtOdataBind) {
    this.userIdNavAtOdataBind = userIdNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataTemporaryTimeInformationCreate sfODataTemporaryTimeInformationCreate = (SFODataTemporaryTimeInformationCreate) o;
    return Objects.equals(this.comment, sfODataTemporaryTimeInformationCreate.comment) &&
        Objects.equals(this.createdBy, sfODataTemporaryTimeInformationCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataTemporaryTimeInformationCreate.createdDateTime) &&
        Objects.equals(this.dayModel, sfODataTemporaryTimeInformationCreate.dayModel) &&
        Objects.equals(this.endDate, sfODataTemporaryTimeInformationCreate.endDate) &&
        Objects.equals(this.entityUUID, sfODataTemporaryTimeInformationCreate.entityUUID) &&
        Objects.equals(this.externalCode, sfODataTemporaryTimeInformationCreate.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataTemporaryTimeInformationCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataTemporaryTimeInformationCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataTemporaryTimeInformationCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.mdfSystemStatus, sfODataTemporaryTimeInformationCreate.mdfSystemStatus) &&
        Objects.equals(this.recordId, sfODataTemporaryTimeInformationCreate.recordId) &&
        Objects.equals(this.startDate, sfODataTemporaryTimeInformationCreate.startDate) &&
        Objects.equals(this.userId, sfODataTemporaryTimeInformationCreate.userId) &&
        Objects.equals(this.workSchedule, sfODataTemporaryTimeInformationCreate.workSchedule) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataTemporaryTimeInformationCreate.mdfSystemRecordStatusNavAtOdataBind) &&
        Objects.equals(this.mdfSystemStatusNavAtOdataBind, sfODataTemporaryTimeInformationCreate.mdfSystemStatusNavAtOdataBind) &&
        Objects.equals(this.userIdNavAtOdataBind, sfODataTemporaryTimeInformationCreate.userIdNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, createdBy, createdDateTime, dayModel, endDate, entityUUID, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, mdfSystemStatus, recordId, startDate, userId, workSchedule, mdfSystemRecordStatusNavAtOdataBind, mdfSystemStatusNavAtOdataBind, userIdNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataTemporaryTimeInformationCreate {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    dayModel: ").append(toIndentedString(dayModel)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    entityUUID: ").append(toIndentedString(entityUUID)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    mdfSystemStatus: ").append(toIndentedString(mdfSystemStatus)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    workSchedule: ").append(toIndentedString(workSchedule)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("    mdfSystemStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemStatusNavAtOdataBind)).append("\n");
    sb.append("    userIdNavAtOdataBind: ").append(toIndentedString(userIdNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
