/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SFODataTodoActionCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataTodoActionCreate {
  @JsonProperty("actionId")
  private Integer actionId = null;

  @JsonProperty("actionName")
  private String actionName = null;

  @JsonProperty("categoryId")
  private String categoryId = null;

  @JsonProperty("functionImportName")
  private String functionImportName = null;

  @JsonProperty("categoryNav@odata.bind")
  private String categoryNavAtOdataBind = null;

  public SFODataTodoActionCreate actionId(Integer actionId) {
    this.actionId = actionId;
    return this;
  }

   /**
   * Get actionId
   * @return actionId
  **/
  public Integer getActionId() {
    return actionId;
  }

  public void setActionId(Integer actionId) {
    this.actionId = actionId;
  }

  public SFODataTodoActionCreate actionName(String actionName) {
    this.actionName = actionName;
    return this;
  }

   /**
   * Get actionName
   * @return actionName
  **/
  public String getActionName() {
    return actionName;
  }

  public void setActionName(String actionName) {
    this.actionName = actionName;
  }

  public SFODataTodoActionCreate categoryId(String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Get categoryId
   * @return categoryId
  **/
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  public SFODataTodoActionCreate functionImportName(String functionImportName) {
    this.functionImportName = functionImportName;
    return this;
  }

   /**
   * Get functionImportName
   * @return functionImportName
  **/
  public String getFunctionImportName() {
    return functionImportName;
  }

  public void setFunctionImportName(String functionImportName) {
    this.functionImportName = functionImportName;
  }

  public SFODataTodoActionCreate categoryNavAtOdataBind(String categoryNavAtOdataBind) {
    this.categoryNavAtOdataBind = categoryNavAtOdataBind;
    return this;
  }

   /**
   * Get categoryNavAtOdataBind
   * @return categoryNavAtOdataBind
  **/
  public String getCategoryNavAtOdataBind() {
    return categoryNavAtOdataBind;
  }

  public void setCategoryNavAtOdataBind(String categoryNavAtOdataBind) {
    this.categoryNavAtOdataBind = categoryNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataTodoActionCreate sfODataTodoActionCreate = (SFODataTodoActionCreate) o;
    return Objects.equals(this.actionId, sfODataTodoActionCreate.actionId) &&
        Objects.equals(this.actionName, sfODataTodoActionCreate.actionName) &&
        Objects.equals(this.categoryId, sfODataTodoActionCreate.categoryId) &&
        Objects.equals(this.functionImportName, sfODataTodoActionCreate.functionImportName) &&
        Objects.equals(this.categoryNavAtOdataBind, sfODataTodoActionCreate.categoryNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionId, actionName, categoryId, functionImportName, categoryNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataTodoActionCreate {\n");
    
    sb.append("    actionId: ").append(toIndentedString(actionId)).append("\n");
    sb.append("    actionName: ").append(toIndentedString(actionName)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    functionImportName: ").append(toIndentedString(functionImportName)).append("\n");
    sb.append("    categoryNavAtOdataBind: ").append(toIndentedString(categoryNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
