/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataTimeAccountTypeAUSCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataTimeAccountTypeAUSCreate {
  @JsonProperty("TimeAccountType_externalCode")
  private String timeAccountTypeExternalCode = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("entityUUID")
  private String entityUUID = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataTimeAccountTypeAUSCreateExternalCode externalCode = null;

  @JsonProperty("includeInLeaveLoadingCalculations")
  private Boolean includeInLeaveLoadingCalculations = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("priorServiceAccountDistinction")
  private String priorServiceAccountDistinction = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  @JsonProperty("priorServiceAccountDistinctionNav@odata.bind")
  private String priorServiceAccountDistinctionNavAtOdataBind = null;

  public SFODataTimeAccountTypeAUSCreate timeAccountTypeExternalCode(String timeAccountTypeExternalCode) {
    this.timeAccountTypeExternalCode = timeAccountTypeExternalCode;
    return this;
  }

   /**
   * Get timeAccountTypeExternalCode
   * @return timeAccountTypeExternalCode
  **/
  public String getTimeAccountTypeExternalCode() {
    return timeAccountTypeExternalCode;
  }

  public void setTimeAccountTypeExternalCode(String timeAccountTypeExternalCode) {
    this.timeAccountTypeExternalCode = timeAccountTypeExternalCode;
  }

  public SFODataTimeAccountTypeAUSCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataTimeAccountTypeAUSCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataTimeAccountTypeAUSCreate entityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
    return this;
  }

   /**
   * Get entityUUID
   * @return entityUUID
  **/
  public String getEntityUUID() {
    return entityUUID;
  }

  public void setEntityUUID(String entityUUID) {
    this.entityUUID = entityUUID;
  }

  public SFODataTimeAccountTypeAUSCreate externalCode(AnyOfSFODataTimeAccountTypeAUSCreateExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataTimeAccountTypeAUSCreateExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataTimeAccountTypeAUSCreateExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataTimeAccountTypeAUSCreate includeInLeaveLoadingCalculations(Boolean includeInLeaveLoadingCalculations) {
    this.includeInLeaveLoadingCalculations = includeInLeaveLoadingCalculations;
    return this;
  }

   /**
   * Get includeInLeaveLoadingCalculations
   * @return includeInLeaveLoadingCalculations
  **/
  public Boolean isIncludeInLeaveLoadingCalculations() {
    return includeInLeaveLoadingCalculations;
  }

  public void setIncludeInLeaveLoadingCalculations(Boolean includeInLeaveLoadingCalculations) {
    this.includeInLeaveLoadingCalculations = includeInLeaveLoadingCalculations;
  }

  public SFODataTimeAccountTypeAUSCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataTimeAccountTypeAUSCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataTimeAccountTypeAUSCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataTimeAccountTypeAUSCreate priorServiceAccountDistinction(String priorServiceAccountDistinction) {
    this.priorServiceAccountDistinction = priorServiceAccountDistinction;
    return this;
  }

   /**
   * Get priorServiceAccountDistinction
   * @return priorServiceAccountDistinction
  **/
  public String getPriorServiceAccountDistinction() {
    return priorServiceAccountDistinction;
  }

  public void setPriorServiceAccountDistinction(String priorServiceAccountDistinction) {
    this.priorServiceAccountDistinction = priorServiceAccountDistinction;
  }

  public SFODataTimeAccountTypeAUSCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }

  public SFODataTimeAccountTypeAUSCreate priorServiceAccountDistinctionNavAtOdataBind(String priorServiceAccountDistinctionNavAtOdataBind) {
    this.priorServiceAccountDistinctionNavAtOdataBind = priorServiceAccountDistinctionNavAtOdataBind;
    return this;
  }

   /**
   * Get priorServiceAccountDistinctionNavAtOdataBind
   * @return priorServiceAccountDistinctionNavAtOdataBind
  **/
  public String getPriorServiceAccountDistinctionNavAtOdataBind() {
    return priorServiceAccountDistinctionNavAtOdataBind;
  }

  public void setPriorServiceAccountDistinctionNavAtOdataBind(String priorServiceAccountDistinctionNavAtOdataBind) {
    this.priorServiceAccountDistinctionNavAtOdataBind = priorServiceAccountDistinctionNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataTimeAccountTypeAUSCreate sfODataTimeAccountTypeAUSCreate = (SFODataTimeAccountTypeAUSCreate) o;
    return Objects.equals(this.timeAccountTypeExternalCode, sfODataTimeAccountTypeAUSCreate.timeAccountTypeExternalCode) &&
        Objects.equals(this.createdBy, sfODataTimeAccountTypeAUSCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataTimeAccountTypeAUSCreate.createdDateTime) &&
        Objects.equals(this.entityUUID, sfODataTimeAccountTypeAUSCreate.entityUUID) &&
        Objects.equals(this.externalCode, sfODataTimeAccountTypeAUSCreate.externalCode) &&
        Objects.equals(this.includeInLeaveLoadingCalculations, sfODataTimeAccountTypeAUSCreate.includeInLeaveLoadingCalculations) &&
        Objects.equals(this.lastModifiedBy, sfODataTimeAccountTypeAUSCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataTimeAccountTypeAUSCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataTimeAccountTypeAUSCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.priorServiceAccountDistinction, sfODataTimeAccountTypeAUSCreate.priorServiceAccountDistinction) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataTimeAccountTypeAUSCreate.mdfSystemRecordStatusNavAtOdataBind) &&
        Objects.equals(this.priorServiceAccountDistinctionNavAtOdataBind, sfODataTimeAccountTypeAUSCreate.priorServiceAccountDistinctionNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeAccountTypeExternalCode, createdBy, createdDateTime, entityUUID, externalCode, includeInLeaveLoadingCalculations, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, priorServiceAccountDistinction, mdfSystemRecordStatusNavAtOdataBind, priorServiceAccountDistinctionNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataTimeAccountTypeAUSCreate {\n");
    
    sb.append("    timeAccountTypeExternalCode: ").append(toIndentedString(timeAccountTypeExternalCode)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    entityUUID: ").append(toIndentedString(entityUUID)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    includeInLeaveLoadingCalculations: ").append(toIndentedString(includeInLeaveLoadingCalculations)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    priorServiceAccountDistinction: ").append(toIndentedString(priorServiceAccountDistinction)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("    priorServiceAccountDistinctionNavAtOdataBind: ").append(toIndentedString(priorServiceAccountDistinctionNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
