/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataFOLegalEntityLocalDEU
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataFOLegalEntityLocalDEU {
  @JsonProperty("country")
  private String country = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("externalCode")
  private String externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("mdfSystemRecordId")
  private String mdfSystemRecordId = null;

  @JsonProperty("socialAccidentInsurance")
  private String socialAccidentInsurance = null;

  @JsonProperty("socialAccidentInsuranceRegistrationNumber")
  private String socialAccidentInsuranceRegistrationNumber = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("taxUnit")
  private String taxUnit = null;

  @JsonProperty("countryNav")
  private AllOfSFODataFOLegalEntityLocalDEUCountryNav countryNav = null;

  @JsonProperty("createdByNav")
  private AllOfSFODataFOLegalEntityLocalDEUCreatedByNav createdByNav = null;

  @JsonProperty("lastModifiedByNav")
  private AllOfSFODataFOLegalEntityLocalDEULastModifiedByNav lastModifiedByNav = null;

  public SFODataFOLegalEntityLocalDEU country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public SFODataFOLegalEntityLocalDEU createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataFOLegalEntityLocalDEU createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataFOLegalEntityLocalDEU createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataFOLegalEntityLocalDEU endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataFOLegalEntityLocalDEU externalCode(String externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public String getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(String externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataFOLegalEntityLocalDEU lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataFOLegalEntityLocalDEU lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataFOLegalEntityLocalDEU lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataFOLegalEntityLocalDEU mdfSystemRecordId(String mdfSystemRecordId) {
    this.mdfSystemRecordId = mdfSystemRecordId;
    return this;
  }

   /**
   * Get mdfSystemRecordId
   * @return mdfSystemRecordId
  **/
  public String getMdfSystemRecordId() {
    return mdfSystemRecordId;
  }

  public void setMdfSystemRecordId(String mdfSystemRecordId) {
    this.mdfSystemRecordId = mdfSystemRecordId;
  }

  public SFODataFOLegalEntityLocalDEU socialAccidentInsurance(String socialAccidentInsurance) {
    this.socialAccidentInsurance = socialAccidentInsurance;
    return this;
  }

   /**
   * Get socialAccidentInsurance
   * @return socialAccidentInsurance
  **/
  public String getSocialAccidentInsurance() {
    return socialAccidentInsurance;
  }

  public void setSocialAccidentInsurance(String socialAccidentInsurance) {
    this.socialAccidentInsurance = socialAccidentInsurance;
  }

  public SFODataFOLegalEntityLocalDEU socialAccidentInsuranceRegistrationNumber(String socialAccidentInsuranceRegistrationNumber) {
    this.socialAccidentInsuranceRegistrationNumber = socialAccidentInsuranceRegistrationNumber;
    return this;
  }

   /**
   * Get socialAccidentInsuranceRegistrationNumber
   * @return socialAccidentInsuranceRegistrationNumber
  **/
  public String getSocialAccidentInsuranceRegistrationNumber() {
    return socialAccidentInsuranceRegistrationNumber;
  }

  public void setSocialAccidentInsuranceRegistrationNumber(String socialAccidentInsuranceRegistrationNumber) {
    this.socialAccidentInsuranceRegistrationNumber = socialAccidentInsuranceRegistrationNumber;
  }

  public SFODataFOLegalEntityLocalDEU startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public SFODataFOLegalEntityLocalDEU status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SFODataFOLegalEntityLocalDEU taxUnit(String taxUnit) {
    this.taxUnit = taxUnit;
    return this;
  }

   /**
   * Get taxUnit
   * @return taxUnit
  **/
  public String getTaxUnit() {
    return taxUnit;
  }

  public void setTaxUnit(String taxUnit) {
    this.taxUnit = taxUnit;
  }

  public SFODataFOLegalEntityLocalDEU countryNav(AllOfSFODataFOLegalEntityLocalDEUCountryNav countryNav) {
    this.countryNav = countryNav;
    return this;
  }

   /**
   * Get countryNav
   * @return countryNav
  **/
  public AllOfSFODataFOLegalEntityLocalDEUCountryNav getCountryNav() {
    return countryNav;
  }

  public void setCountryNav(AllOfSFODataFOLegalEntityLocalDEUCountryNav countryNav) {
    this.countryNav = countryNav;
  }

  public SFODataFOLegalEntityLocalDEU createdByNav(AllOfSFODataFOLegalEntityLocalDEUCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
    return this;
  }

   /**
   * Get createdByNav
   * @return createdByNav
  **/
  public AllOfSFODataFOLegalEntityLocalDEUCreatedByNav getCreatedByNav() {
    return createdByNav;
  }

  public void setCreatedByNav(AllOfSFODataFOLegalEntityLocalDEUCreatedByNav createdByNav) {
    this.createdByNav = createdByNav;
  }

  public SFODataFOLegalEntityLocalDEU lastModifiedByNav(AllOfSFODataFOLegalEntityLocalDEULastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
    return this;
  }

   /**
   * Get lastModifiedByNav
   * @return lastModifiedByNav
  **/
  public AllOfSFODataFOLegalEntityLocalDEULastModifiedByNav getLastModifiedByNav() {
    return lastModifiedByNav;
  }

  public void setLastModifiedByNav(AllOfSFODataFOLegalEntityLocalDEULastModifiedByNav lastModifiedByNav) {
    this.lastModifiedByNav = lastModifiedByNav;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataFOLegalEntityLocalDEU sfODataFOLegalEntityLocalDEU = (SFODataFOLegalEntityLocalDEU) o;
    return Objects.equals(this.country, sfODataFOLegalEntityLocalDEU.country) &&
        Objects.equals(this.createdBy, sfODataFOLegalEntityLocalDEU.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataFOLegalEntityLocalDEU.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataFOLegalEntityLocalDEU.createdOn) &&
        Objects.equals(this.endDate, sfODataFOLegalEntityLocalDEU.endDate) &&
        Objects.equals(this.externalCode, sfODataFOLegalEntityLocalDEU.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataFOLegalEntityLocalDEU.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataFOLegalEntityLocalDEU.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataFOLegalEntityLocalDEU.lastModifiedOn) &&
        Objects.equals(this.mdfSystemRecordId, sfODataFOLegalEntityLocalDEU.mdfSystemRecordId) &&
        Objects.equals(this.socialAccidentInsurance, sfODataFOLegalEntityLocalDEU.socialAccidentInsurance) &&
        Objects.equals(this.socialAccidentInsuranceRegistrationNumber, sfODataFOLegalEntityLocalDEU.socialAccidentInsuranceRegistrationNumber) &&
        Objects.equals(this.startDate, sfODataFOLegalEntityLocalDEU.startDate) &&
        Objects.equals(this.status, sfODataFOLegalEntityLocalDEU.status) &&
        Objects.equals(this.taxUnit, sfODataFOLegalEntityLocalDEU.taxUnit) &&
        Objects.equals(this.countryNav, sfODataFOLegalEntityLocalDEU.countryNav) &&
        Objects.equals(this.createdByNav, sfODataFOLegalEntityLocalDEU.createdByNav) &&
        Objects.equals(this.lastModifiedByNav, sfODataFOLegalEntityLocalDEU.lastModifiedByNav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, createdBy, createdDateTime, createdOn, endDate, externalCode, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, mdfSystemRecordId, socialAccidentInsurance, socialAccidentInsuranceRegistrationNumber, startDate, status, taxUnit, countryNav, createdByNav, lastModifiedByNav);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataFOLegalEntityLocalDEU {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    mdfSystemRecordId: ").append(toIndentedString(mdfSystemRecordId)).append("\n");
    sb.append("    socialAccidentInsurance: ").append(toIndentedString(socialAccidentInsurance)).append("\n");
    sb.append("    socialAccidentInsuranceRegistrationNumber: ").append(toIndentedString(socialAccidentInsuranceRegistrationNumber)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    taxUnit: ").append(toIndentedString(taxUnit)).append("\n");
    sb.append("    countryNav: ").append(toIndentedString(countryNav)).append("\n");
    sb.append("    createdByNav: ").append(toIndentedString(createdByNav)).append("\n");
    sb.append("    lastModifiedByNav: ").append(toIndentedString(lastModifiedByNav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
