/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataCustomPayTypeAssignmentCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataCustomPayTypeAssignmentCreate {
  @JsonProperty("CustomPayType_externalCode")
  private String customPayTypeExternalCode = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("externalCode")
  private AnyOfSFODataCustomPayTypeAssignmentCreateExternalCode externalCode = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("mdfSystemRecordStatus")
  private String mdfSystemRecordStatus = null;

  @JsonProperty("mdfSystemRecordStatusNav@odata.bind")
  private String mdfSystemRecordStatusNavAtOdataBind = null;

  public SFODataCustomPayTypeAssignmentCreate customPayTypeExternalCode(String customPayTypeExternalCode) {
    this.customPayTypeExternalCode = customPayTypeExternalCode;
    return this;
  }

   /**
   * Get customPayTypeExternalCode
   * @return customPayTypeExternalCode
  **/
  public String getCustomPayTypeExternalCode() {
    return customPayTypeExternalCode;
  }

  public void setCustomPayTypeExternalCode(String customPayTypeExternalCode) {
    this.customPayTypeExternalCode = customPayTypeExternalCode;
  }

  public SFODataCustomPayTypeAssignmentCreate country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public SFODataCustomPayTypeAssignmentCreate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataCustomPayTypeAssignmentCreate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataCustomPayTypeAssignmentCreate externalCode(AnyOfSFODataCustomPayTypeAssignmentCreateExternalCode externalCode) {
    this.externalCode = externalCode;
    return this;
  }

   /**
   * Get externalCode
   * @return externalCode
  **/
  public AnyOfSFODataCustomPayTypeAssignmentCreateExternalCode getExternalCode() {
    return externalCode;
  }

  public void setExternalCode(AnyOfSFODataCustomPayTypeAssignmentCreateExternalCode externalCode) {
    this.externalCode = externalCode;
  }

  public SFODataCustomPayTypeAssignmentCreate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataCustomPayTypeAssignmentCreate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataCustomPayTypeAssignmentCreate mdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
    return this;
  }

   /**
   * Get mdfSystemRecordStatus
   * @return mdfSystemRecordStatus
  **/
  public String getMdfSystemRecordStatus() {
    return mdfSystemRecordStatus;
  }

  public void setMdfSystemRecordStatus(String mdfSystemRecordStatus) {
    this.mdfSystemRecordStatus = mdfSystemRecordStatus;
  }

  public SFODataCustomPayTypeAssignmentCreate mdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
    return this;
  }

   /**
   * Get mdfSystemRecordStatusNavAtOdataBind
   * @return mdfSystemRecordStatusNavAtOdataBind
  **/
  public String getMdfSystemRecordStatusNavAtOdataBind() {
    return mdfSystemRecordStatusNavAtOdataBind;
  }

  public void setMdfSystemRecordStatusNavAtOdataBind(String mdfSystemRecordStatusNavAtOdataBind) {
    this.mdfSystemRecordStatusNavAtOdataBind = mdfSystemRecordStatusNavAtOdataBind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataCustomPayTypeAssignmentCreate sfODataCustomPayTypeAssignmentCreate = (SFODataCustomPayTypeAssignmentCreate) o;
    return Objects.equals(this.customPayTypeExternalCode, sfODataCustomPayTypeAssignmentCreate.customPayTypeExternalCode) &&
        Objects.equals(this.country, sfODataCustomPayTypeAssignmentCreate.country) &&
        Objects.equals(this.createdBy, sfODataCustomPayTypeAssignmentCreate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataCustomPayTypeAssignmentCreate.createdDateTime) &&
        Objects.equals(this.externalCode, sfODataCustomPayTypeAssignmentCreate.externalCode) &&
        Objects.equals(this.lastModifiedBy, sfODataCustomPayTypeAssignmentCreate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataCustomPayTypeAssignmentCreate.lastModifiedDateTime) &&
        Objects.equals(this.mdfSystemRecordStatus, sfODataCustomPayTypeAssignmentCreate.mdfSystemRecordStatus) &&
        Objects.equals(this.mdfSystemRecordStatusNavAtOdataBind, sfODataCustomPayTypeAssignmentCreate.mdfSystemRecordStatusNavAtOdataBind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customPayTypeExternalCode, country, createdBy, createdDateTime, externalCode, lastModifiedBy, lastModifiedDateTime, mdfSystemRecordStatus, mdfSystemRecordStatusNavAtOdataBind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataCustomPayTypeAssignmentCreate {\n");
    
    sb.append("    customPayTypeExternalCode: ").append(toIndentedString(customPayTypeExternalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    mdfSystemRecordStatus: ").append(toIndentedString(mdfSystemRecordStatus)).append("\n");
    sb.append("    mdfSystemRecordStatusNavAtOdataBind: ").append(toIndentedString(mdfSystemRecordStatusNavAtOdataBind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
