/*
 * 
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.successfactors.connector.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * SFODataEmpEmploymentUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-06T17:23:28.209073400+07:00[Asia/Bangkok]")
public class SFODataEmpEmploymentUpdate {
  @JsonProperty("assignmentClass")
  private String assignmentClass = null;

  @JsonProperty("assignmentIdExternal")
  private String assignmentIdExternal = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("createdDateTime")
  private OffsetDateTime createdDateTime = null;

  @JsonProperty("createdOn")
  private OffsetDateTime createdOn = null;

  @JsonProperty("customDate10")
  private OffsetDateTime customDate10 = null;

  @JsonProperty("customDate11")
  private OffsetDateTime customDate11 = null;

  @JsonProperty("customDate12")
  private OffsetDateTime customDate12 = null;

  @JsonProperty("customDate6")
  private OffsetDateTime customDate6 = null;

  @JsonProperty("customDate7")
  private OffsetDateTime customDate7 = null;

  @JsonProperty("customDate8")
  private OffsetDateTime customDate8 = null;

  @JsonProperty("customDate9")
  private OffsetDateTime customDate9 = null;

  @JsonProperty("endDate")
  private OffsetDateTime endDate = null;

  @JsonProperty("hiringNotCompleted")
  private Boolean hiringNotCompleted = null;

  @JsonProperty("includeAllRecords")
  private Boolean includeAllRecords = null;

  @JsonProperty("isECRecord")
  private Boolean isECRecord = null;

  @JsonProperty("isPrimary")
  private Boolean isPrimary = null;

  @JsonProperty("jobNumber")
  private AnyOfSFODataEmpEmploymentUpdateJobNumber jobNumber = null;

  @JsonProperty("lastDateWorked")
  private OffsetDateTime lastDateWorked = null;

  @JsonProperty("lastModifiedBy")
  private String lastModifiedBy = null;

  @JsonProperty("lastModifiedDateTime")
  private OffsetDateTime lastModifiedDateTime = null;

  @JsonProperty("lastModifiedOn")
  private OffsetDateTime lastModifiedOn = null;

  @JsonProperty("notes")
  private String notes = null;

  @JsonProperty("okToRehire")
  private Boolean okToRehire = null;

  @JsonProperty("originalStartDate")
  private OffsetDateTime originalStartDate = null;

  @JsonProperty("serviceDate")
  private OffsetDateTime serviceDate = null;

  @JsonProperty("startDate")
  private OffsetDateTime startDate = null;

  public SFODataEmpEmploymentUpdate assignmentClass(String assignmentClass) {
    this.assignmentClass = assignmentClass;
    return this;
  }

   /**
   * Get assignmentClass
   * @return assignmentClass
  **/
  public String getAssignmentClass() {
    return assignmentClass;
  }

  public void setAssignmentClass(String assignmentClass) {
    this.assignmentClass = assignmentClass;
  }

  public SFODataEmpEmploymentUpdate assignmentIdExternal(String assignmentIdExternal) {
    this.assignmentIdExternal = assignmentIdExternal;
    return this;
  }

   /**
   * Get assignmentIdExternal
   * @return assignmentIdExternal
  **/
  public String getAssignmentIdExternal() {
    return assignmentIdExternal;
  }

  public void setAssignmentIdExternal(String assignmentIdExternal) {
    this.assignmentIdExternal = assignmentIdExternal;
  }

  public SFODataEmpEmploymentUpdate createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public SFODataEmpEmploymentUpdate createdDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public SFODataEmpEmploymentUpdate createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public SFODataEmpEmploymentUpdate customDate10(OffsetDateTime customDate10) {
    this.customDate10 = customDate10;
    return this;
  }

   /**
   * Get customDate10
   * @return customDate10
  **/
  public OffsetDateTime getCustomDate10() {
    return customDate10;
  }

  public void setCustomDate10(OffsetDateTime customDate10) {
    this.customDate10 = customDate10;
  }

  public SFODataEmpEmploymentUpdate customDate11(OffsetDateTime customDate11) {
    this.customDate11 = customDate11;
    return this;
  }

   /**
   * Get customDate11
   * @return customDate11
  **/
  public OffsetDateTime getCustomDate11() {
    return customDate11;
  }

  public void setCustomDate11(OffsetDateTime customDate11) {
    this.customDate11 = customDate11;
  }

  public SFODataEmpEmploymentUpdate customDate12(OffsetDateTime customDate12) {
    this.customDate12 = customDate12;
    return this;
  }

   /**
   * Get customDate12
   * @return customDate12
  **/
  public OffsetDateTime getCustomDate12() {
    return customDate12;
  }

  public void setCustomDate12(OffsetDateTime customDate12) {
    this.customDate12 = customDate12;
  }

  public SFODataEmpEmploymentUpdate customDate6(OffsetDateTime customDate6) {
    this.customDate6 = customDate6;
    return this;
  }

   /**
   * Get customDate6
   * @return customDate6
  **/
  public OffsetDateTime getCustomDate6() {
    return customDate6;
  }

  public void setCustomDate6(OffsetDateTime customDate6) {
    this.customDate6 = customDate6;
  }

  public SFODataEmpEmploymentUpdate customDate7(OffsetDateTime customDate7) {
    this.customDate7 = customDate7;
    return this;
  }

   /**
   * Get customDate7
   * @return customDate7
  **/
  public OffsetDateTime getCustomDate7() {
    return customDate7;
  }

  public void setCustomDate7(OffsetDateTime customDate7) {
    this.customDate7 = customDate7;
  }

  public SFODataEmpEmploymentUpdate customDate8(OffsetDateTime customDate8) {
    this.customDate8 = customDate8;
    return this;
  }

   /**
   * Get customDate8
   * @return customDate8
  **/
  public OffsetDateTime getCustomDate8() {
    return customDate8;
  }

  public void setCustomDate8(OffsetDateTime customDate8) {
    this.customDate8 = customDate8;
  }

  public SFODataEmpEmploymentUpdate customDate9(OffsetDateTime customDate9) {
    this.customDate9 = customDate9;
    return this;
  }

   /**
   * Get customDate9
   * @return customDate9
  **/
  public OffsetDateTime getCustomDate9() {
    return customDate9;
  }

  public void setCustomDate9(OffsetDateTime customDate9) {
    this.customDate9 = customDate9;
  }

  public SFODataEmpEmploymentUpdate endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public SFODataEmpEmploymentUpdate hiringNotCompleted(Boolean hiringNotCompleted) {
    this.hiringNotCompleted = hiringNotCompleted;
    return this;
  }

   /**
   * Get hiringNotCompleted
   * @return hiringNotCompleted
  **/
  public Boolean isHiringNotCompleted() {
    return hiringNotCompleted;
  }

  public void setHiringNotCompleted(Boolean hiringNotCompleted) {
    this.hiringNotCompleted = hiringNotCompleted;
  }

  public SFODataEmpEmploymentUpdate includeAllRecords(Boolean includeAllRecords) {
    this.includeAllRecords = includeAllRecords;
    return this;
  }

   /**
   * Get includeAllRecords
   * @return includeAllRecords
  **/
  public Boolean isIncludeAllRecords() {
    return includeAllRecords;
  }

  public void setIncludeAllRecords(Boolean includeAllRecords) {
    this.includeAllRecords = includeAllRecords;
  }

  public SFODataEmpEmploymentUpdate isECRecord(Boolean isECRecord) {
    this.isECRecord = isECRecord;
    return this;
  }

   /**
   * Get isECRecord
   * @return isECRecord
  **/
  public Boolean isIsECRecord() {
    return isECRecord;
  }

  public void setIsECRecord(Boolean isECRecord) {
    this.isECRecord = isECRecord;
  }

  public SFODataEmpEmploymentUpdate isPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * Get isPrimary
   * @return isPrimary
  **/
  public Boolean isIsPrimary() {
    return isPrimary;
  }

  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }

  public SFODataEmpEmploymentUpdate jobNumber(AnyOfSFODataEmpEmploymentUpdateJobNumber jobNumber) {
    this.jobNumber = jobNumber;
    return this;
  }

   /**
   * Get jobNumber
   * @return jobNumber
  **/
  public AnyOfSFODataEmpEmploymentUpdateJobNumber getJobNumber() {
    return jobNumber;
  }

  public void setJobNumber(AnyOfSFODataEmpEmploymentUpdateJobNumber jobNumber) {
    this.jobNumber = jobNumber;
  }

  public SFODataEmpEmploymentUpdate lastDateWorked(OffsetDateTime lastDateWorked) {
    this.lastDateWorked = lastDateWorked;
    return this;
  }

   /**
   * Get lastDateWorked
   * @return lastDateWorked
  **/
  public OffsetDateTime getLastDateWorked() {
    return lastDateWorked;
  }

  public void setLastDateWorked(OffsetDateTime lastDateWorked) {
    this.lastDateWorked = lastDateWorked;
  }

  public SFODataEmpEmploymentUpdate lastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Get lastModifiedBy
   * @return lastModifiedBy
  **/
  public String getLastModifiedBy() {
    return lastModifiedBy;
  }

  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  public SFODataEmpEmploymentUpdate lastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  public OffsetDateTime getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(OffsetDateTime lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SFODataEmpEmploymentUpdate lastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  public OffsetDateTime getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(OffsetDateTime lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public SFODataEmpEmploymentUpdate notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public SFODataEmpEmploymentUpdate okToRehire(Boolean okToRehire) {
    this.okToRehire = okToRehire;
    return this;
  }

   /**
   * Get okToRehire
   * @return okToRehire
  **/
  public Boolean isOkToRehire() {
    return okToRehire;
  }

  public void setOkToRehire(Boolean okToRehire) {
    this.okToRehire = okToRehire;
  }

  public SFODataEmpEmploymentUpdate originalStartDate(OffsetDateTime originalStartDate) {
    this.originalStartDate = originalStartDate;
    return this;
  }

   /**
   * Get originalStartDate
   * @return originalStartDate
  **/
  public OffsetDateTime getOriginalStartDate() {
    return originalStartDate;
  }

  public void setOriginalStartDate(OffsetDateTime originalStartDate) {
    this.originalStartDate = originalStartDate;
  }

  public SFODataEmpEmploymentUpdate serviceDate(OffsetDateTime serviceDate) {
    this.serviceDate = serviceDate;
    return this;
  }

   /**
   * Get serviceDate
   * @return serviceDate
  **/
  public OffsetDateTime getServiceDate() {
    return serviceDate;
  }

  public void setServiceDate(OffsetDateTime serviceDate) {
    this.serviceDate = serviceDate;
  }

  public SFODataEmpEmploymentUpdate startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SFODataEmpEmploymentUpdate sfODataEmpEmploymentUpdate = (SFODataEmpEmploymentUpdate) o;
    return Objects.equals(this.assignmentClass, sfODataEmpEmploymentUpdate.assignmentClass) &&
        Objects.equals(this.assignmentIdExternal, sfODataEmpEmploymentUpdate.assignmentIdExternal) &&
        Objects.equals(this.createdBy, sfODataEmpEmploymentUpdate.createdBy) &&
        Objects.equals(this.createdDateTime, sfODataEmpEmploymentUpdate.createdDateTime) &&
        Objects.equals(this.createdOn, sfODataEmpEmploymentUpdate.createdOn) &&
        Objects.equals(this.customDate10, sfODataEmpEmploymentUpdate.customDate10) &&
        Objects.equals(this.customDate11, sfODataEmpEmploymentUpdate.customDate11) &&
        Objects.equals(this.customDate12, sfODataEmpEmploymentUpdate.customDate12) &&
        Objects.equals(this.customDate6, sfODataEmpEmploymentUpdate.customDate6) &&
        Objects.equals(this.customDate7, sfODataEmpEmploymentUpdate.customDate7) &&
        Objects.equals(this.customDate8, sfODataEmpEmploymentUpdate.customDate8) &&
        Objects.equals(this.customDate9, sfODataEmpEmploymentUpdate.customDate9) &&
        Objects.equals(this.endDate, sfODataEmpEmploymentUpdate.endDate) &&
        Objects.equals(this.hiringNotCompleted, sfODataEmpEmploymentUpdate.hiringNotCompleted) &&
        Objects.equals(this.includeAllRecords, sfODataEmpEmploymentUpdate.includeAllRecords) &&
        Objects.equals(this.isECRecord, sfODataEmpEmploymentUpdate.isECRecord) &&
        Objects.equals(this.isPrimary, sfODataEmpEmploymentUpdate.isPrimary) &&
        Objects.equals(this.jobNumber, sfODataEmpEmploymentUpdate.jobNumber) &&
        Objects.equals(this.lastDateWorked, sfODataEmpEmploymentUpdate.lastDateWorked) &&
        Objects.equals(this.lastModifiedBy, sfODataEmpEmploymentUpdate.lastModifiedBy) &&
        Objects.equals(this.lastModifiedDateTime, sfODataEmpEmploymentUpdate.lastModifiedDateTime) &&
        Objects.equals(this.lastModifiedOn, sfODataEmpEmploymentUpdate.lastModifiedOn) &&
        Objects.equals(this.notes, sfODataEmpEmploymentUpdate.notes) &&
        Objects.equals(this.okToRehire, sfODataEmpEmploymentUpdate.okToRehire) &&
        Objects.equals(this.originalStartDate, sfODataEmpEmploymentUpdate.originalStartDate) &&
        Objects.equals(this.serviceDate, sfODataEmpEmploymentUpdate.serviceDate) &&
        Objects.equals(this.startDate, sfODataEmpEmploymentUpdate.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignmentClass, assignmentIdExternal, createdBy, createdDateTime, createdOn, customDate10, customDate11, customDate12, customDate6, customDate7, customDate8, customDate9, endDate, hiringNotCompleted, includeAllRecords, isECRecord, isPrimary, jobNumber, lastDateWorked, lastModifiedBy, lastModifiedDateTime, lastModifiedOn, notes, okToRehire, originalStartDate, serviceDate, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SFODataEmpEmploymentUpdate {\n");
    
    sb.append("    assignmentClass: ").append(toIndentedString(assignmentClass)).append("\n");
    sb.append("    assignmentIdExternal: ").append(toIndentedString(assignmentIdExternal)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    customDate10: ").append(toIndentedString(customDate10)).append("\n");
    sb.append("    customDate11: ").append(toIndentedString(customDate11)).append("\n");
    sb.append("    customDate12: ").append(toIndentedString(customDate12)).append("\n");
    sb.append("    customDate6: ").append(toIndentedString(customDate6)).append("\n");
    sb.append("    customDate7: ").append(toIndentedString(customDate7)).append("\n");
    sb.append("    customDate8: ").append(toIndentedString(customDate8)).append("\n");
    sb.append("    customDate9: ").append(toIndentedString(customDate9)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    hiringNotCompleted: ").append(toIndentedString(hiringNotCompleted)).append("\n");
    sb.append("    includeAllRecords: ").append(toIndentedString(includeAllRecords)).append("\n");
    sb.append("    isECRecord: ").append(toIndentedString(isECRecord)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    jobNumber: ").append(toIndentedString(jobNumber)).append("\n");
    sb.append("    lastDateWorked: ").append(toIndentedString(lastDateWorked)).append("\n");
    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    okToRehire: ").append(toIndentedString(okToRehire)).append("\n");
    sb.append("    originalStartDate: ").append(toIndentedString(originalStartDate)).append("\n");
    sb.append("    serviceDate: ").append(toIndentedString(serviceDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
